### ISSUE TITLE
2FA Section

### ISSUE THREAD

**Issue by freddy-m** [privacyguides/privacyguides.org#10]
## Description

A section dedicated to two-factor authentication (2FA). Potenial software to include could be:

- Aegis Authenticator  
- andOTP

---

This page *could* also be used as a template: https://thenewoil.xyz/mfa.html

**Comment by GintokiHub** [comment]
Authenticator Pro by jmh - seems to be updated constantly ,
it's also on f-droid & here : https://github.com/jamie-mh/AuthenticatorPro

**Comment by dngray** [comment]
I would go to Aegis Authenticator. Some time ago @lynn-stephenson looked into this and determined the password encryption was better on Aegis.

afaik andOTP uses a heap of rounds of PBKDF2, and when you have a lot of passwords it opens really slowly.

**Comment by dngray** [comment]
On iOS I usually recommend: "Authenticator" 

- https://mattrubin.me/authenticator
- https://apps.apple.com/us/app/authenticator/id766157276
- https://github.com/mattrubin/Authenticator

**Comment by freddy-m** [comment]
@dngray I use Aegis and love it! I'll take your word for the use of "Authenitcator" for iOS.

**Comment by danarel** [comment]
I would highly recommend Ravio OTP as well

https://github.com/raivo-otp/ios-application
