### ISSUE TITLE
EXIF wiki page is linked too many times

### ISSUE THREAD

**Issue by flexagoon** [privacyguides/privacyguides.org#1005]
## Description

I feel like https://en.wikipedia.org/wiki/Exif is linked too many times on the metadata removal page

**URL of affected page:**

https://www.privacyguides.org/metadata-removal-tools/

**Comment by lx-is** [comment]
Agreed lol

A collapsable admonition could work, featuring a brief explanation of what Exif is while also linking to external resources. Similar to the "When are VPN's useful?" admonition on [the vpn page](https://www.privacyguides.org/vpn/).

**Comment by dngray** [comment]
> I feel like https://en.wikipedia.org/wiki/Exif is linked too many times on the metadata removal page

From what I can see it's only linked in the first paragraph.
