### ISSUE TITLE
Password Managers: "encrypted container" link returns 404

### ISSUE THREAD

**Issue by cYDN48** [privacyguides/privacyguides.org#1036]
## Description
The "encrypted container" hyperlink in the second bullet point under "Password Best Practices" returns a 404 page.

Link in question: https://www.privacyguides.org/passwords/encryption

**Comment by dngray** [comment]
Fixed in https://github.com/privacyguides/privacyguides.org/commit/ff5b3ee504e65e41aa5b42eba3869f3c0e7fa0a5
