### ISSUE TITLE
Broken link to searx.me for Search Engines

### ISSUE THREAD

**Issue by taivlam** [privacyguides/privacyguides.org#1042]
## Description

The link to the [searx.me](https://searx.me/) instance doesn't work and give an error about not being able to outright connect.  (This isn't an issue with my VPN or Tor, because I'm getting the same result on my ISP on cellular data and my home Wi-Fi.)

However, I'm not sure how Privacy Guides can directly "fix" this, because I'm pretty sure this has been going on for some time (at least 1 1 week before writing this?).

### Other info (might not be related)

Not sure if this is related, but IIRC [searx.info](https://searx.info/) has general info on Searx (and no search engine capability itself), but it's also down with a 502 error status (which could be a coincidence).

Also, IIRC [searx.space](https://searx.space/) was never an "official" page, but at least it works right now (at the time I'm writing this).

**Comment by dngray** [comment]
I'm thinking this link should probably be updated to https://searx.github.io/searx/
