### ISSUE TITLE
password: keepassxc

### ISSUE THREAD

**Issue by frogtile** [privacyguides/privacyguides.org#107]
keepassxc and keepassdx are separate program, don't combine then into one.

**Comment by jonaharagon** [comment]
Context: KeePassDX is our currently recommended KeePassXC client on Android, as KeePassXC only has desktop clients

https://privacyguides.org/software/passwords/#pw

https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free

**Comment by frogtile** [comment]
They are separate application from separate parties, they should not be combined into one even if they work on compatible formats.

**Comment by frogtile** [comment]
> https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free

What is this?

This tells more.
