### ISSUE TITLE
Replace the "Visit website.example" buttons with "Visit Homepage" or "Visit Repository"

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#1094]
Kinda related but kinda not — I was thinking what if we replaced the "Visit website.example" purple buttons with "Visit Homepage" and "Visit Repository" instead. 

This would make the buttons more visually consistent with the privacy policy buttons, as well as solve the issue when a URL is really long or unappealing (e.g. the buttons on the [Magic Wormhole](https://www.privacyguides.org/file-sharing/#magic-wormhole) and [git-annex](https://www.privacyguides.org/file-sharing/#git-annex) cards).

_Originally posted by @lx-is in https://github.com/privacyguides/privacyguides.org/issues/1093#issuecomment-1107663538_

**Comment by jonaharagon** [comment]
Yes, this is a change I wanted to make after switching to mkdocs.

I wonder if `Visit Homepage` or `Homepage` or `Project Homepage` is better.

**Comment by lx-is** [comment]
> I wonder if `Visit Homepage` or `Homepage` or `Project Homepage` is better.

My initial vote would go towards just "Homepage" but that might make the button look too short. I guess I'd have to see the options visually.

**Comment by flexagoon** [comment]
This will also make translation much easier 😉

**Comment by dngray** [comment]
I think this one is more a less finished if you want to review.
