### ISSUE TITLE
Plausible Analytics

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#1111]
This is sort of an issue to add a feature, sort of a community poll/RFC: I'm wondering whether we should add **self-hosted** [Plausible](https://plausible.io/) analytics to the site. 

It would actually be pretty useful to us to know which pages get the most traffic, what the bounce rate on each page is, where we're getting traffic from, etc. Bounce rates in particular would let us know what pages need reworking before others.

<details><summary>some history</summary>Way back in the day we used to use Matomo, but I didn't like it because it was kinda complex/old-fashioned, and it collected and saved a lot of data that was pretty irrelevant, and I don't like storing data for no reason. Also we had no way of easily making that data public, and lots of people were interested in seeing those stats that I couldn't give access to because of how much other data it collected. Plausible looks a lot better, and has built in public dashboards we could easily share in our readme.</details>

also see: https://plausible.io/vs-matomo

demo of data available: https://plausible.io/plausible.io

**Comment by lx-is** [comment]
I'm not against the idea, especially if the data is public (I'm curious as to what the numbers would be lol). I think some would blindly see the move as ironic or even hypocritical, but *blindly* is the key word there.

I remember researching web analytics for a side project I wanted to start and, if I had actually started the project, I believe I was going to settle with [umami](https://umami.is/) — so another option to look into if you want.

This also brings up the idea that the site could feature recommendations for web developers — site hosts, analytics, etc.

**Comment by dngray** [comment]
I don't believe there is any issue.

The data isn't particularly personal and being worried about it doesn't fit a threat model besides paranoia. It's not like we prevent people using Tor, or a VPN if they do want to hide their location.
