### ISSUE TITLE
Link to PrivacyGuides repository from PrivacyTools github

### ISSUE THREAD

**Issue by ignoramous** [privacyguides/privacyguides.org#112]
## Description

PrivacyTools github repositories have been archived, but don't link to corresponding privacyguides.org repositories. May be this is intentional (since privacytools.io doesn't link to privacyguides either)?

**URL of affected page:** https://github.com/privacytools/privacytools.io/

**Comment by dngray** [comment]
Thanks for opening this I've been meaning to do that.

**Comment by dngray** [comment]
[Done](https://github.com/privacytools/privacytools.io).

Fixed: https://github.com/privacytools/privacytools.io/commit/2210f90e4bf44ffaefaf66f3922913cbdd5fce06
Fixed: https://github.com/privacytools/.github/commit/9d59ecc9989a1fe6014f29e8c84ba045997f7c4e
