### ISSUE TITLE
Website Issue | Line length is too wide

### ISSUE THREAD

**Issue by Nautman** [privacyguides/privacyguides.org#113]
## Description

On wide screens, the text is too wide too be easily readable. I suggest that the text is condensed into smaller columns, like below. According to the [Refactoring UI](https://www.refactoringui.com) book, to create the best reading experience, "make your paragraphs wide enough to fit between 45 and 75 characters per line. [...]. A width of 20-35em will get you in the right ballpark".

## Potential fix

This is with a width of 35rem, or around `col-lg-6` class name. If you agree with me then I can open a PR for this.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28629647/133930871-79688866-b070-4651-a8f8-6335a482c342.png">

## Current situation

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28629647/133930648-9f89312b-8c7f-4ff0-982f-8e9ca7077e69.png">

**Comment by Nautman** [comment]
While discussing the topic, there are many places on this site where this could be applied. For example, when presenting page sections. 

## Fix
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28629647/133931055-6e5bdd9d-5dd6-4e10-adf8-d11f3b58a641.png">

## Current situation
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28629647/133931060-a591841a-60e9-46b5-80fb-b6629bc2dc08.png">

**Comment by dngray** [comment]
I'm inclined to agree with this. @jonaharagon?

**Comment by dngray** [comment]
Closing site has changed.
