### ISSUE TITLE
Anonaddy

### ISSUE THREAD

**Issue by Lostname777** [privacyguides/privacyguides.org#1138]
Now that we all know, Anonaddy supports OpenPGP encryption on their **free plan** it should be mentioned on this page: https://www.privacyguides.org/email/#email-cloaking-services

What is your take on this?

**Comment by dngray** [comment]
I think this is something they changed, initially it didn't.

**Comment by dngray** [comment]
> > I think this is something they changed, initially it didn't.
> 
> I don't understand the point. If they have changed it now, so you should also add that positive security point in the website.

I was just letting @lx-is know.
