### ISSUE TITLE
ControlD does not support DNSSEC

### ISSUE THREAD

**Issue by prestr** [privacyguides/privacyguides.org#1221]
## Description
While using ControlD did a test on https://cmdns.dev.dns-oarc.net/ and https://cmdns.dev.dns-oarc.net/ and it said DNSSEC was failing. 
I reached out to ControlD via email and they advised "Control D DNS does not support DNSSEC.". I also got the same response on reddit. 

**URL of affected page:** https://www.privacyguides.org/dns/

**Comment by mfwmyfacewhen** [comment]
That's one of the requirements for the recommendations so I think it should be removed. Did the test myself and got the same thing.

**Comment by Dyrimon** [comment]
In a [reddit comment](https://www.reddit.com/r/ControlD/comments/okb7g6/comment/h56tmqz/?utm_source=share&utm_medium=web2x&context=3) @yegors says DNSSEC is enforced.

**Comment by prestr** [comment]
> In a [reddit comment](https://www.reddit.com/r/ControlD/comments/okb7g6/comment/h56tmqz/?utm_source=share&utm_medium=web2x&context=3) @yegors says DNSSEC is enforced.

I guess I need to stop deleting my reddit posts. He said a few weeks ago its not used.
