### ISSUE TITLE
Safari does not meet the browser requirements laid out on the wiki

### ISSUE THREAD

**Issue by mfwmyfacewhen** [privacyguides/privacyguides.org#1226]
## Description
Safari on iOS doesn't let you freely configure your search engine, but the wiki states that a freely configurable search engine is a requirement. Personally, I don't think this needs to be a requirement since duckduckgo is included as a default option and what search engine you pick doesn't matter that much anyway as you can't verify that they aren't logging your searches.

**URL of affected page:** https://github.com/privacyguides/privacyguides.org/wiki/Page-Criteria#privacy-features

**Comment by dngray** [comment]
Those were only very early draft discussion points, that's why they hadn't been merged over into the pages

**Comment by mfwmyfacewhen** [comment]
> Those were only very early draft discussion points, that's why they hadn't been merged over into the pages.
> 
> Now that the pages are complete, we should start moving that criteria back to the pages.

Ok I thought they were final, but good to know :+1:
