### ISSUE TITLE
download format inconsistency in recommendation card

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacyguides/privacyguides.org#1235]
## Description
I noticed that sometimes Github/Gitlab/git is used as word in the download format and sometimes the word 'Source'. Which one is preferred? If i know this i'll create a PR to iron out this inconsistency. Personally i think the source would be a better fit.
![github](https://user-images.githubusercontent.com/73130443/168476939-62d37f70-5bf3-4f9a-a6fa-f65d3dada4f8.PNG)

![source](https://user-images.githubusercontent.com/73130443/168476942-7b87bd5b-e4b6-4aea-871b-8ec1adb2aa84.PNG)

**Comment by dngray** [comment]
> Personally i think the source would be a better fit

I agree, as long as the logo remains, its all good. I think this is from legacy, source is what we are doing now.

**Comment by mfwmyfacewhen** [comment]
Yeah source is probably the best.
