### ISSUE TITLE
PrivacyGuides is in serious decline.

### ISSUE THREAD

**Issue by anon238** [privacyguides/privacyguides.org#1266]
Are these PrivacyGuide's maintaners? If so, I will never visit your page again. First a big mouth with Ctemplar and then the contrary was proven and now lies upon lies again. Just go or stop with thinking privacy guides are a competition.

![B1159E90-2AA6-423A-AE7D-18397394F223](https://user-images.githubusercontent.com/76251639/169108710-97d2d3da-1ad1-43e0-ad60-7e7d02155ad1.jpg)

**Comment by jonaharagon** [comment]
Why would writing privacy guides be a competition? lol

**Comment by anon238** [comment]
> 

Ask your moderator that, but as usual a big mouth, but no added value in terms of content.
