### ISSUE TITLE
FairEmail is discontinued

### ISSUE THREAD

**Issue by flexagoon** [privacyguides/privacyguides.org#1273]
## Description

The developer of FairEmail and NetGuard discontinued both apps. As the FairEmail website says:

> All my projects have been terminated after Google falsely flagged FairEmail as spyware without a reasonable opportunity to appeal. There will be no further development and no more support.

There's also more info from the developer in this XDA thread:

https://forum.xda-developers.com/t/app-5-0-fairemail-fully-featured-open-source-privacy-oriented-email-app.3824168/post-86908335

https://forum.xda-developers.com/t/app-5-0-fairemail-fully-featured-open-source-privacy-oriented-email-app.3824168/post-86909853

**URL of affected page:**

https://www.privacyguides.org/email-clients

**Comment by DoktorScience** [comment]
It looks like the issue was solved through Google's support.

https://forum.xda-developers.com/t/app-5-0-fairemail-fully-featured-open-source-privacy-oriented-email-app.3824168/page-1108#post-86940513

It seems development may continue after all. I would suggest reverting #1270 for now.
