### ISSUE TITLE
Markdown headers do not have anchor hyperlinks

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacyguides/privacyguides.org#132]
## Description
This is how it supposed to be. First the big header title and then the H2 i guess with the link.

![Capture](https://user-images.githubusercontent.com/73130443/134236039-6b2c6023-8816-41fa-ae51-18c6ecfc37b4.PNG)

1. Here are the headers that need some attention:

https://user-images.githubusercontent.com/73130443/134238479-4b8efa82-ed85-490d-bc78-ac5a1102219a.mp4

https://user-images.githubusercontent.com/73130443/134238641-2876ce7f-2b66-443e-a4c4-3e4e054cee0a.mp4

2. So here u only have the big title and no h2 beneath the title. So there is obiously no where to link to.

![link to dns header](https://user-images.githubusercontent.com/73130443/134238793-66b8c0a5-8e16-4252-85eb-d21f8ad5c04c.PNG)
![link to browser header](https://user-images.githubusercontent.com/73130443/134238799-5454abc7-6f8a-4d12-b283-e3d7a52f0ade.PNG)

3. Lastly u have to links here pointing to the same section. You can remove one or add some text between them.

![two links](https://user-images.githubusercontent.com/73130443/134238909-0ced4d1f-a81e-4ca3-9840-f751f3d90c7c.PNG)

**URL of affected page:**
1&2 https://privacyguides.org/providers/dns/, https://privacyguides.org/browsers/

3. https://privacyguides.org/software/email/#mobileclients, https://privacyguides.org/operating-systems/#mobile_os

**Comment by peepopoggers** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc :monocle_face:

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
*insert surprised pikachu face*

**Comment by jonaharagon** [comment]
This is actually an issue with Jekyll's Markdown renderer, which we'll need to fix as we transition to more MD pages...

**Comment by dngray** [comment]
The anchor links do actually exist. I think though in the future we'll go to putting them after the heading and making them almost invisible, rather than big and obnoxious like they were.

**Comment by dngray** [comment]
This will likely get resolved when we do https://github.com/privacyguides/privacyguides.org/issues/802
