### ISSUE TITLE
Piped instances privacy policy

### ISSUE THREAD

**Issue by Lostname777** [privacyguides/privacyguides.org#1325]
You said "When you are using a Piped instance, make sure to read the privacy policy of that specific instance.". But where the heck is privacy policy of individual instances of piped, I couldn't find them.

URL of Affected Page: https://www.privacyguides.org/video-streaming/#piped

**Comment by EdwardLangdon** [comment]
Piped doesn't offer one.

**Comment by dngray** [comment]
Well if the specific instance provides one there might be one.

**Comment by Lostname777** [comment]
I am asking where is it, I couldn't find it

**Comment by EdwardLangdon** [comment]
For Example, https://piped.mha.fi. For this Instance, The Privacy Policy applies from their General ones. See here - https://mha.fi/privacy/

**Comment by dngray** [comment]
I think we'll close this one, like Invidious instances it's going to be different for each instance.

We do not link to specific instances [because we don't want to overload them](https://github.com/orgs/privacyguides/discussions/341#discussioncomment-1665953).

**Comment by Lostname777** [comment]
HEY!!! The issue is that privacy policies are not even present and PG says that check through their Privacy policies.
The only one present is the one linked by EdwardLangdon above. None other.
I was able to open mint.lgbt, and their privacy policy said that they collect ip and store it. But I cannot say it's same for their piped instance as it's not specified.

**Comment by jonaharagon** [comment]
If a website does not provide a privacy policy that is probably a good indicator that you should not use that website.

**Comment by Lostname777** [comment]
What?! PG recommends Piped. So it's not trustworthy if it doesn't have privacy policy?

**Comment by dngray** [comment]
> PG recommends Piped

Indeed the software.

> So it's not trustworthy if it doesn't have privacy policy?

We don't endorse specific instances. Privacy Policy will differ per instance.

**Comment by Lostname777** [comment]
> We don't endorse specific instances. Privacy Policy will differ per instance.

dafuq, I am saying it doesn't even have a privacy policy in the first place.

**Comment by flexagoon** [comment]
@Lostname777 some instances do
