### ISSUE TITLE
Minify HTML & CSS

### ISSUE THREAD

**Issue by 27lx** [privacyguides/privacyguides.org#1343]
Taking a look at the HTML output served, it's quite a mess. Hundreds of lines of whitespace and really strange indentation. Solution to this would probably be to use [mkdocs-minify-plugin](https://github.com/byrnereese/mkdocs-minify-plugin), if possible. The base CSS files are already minified, however extra.css isn't.

https://user-images.githubusercontent.com/100533118/170815351-020bede8-2387-4df4-b12d-8c2fa48be5aa.mp4

**Comment by noClaps** [comment]
Minifying extra.css works if you store the svg for the downloads icon separately and then link to the svg file.

Something like this: https://codeberg.org/tcgmoo/pages/src/commit/7a1f71f9dacf6436d91d0f27b2f060b8235225ee/docs/assets/stylesheets/extra.css#L122

If you look at the generated extra.min.css, the minifier seems to have removed the spaces between the svg code in the css, which causes the image to not load properly.
