### ISSUE TITLE
Disclaimer for ProtonMail

### ISSUE THREAD

**Issue by ut-kr** [privacyguides/privacyguides.org#1344]
## Description
I believe it is worth mentioning somewhere in this section that Protonmail does in fact store user **IP addresses** and **Device information**, which it shares with the authorities if/when requested. They themselves, because of this, recommend using the service over tor to gain the true anonymity that we expect.

**Source:**
- https://www.youtube.com/watch?v=QCx_G_R0UmQ
- https://proton.me/news/climate-activist-arrest
- https://mobile.twitter.com/tenacioustek/status/1434604102676271106
- https://www.reddit.com/r/ProtonMail/comments/pil6xi/climate_activist_arrested_after_protonmail/hbqha63/

**URL of affected page:** https://www.privacyguides.org/email/#protonmail

**Comment by dngray** [comment]
This is not new, and you can assume all providers will do this.

**Comment by dngray** [comment]
This is not new, and you can assume all providers will do this. Email has a lot of metadata, and providers will always comply with judicial requests.

There is no reason to single Proton out for this.

Regarding that particular case about the alleged "climate activist". The media latched onto that, we're not even sure if it is true or if that was even the reason the request was made. More details were provided by the Proton CEO in https://twitter.com/andyyen/status/1434665927631679491

Also don't use Mental Outlaw as a source, they are not reliable, and are mostly a sensationalist youtube parrot.
