### ISSUE TITLE
Fix spelling in VPN Services section

### ISSUE THREAD

**Issue by brentoer** [privacyguides/privacyguides.org#1348]
## Description
The following has spelling mistakes:
"Thus, this feature should be viewed as a convenient way to access the Tor Network, not to stay annonymous. For true anonimity, use the Tor Browser Bundle, TorSocks, or a Tor gateway."

(annonymous and anonimity)

**URL of affected page:**
https://www.privacyguides.org/vpn/#what-if-i-need-anonymity

**Comment by 27lx** [comment]
Thanks!
