### ISSUE TITLE
Change the Firefox logo without the fox with the Firefox logo with the fox in the extension seccion

### ISSUE THREAD

**Issue by EvilEZNS** [privacyguides/privacyguides.org#137]
Change the Firefox logo without the fox with the normal normal one for the new people that don't know that are the same.

It should seen like this:

![](http://cdn.osxdaily.com/wp-content/uploads/2007/05/firefox-logo.jpg)

**Comment by PoorPocketsMcNewHold** [comment]
Whenever you like it or not, This isn't the actual up-to-date used logo.
