### ISSUE TITLE
Website Issue | Align logo with hamburger button on mobile < 396px and header styling

### ISSUE THREAD

**Issue by sakerhetspolisen** [privacyguides/privacyguides.org#144]
## Description
Logo needs to be made smaller on mobile screens smaller than 396px, so that the hamburger button can be aligned correctly. Also, the default Bootstrap hamburger is quite ugly.

This:

![Screen Shot 2021-09-29 at 11 24 56](https://user-images.githubusercontent.com/68159964/135242302-e00c5e6c-f08e-4909-8df4-9435db6ce2f1.png)

Should become something like this:

![iPhone 8 - 1](https://user-images.githubusercontent.com/68159964/135244155-79750b14-ac59-4c75-be1c-99a4f7b702a3.png)

Maybe a sticky header?

![iPhone 8 - 2](https://user-images.githubusercontent.com/68159964/135244168-3ea778a1-291c-442e-aa90-71d79d485251.png)

**Comment by peepopoggers** [comment]
Did you make a mockup or did you code this?

**Comment by sakerhetspolisen** [comment]
This was just a mockup!
