### ISSUE TITLE
Removal of HTTPS Everywhere 

### ISSUE THREAD

**Issue by CTZxVULKAN** [privacyguides/privacyguides.org#145]
## Description

EFF has announced that HTTPS Everywhere browser extension will be soon depreciated by the end of 2021 as modern web browsers already have native support to forcefully encrypt `http` sites to `https`.

"With these simple settings available, EFF is preparing to deprecate the HTTPS Everywhere web extension as we look to new frontiers of secure protocols like SSL/TLS. After the end of this year, the extension will be in “maintenance mode.” for 2022. "
~ EFF
* Source : https://www.eff.org/deeplinks/2021/09/https-actually-everywhere  

This makes no sense in keeping the extension further enlisted in privacyguides.org .

## Suggestion 

Normal users generally tend not to update themselves on a regular basis. In this case referring a **soon to be depriciated** extension to such a consumer base is not paticularly a good option. It is best for a privacy guide to stay as updated as a browser so that its users at any point can get the correct information they need and not an older alternative solution to the problem.

PrivacyGuides should rather encourage users to enable the native settings (available on both firefox and chromium and all its derivatives) manually as they offer the same functionality.

**URL of affected page:**
https://privacyguides.org/browsers/

**Comment by CTZxVULKAN** [comment]
I would love to hear what the maintainers have to say on this.
Thankyou :)

**Comment by Mikaela** [comment]
Personally I would keep HTTPS Everywhere listed until it gets formally discontinued as it's easier to use than the instructions on that page, especially Edge and Firefox mobile:

> Edge
> 
> This is still considered an “experimental feature” in Edge, but is available in Edge 92.
> 
> Visit edge://flags/#edge-automatic-https and enable Automatic HTTPS
> Hit the “Restart” button that appears to restart Microsoft Edge.
> Visit edge://settings/privacy, scroll down, and turn on “Automatically switch to more secure connections with Automatic HTTPS”.
> * * * * *
> HTTPS-only for mobile is currently only available in Firefox Developer mode, which advanced users can enable in about:config. 

I don't know about Chrome on whether it would sync, but Edge doesn't sync it, so the user would need to perform these steps every time they open a new browser at a different place.

I hope this will become easier/automatic for the user before HTTPS Everywhere is gone.

**Comment by peepopoggers** [comment]
A "discontinued soon" suggestion could be added though. What do you guys think?

**Comment by CTZxVULKAN** [comment]
Yeah that should be done atleast for now.
General users think extensions are *install and forget* tools and wont update themselves on a regular basis.
Its best for them to know before hand that they are about to install an about to be depreciated extension.

**Comment by Mikaela** [comment]
I opened a question on HTTPS Everywhere what will happen once the discontinuation happens.

* https://github.com/EFForg/https-everywhere/discussions/20138

There is a hint that the extension will stop working at least in Chrome in January 2023 as MV2 is deprecated and the extension won't be ported. I have no idea what that is though.

* https://github.com/EFForg/https-everywhere/discussions/20137#discussioncomment-1398861

**Comment by elitejake** [comment]
> A "discontinued soon" suggestion could be added though. What do you guys think?

How does this look?

![image](https://user-images.githubusercontent.com/74049394/135659236-4401e5b4-88e5-492d-b138-2646c1881367.png)

Hovering over _Deprecation Warning_ will bring up a tooltip stating that `EFF will deprecate HTTPS Everywhere in 2022`.

Should I open a PR?

**Comment by peepopoggers** [comment]
:+1: yes looks good

**Comment by realmain** [comment]
The Android version of Firefox still needs HTTPS Everywhere. We should have a note for that. There is no HTTPS-Only Mode for Android Firefox.

**Comment by CTZxVULKAN** [comment]
This is great :)

**Comment by Mikaela** [comment]
An HTTPS Everywhere maintainer (zoracon) answers:

> The extension won't be taken down until late next year (winter, likely). Before then we want to utilize existing mechanisms to remove the extension from Firefox.
> 
> There's also a plan to give user prompts, depending on their browser, from the HTTPS Everywhere Home Page. To alleviate the situations where the user has to dig to find a setting. Like in Edge.
> 
> Lastly, we will publicly archive the last release of the extension and update the add-on/extensions store pages that it will be no longer updated or maintained before hand.
> 
> Any other suggestions are welcome to assist users! We want to make this transition as smooth as we can.

* https://github.com/EFForg/https-everywhere/discussions/20138#discussioncomment-1439427
