### ISSUE TITLE
#vaultwarden

### ISSUE THREAD

**Issue by masvil** [privacyguides/privacyguides.org#1467]
## Description

On https://www.privacyguides.org/tools/#multi-factor-authentication-tools there is a link to https://www.privacyguides.org/passwords/#vaultwarden, but #vaultwarden doesn't exist

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Issue is still valid. It should redirect to bitwarden instead of the current behavior

**Comment by EdwardLangdon** [comment]
They made Vaultwarden under Bitwarden as Vaultwarden is a fork of bitwarden for Smaller deployments not a separate app.

**Comment by EdwardLangdon** [comment]
I understand now. I'll open a PR.

**Comment by dngray** [comment]
Yes it looks like this got updated without the entry on the tools page.
