### ISSUE TITLE
Clicking on the blog button gives a  "404 - Not found" error

### ISSUE THREAD

**Issue by TheW0LVERIN3** [privacyguides/privacyguides.org#1476]
## Description
When going to [privacyguides.org](https://www.privacyguides.org/) and clicking on the blog button, it redirects to https://www.privacyguides.org/blog/2022/06/09/hide-nothing.md and gives a "404 - Not found" error.

![image](https://user-images.githubusercontent.com/44342613/175131052-ace7d9e2-7cd5-4cfd-8ad5-f392b95991d5.png)

**Comment by dngray** [comment]
This should be fixed in https://github.com/privacyguides/privacyguides.org/commit/f538a2c7c868341476d0f7fb0c5b02a96bc3f9d7
