### ISSUE TITLE
Missing information, Storage Section, File Erasure

### ISSUE THREAD

**Issue by Batcherdink** [privacyguides/privacyguides.org#1491]
### First issue

The "Erasing Specific Files" section does not mention that traditional secure erase is totally possible on HDD (Magnetic)

### Second issue

The "Erasing Specific Files" section does not mention that for some extra paranoia, you can at least issue a Trim operation after deletion of files on an SSD/NVMe. Studies have shown that it's close to impossible to recover after a Trim.

**https://www.privacyguides.org/advanced/erasing-data/#erasing-specific-files**

**Comment by dngray** [comment]
Erasure tools like this should never be trusted, what if the storage device fails in warranty and you want to return it? I just don't see the point when FDE comes these days at really no significant cost.

**Comment by tommytran732** [comment]
Don't forget CoW filesystems ;)
Trim is really not going to save you there

**Comment by dngray** [comment]
Every time I see TGHOA mentioned I cringe, because it's the most god awful document to read, and that's just because it's so poorly presented.
