### ISSUE TITLE
Use mkdocs.insiders.yml and requirements.txt files

### ISSUE THREAD

**Issue by noClaps** [privacyguides/privacyguides.org#1504]
## Description
PG should use a [`mkdocs.insiders.yml`](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins) file for any insider plugins and features, so that anyone contributing to PG that doesn't have access to the insiders repo can do so easily. Right now, if I want to contribute to PG, I have to comment out the privacy plugin every time while testing on my local machine, and uncomment before I push my changes to my branch. If I forget to uncomment, and it gets merged into the main branch, that could cause issues.

PG should also use a[ `requirements.txt`](https://pip.pypa.io/en/stable/user_guide/#requirements-files) file to make installing plugins easier using `pip`, since those contributing won't have to type out or copy a long command. Also, in the event that PG changes the external plugins used, the `pip install` command in README won't have to be updated every time, only the `requirements.txt` file will.

**Comment by jonaharagon** [comment]
We can't have a `requirements.txt` and a `Pipfile`, but at least once the mkdocs configuration is split that long `pip install ...` command can be made shorter, and will have to be updated less frequently since new external plugins will probably just go in the production/insiders config.
