### ISSUE TITLE
Check LUKS2 Encrypted boot

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1514]
## Description

**URL of affected page: https://privacyguides.org/linux-desktop/hardening/#secure-boot**

Looks like [GRUB supports LUKS2](https://www.phoronix.com/scan.php?page=news_item&px=GRUB-Boots-LUKS2-Disk-Encrypt). This [comment](https://libredd.it/r/PrivacyGuides/comments/timghp/new_linux_desktop_page/i1h30je/?context=3) seems to suggest `systemd-boot` can also boot an encrypted LUKS2 partition, but I've not seen any information about that.

We should investigate this and update the page.

**Comment by d4rklynk** [comment]
I found this https://www.gnu.org/software/grub/manual/grub/grub.pdf at chapter `16.3.19 cryptomount`

> GRUB suports devices encrypted using LUKS, LUKS2 and geli. Note that necessary
modules (luks, luks2 and geli) have to be loaded manually before this command can be used. For LUKS2 only the PBKDF2 key derivation function is supported, as
Argon2 is not yet supported.

**Comment by dngray** [comment]
At this point we wouldn't be recommending a git tagged version of Grub. If I'm being honest, I really don't like the "encrypted boot" idea because it will never be part of an installer, and is certainly  redundant when you're using TPM  [`systemd-measure`](https://www.freedesktop.org/software/systemd/man/systemd-measure.html) which will no doubt become a better developed solution.

When I tried out encrypted encrypted Grub it was **super slow**, because the Grub implementation of even LUKS1 didn't have SSE support if I remember correctly.  I doubt it has been audited either, as nobody really uses except for hardcore nerds following the arch wiki.

I also totally see distributions in the future doing away with BIOS support, and only supporting [`systemd-boot`](https://en.wikipedia.org/wiki/Systemd-boot) only. Redhat already has made some attempt to do this [in F37](https://fedoraproject.org/wiki/Changes/DeprecateLegacyBIOS) and although rejected they have settled for making [UEFI the default](https://fedoraproject.org/wiki/Releases/37/ChangeSet).
