### ISSUE TITLE
Simplelogin free features

### ISSUE THREAD

**Issue by Lostname777** [privacyguides/privacyguides.org#1521]
Description: Your description of Simplelogin free features is correct. But apparently, I found out that if you enable stuff like PGP, add multiple sub domains, add multiple mail boxes, change settings of premium. When you have created your account, under free premium trial period.
It still remains intact even after the premium trial ends. So technically Simplelogin do support these features for free, and much more like shifting your email subject to your inbox content to remove that metadata.

URL of affected page: https://www.privacyguides.org/email/#simplelogin

**Comment by jonaharagon** [comment]
Yeah I think this is probably a "bug" on their end, which works in favor of its users, so they probably aren't interested in fixing it, but I don't think we would want to encourage people to take advantage of it as if it's an officially supported method of using the service.
