### ISSUE TITLE
Bromite still appears in the Recommendations page

### ISSUE THREAD

**Issue by Araraura** [privacyguides/privacyguides.org#1524]
![2022-07-10 21_46_40-Privacy Tools - Privacy Guides — Mozilla Firefox](https://user-images.githubusercontent.com/25017422/178158015-de9bd3ff-6e22-46c4-b353-924b79629fb3.png)

**Comment by flexagoon** [comment]
@Araraura this is supposed to happen, as PrivacyGuides is updated in releases. https://github.com/privacyguides/privacyguides.org/releases. Wait for the next version to be released.

**Comment by flexagoon** [comment]
This is supposed to happen, as PrivacyGuides is updated in releases. Just wait for the next version to be released.

https://github.com/privacyguides/privacyguides.org/releases

**Comment by flexagoon** [comment]
It no longer does
