### ISSUE TITLE
Potential Correction for graphene vs calyx page

### ISSUE THREAD

**Issue by donefool** [privacyguides/privacyguides.org#1545]
## Description
The page has a heading of "Why we recommend GrapheneOS over CalyxOS?" but I think "Why do we recommend GrapheneOS over CalyxOS?" OR "Why we recommend GrapheneOS over CalyxOS" without the exclamation mark (probably better) would be more suitable

Also "Below are some of the reasons we recommend GrapheneOS over CalyxOS." could possibly be rephrased to "Below are some of the reasons why we recommend GrapheneOS over CalyxOS."

**URL of affected page: https://www.privacyguides.org/android/grapheneos-vs-calyxos/**

**Comment by d4rklynk** [comment]
Merged in #1546
