### ISSUE TITLE
Rephrase Tails Description

### ISSUE THREAD

**Issue by donefool** [privacyguides/privacyguides.org#1550]
## Description
Currently one of the sentences says "Tails is great for counter forensics due to amnesia (meaning nothing is written to the disk); it is not a hardened distribution like Whonix." 

There are multiple ways this could be better phrased.

- "Tails is great for counter forensics due to amnesia (meaning nothing is written to the disk); however, it is not a hardened distribution like Whonix." 
- "While Tails is great for counter forensics due to amnesia (meaning nothing is written to the disk), it is not a hardened distribution like Whonix." 
- "Tails is great for counter forensics due to amnesia (meaning nothing is written to the disk). However, it is not a hardened distribution like Whonix." 
- "Tails is great for counter forensics due to amnesia (meaning nothing is written to the disk) but it is not a hardened distribution like Whonix." 

**URL of affected page: https://www.privacyguides.org/linux-desktop/#tails**

**Comment by d4rklynk** [comment]
I think the first one would be better indeed.
