### ISSUE TITLE
Website Inaccessible Due To Expired HTTPS Certificate

### ISSUE THREAD

**Issue by Arjdroid** [privacyguides/privacyguides.org#1554]
## Description

The privacyguides.org website is currently inaccessible due to its HTTPS certificate being expired as of today, the 16th of July, 2022 and the website is configured to use HSTS so it cannot be accessed at all, even in a non-secure mode.

## Screenshots

<img width="1552" alt="Screenshot 2022-07-16 at 1 02 56 PM" src="https://user-images.githubusercontent.com/57623600/179345279-ca0d9b4f-89ec-444e-940c-2973a2656765.png">

**Comment by dngray** [comment]
Yes we're aware, https://github.com/privacyguides/privacyguides.org/discussions/1553

**Comment by Arjdroid** [comment]
Understood
