### ISSUE TITLE
Remove product logos from secondary products

### ISSUE THREAD

**Issue by ph00lt0** [privacyguides/privacyguides.org#1564]
The card around the Mollie app is missing.

![mollie](https://user-images.githubusercontent.com/15004290/179796290-adad9780-81b7-4834-8537-8da03835c148.png)

**Comment by d4rklynk** [comment]
That's completely normal.
We don't want to make a box for Molly as the main recommendation is still Signal.

**Comment by ph00lt0** [comment]
in the way it is now it looks very off, i am sorry but it's very inconsistent. Besides that worth mentioning listings were removed and everything else was upgraded to a card. Now you are reintroducing it, I don't think this is a good thing. On all other pages the less preferred tools were also cards. Think about when CalyxOS was still there.

**Comment by d4rklynk** [comment]
Yes but it still secondary. People should not chose between Signal and Molly, they should Signal, and depending of their threat model, their situation their preference they can take Molly.
In this page we recommend Signal, Element, Session and Briar. And optionally you can use Molly, we just say it exists.

**Comment by d4rklynk** [comment]
We did the same for [vaultwarden](https://www.privacyguides.org/passwords/#bitwarden) btw

**Comment by ph00lt0** [comment]
If it's not recommended, don't list it imho. I see now this change is new to me, it still looks like a mistake/broken.

**Comment by dngray** [comment]
This was an intentional design as Molly is a "sub recommendation", its not that we don't recommend it, it's that it's an optional extra.

**Comment by ph00lt0** [comment]
I understand you want to distinguish the other option, but I think the design is confusing and does not represent what you are trying to communicate.

**Comment by ph00lt0** [comment]
My suggestion would be to also make it a card, but shirk f.x. the icon and make the text color less prominent. Currently the icon is even bigger than the one of Signal itself...

**Comment by jonaharagon** [comment]
Looking at this again, I think the logo-type images should be removed from non-recommendations 👍 

The rest of the format looks good as-is without the logo, so they don't need to be converted to cards. I think we should remove the logos from Vaultwarden, Mollie, and NPxSB.
