### ISSUE TITLE
"powershell Get-Disk 0 | findstr GPT && echo This is a GPT system disk!" doesn't work on my windows 10 laptop

### ISSUE THREAD

**Issue by youdontneedtoknow22** [privacyguides/privacyguides.org#1587]
## Description

so executing "powershell Get-Disk 0 | findstr GPT && echo This is a GPT system disk!" on powershell on my laptop gives me an error, that the token "&&" isn't valid in this powershell version.

However, when executing "powershell Get-Disk 0" I get a result and I can read "GPT" under "Partition Style". 

> Number Friendly Name Serial Number                    HealthStatus         OperationalStatus      Total Size Partition Style
>                                                                                                              Style
> ------ ------------- -------------                    ------------         -----------------      ---------- ----------
> 0      WDC PC SN5... xxxxxx                                             Healthy              Online                  238.47 GB GPT

So maybe this should be the used method.

Edit:
I can't edit the title anymore, but the instructions are really unclear. For the second step:

> Check TPM version. The value returned must be "3 True". The spec must be 1.2 or above.

 What value are we talking about here? If it's all about the "SpecVersion", then we should mention that.
That's the result of the commands on my laptop:
```
PS C:\WINDOWS\system32> powershell Get-WmiObject -Namespace "root/cimv2/security/microsofttpm" -Class WIN32_tpm | findstr "IsActivated IsEnabled IsOwned SpecVersion"
IsActivated_InitialValue    : True
IsEnabled_InitialValue      : True
IsOwned_InitialValue        : True
SpecVersion                 : 2.0, 0, 1.16
```

**URL of affected page:**

https://www.privacyguides.org/encryption/#bitlocker

**Comment by dngray** [comment]
I'm wondering whether this has changed since we wrote it.

**Comment by youdontneedtoknow22** [comment]
I just tested this after updating from Win10 to Win11, I still have the same problem. However, when opening powershell it's recommending me to update to another version (I should download it from an external website, and I'm not willing to break my machine with such update tbh).

**Comment by jonaharagon** [comment]
FYI (for ourselves since the website is completely wrong lol): Both of these commands don't work because it is meant to be run in Command Prompt, not Powershell. Not sure why we say to open Powershell.

The steps should be changed to (1) running `powershell Get-Disk` and seeing if GPT is listed under "Partition Style" (as you suggested), and (2) running `powershell Get-WmiObject -Namespace "root/cimv2/security/microsofttpm" -Class WIN32_tpm` and making sure `SpecVersion` is 1.2 or 2.0. These commands would be compatible with both Command Prompt and Powershell.
