### ISSUE TITLE
Njalla is missing a proper privacy policy.

### ISSUE THREAD

**Issue by MrMuffinIsTaken** [privacyguides/privacyguides.org#160]
**Affected url/page**
URL: https://njal.la/
Page: [/providers/hosting/](https://privacyguides.org/providers/hosting/)

## Description
The service in question is called "njalla", the service in question is missing a proper privacy policy (legal doc) explaining what information the service collects, how it's used, and how it's being protected, etc. The fact that such an important document/note is missing is bad, the "1337" team ("njalla" team) has written up a **[terms of service](https://njal.la/tos/)** witch briefly explains what information they collect. The problem with the terms of service document/note is that it lacks the necessary information to call it a proper privacy policy. The fix that i propose to you guys' is one of the following three listed below.

1.  Contact the "1337" team and ask them to provide a proper privacy policy.
2.  Display a warning on the website saying they lack a proper privacy policy.
3.  Remove "njalla" from the site all together and look at a replacement.

The options i've proposed above seem like the most logical, if there is any other alternative methods someone wants to add feel free to do so.

This issue was opened by, 
Mr. Muffin,
Representative of [The New Oil](https://thenewoil.org/about.html),
**_(not opening this issue on behave of The New Oil)_**

**Full URLs:**
https://njal.la/
https://njal.la/tos/
https://thenewoil.org/about.html
https://privacyguides.org/providers/hosting/

**Comment by MrMuffinIsTaken** [comment]
Yes, i agree. I mean they sure are an interesting service that some people would maybe want to check out, but the matter of the fact is that they don't have a proper privacy policy nor do they seem to be GDPR/CCPA compliant.

**Comment by dngray** [comment]
This has been removed along with the hosting page.
