### ISSUE TITLE
Investigate hosting site on GitHub Pages

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#1605]
GitHub Pages supposedly works with any static site generator now (technically we could've before, but maybe they've made it less hacky now): https://twitter.com/github/status/1556340744989859840?s=21&t=IE5LwJlbkhqj1JRIVvFbiA

**Comment by flexagoon** [comment]
Yes, I'm using this for my site made with Hugo, and it works great. Don't know if they have a pre-made workflow for Mkdocs though

**Comment by jonaharagon** [comment]
@flexagoon very cool. We build and deploy with GitHub Actions already, just to our own server, so making this change to our workflow should be trivial, we wouldn't need a premade one. 

@privacyguides/team do we have any objections to this setup? I'll look into getting it setup tomorrow otherwise.

**Comment by dngray** [comment]
> @privacyguides/team do we have any objections to this setup? Otherwise I'll look into getting it set up tomorrow.

Not that I can see, if it works why not.

**Comment by holequantum** [comment]
i think codeberg is a good option gitlab also provide pages.
