### ISSUE TITLE
Top bar, "Discussions" link

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1622]
### Discussed in https://github.com/orgs/privacyguides/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **Beventar** August  9, 2022</sup>
I think it's better to open a new tab instead of opening the link in the current tab when clicking on "Discussions". It's a small change but I think it would be better.</div>

**Comment by jonaharagon** [comment]
Two issues with this:

1. I don't know how to do this with mkdocs
2. Why?

From an article entitled [When to use target=”_blank”](https://css-tricks.com/use-target_blank/):

> ## A Bad Reason: Because you like it that way.
> 
> Like it or not, target="_blank" is a change in default behavior. Links opening within the same page is the default behavior (as if the link had target="_self" on it).
> 
> Perhaps you’ve developed a personal taste for opening all links in new windows/tabs. That’s wonderful for you, but it is safe to assume most users are most comfortable with the default behavior. And thus less comfortable with your forcing of a different behavior.
> 
> If it’s an internal tool just for you, do whatever you want. If other people use the site, leave it be.
> 
> It is also worth noting that users can force a link to open in a new window/tab by [Meta Key]-clicking a link. That means both behaviors are available to them for links. That also means that if you like opening new tabs, you can, and you don’t have to impart that behavior on anyone else.
> 
> By using target="_blank", only that behavior is available.

Obviously this is an opinion-piece, but it's an opinion I've personally subscribed to after realizing all this does is remove a choice the user has :)

**Comment by dngray** [comment]
Fair enough.

**Comment by Dyrimon** [comment]
> Obviously this is an opinion-piece, but it's an opinion I've personally subscribed to after realizing all this does is remove a choice the user has :)

Exactly, I use temporary containers so every different domain hyperlinking from one another will open in a separate container and separate tab (except for those related domains I disabled isolation), but I don't imagine most users use their browser like this.
