### ISSUE TITLE
Remove NewPipe x SponsorBlock

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#1668]
Comment from NPxSB dev in thread:

> I now feel like if people would rather focus on privacy, the official NewPipe repo is the place to go.

Sounds good to me 👍 

### Discussed in https://github.com/privacyguides/team/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **matchboxbananasynergy** August 21, 2022</sup>
https://old.reddit.com/r/NewPipe/comments/tg2spq/an_update_about_my_fork/

We currently recommend NewPipe X Sponsorblock as an alternative to the upstream project for people who want SponsorBlock functionality (which is a nice-to-have, but admittedly a convenience thing, rather than a privacy benefit).

Based on the Reddit thread above, it seems that the app will be taking another direction, and will be introducing Google APIs in order to enable account login among other things.

I feel like it is straying away from NewPipe's privacy-centric approach, and thus I feel like it warrants de-listing it.

Thoughts?</div>

**Comment by d4rklynk** [comment]
Libretube has sponsorblock. If people want it, we can add this one

**Comment by jonaharagon** [comment]
Updated the discussion at #1594 to discuss that. Looks potentially neat, but we don't often list beta software.
