### ISSUE TITLE
Yattee (YouTube Frontend)

### ISSUE THREAD

**Issue by holequantum** [privacyguides/privacyguides.org#1675]
If this gets listed also https://github.com/privacyguides/privacyguides.org/discussions/457 should be pushed through. Basically same features for iOS and MacOS. Also uses Piped and SponsorBlock.

_Originally posted by @ph00lt0 in https://github.com/privacyguides/privacyguides.org/discussions/1594#discussioncomment-3445783_

**Comment by jonaharagon** [comment]
Duplicate of #457.
