### ISSUE TITLE
Black line on homepage when using dark mode

### ISSUE THREAD

**Issue by mfmw123** [privacyguides/privacyguides.org#1701]
On the homepage there is a blackline when using the dark mode that is non existent in the light mode.
I'm using Brave. When I was using Firefox it wasn't there.

![image](https://user-images.githubusercontent.com/51784467/187046514-3aa3b252-9064-46f3-a05d-ad1a7ebe3412.png)

**Comment by jonaharagon** [comment]
I can't reproduce this in Arc, Brave, or Firefox. Can you share your OS, screen resolution, and any extensions you have installed?

**Comment by Beventar** [comment]
I only have Bitwarden extension installed.
I'm on Windows 11, 1920x1080.

**Comment by flexagoon** [comment]
I also can't reproduce this on Linux (NixOS) Firefox+Arkenfox 1080p. Weird.

@Beventar can you try using the element picker in the dev tools and check which element the line is part of?

**Comment by jonaharagon** [comment]
Okay, I'm seeing this on my Windows 11 machine in Microsoft Edge 👍 Will look into this in a bit.

**Comment by mfwmyfacewhen** [comment]
The issue seems to be fixed now on Brave.

**Comment by mfmw123** [comment]
That's not true, it's still there.

**Comment by mfwmyfacewhen** [comment]
What OS are you on?
