### ISSUE TITLE
Passwords Knowledge Base Article

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1706]
This will replace the "Password Best Practices" section in [Password Managers](https://www.privacyguides.org/passwords/#password-best-practices), and the hope is for it go into more depth about how to choose passwords for your accounts.

If you have ideas on what should be included, or resources we can use to research for this page, please let me know here.

**Comment by razac-elda** [comment]
I saw my discussion was already linked in the pull request, I'm going to link it here as well if anyone wants to comment. #1609

**Comment by razac-elda** [comment]
I think it depends on how much we want to add to a single page. 

A single page will need to explain passwords, aliases, sso...and I'm afraid it will be too much.
Meanwhile a dedicated page for SSO won't have much informations, but could be supplemented by aliases like you said. Also it will give more flaxibility for futures updates.
