### ISSUE TITLE
DNS: Windows 11 has native support for DNS over HTTPS

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/privacyguides.org#172]
## Description

**URL of affected page:** https://privacyguides.org/providers/dns/

See also #166 and https://github.com/privacyguides/privacyguides.org/discussions/117#discussioncomment-1440335 (quick how)

**Comment by Mikaela** [comment]
Settings (Windows - I (capital i)), Web & Internet, Properties (it's top middle) DNS Settings, click customize.

![image](https://user-images.githubusercontent.com/831184/136649401-af9f8065-eaaa-4154-91d7-cc846585d598.png)

The options are:

* only unencrypted
* only encrypted (DNS & HTTPS)
* Encrypted primary, unencrypted allowed

I think this may be usual varying quality of Finnish localization of Windows. And I should really set a better set of servers and enable IPv6 DNS.

Additionally only Microsoft supported servers have DoH, so a list of those should be looked up for this issue.

**Comment by Loki-L1130** [comment]
It is also only for Ethernet as far as I know. Not available for WiFi Connections.

**Comment by Mikaela** [comment]
> It is also only for Ethernet as far as I know. Not available for WiFi Connections.

It is available for both, however all adapters need to be configured separately. My setup includes ethernet and WiFi, I am yet to try USB ones, but imagine they will work similarly

**Comment by Mikaela** [comment]
Self-assigning as an issue I care about and may be PRing by myself so it will be visible in [/issues](https://github.com/issues), please feel free to send a PR on this regardless should I not have done that at the time.

**Comment by gracjankn** [comment]
I made a pull request. #783

**Comment by dngray** [comment]
Resolved in https://github.com/privacyguides/privacyguides.org/pull/767
