### ISSUE TITLE
Standardize download sections

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#1727]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1726

<div type='discussions-op-text'>

<sup>Originally posted by **Redre1l** September  7, 2022</sup>
So, in the password managers section Bitwarden has listed browser extension stores, Android, iOS stores etc.
While 1Password is in the same section and has no listed apps.

Also I don't think it makes sense to not list downloads in the mail and VPN sections.</div>

**Comment by mfwmyfacewhen** [comment]
Also there's an appstore download and a Mac app store download in a lot of places even though either link works on both platforms.

**Comment by KaiTebay** [comment]
I'll get started on this.

For Android downloads, do we have any preference on ordering the links to .apk files, F-Droid, and the Google Play Store?

**Comment by KaiTebay** [comment]
> 

Ah, I see. Thank you for clarifying! I'll hold-off for the moment, then, and just keep tabs on the discussion.

**Comment by mfwmyfacewhen** [comment]
> Current WIP standardized download section order:
> 
> 1. Android
> 2. iOS
> 3. [Multiplatform "GitHub Releases" or similar page]
> 4. Windows
> 5. macOS
> 6. Linux
> 7. [PWAs/Extensions]
> 8. FreeBSD
> 9. OpenBSD
> 10. NetBSD

I think change iOS to just App Store

**Comment by KaiTebay** [comment]
@matchboxbananasynergy 

The order seems sensible to me. I can't think of anything missing, but I'll raise any new or unclear cases with the team (if I come across them).

**Comment by mfmw123** [comment]
> > And what about where to list the downloads?
> > List them everywhere where applicable or nitpick where to list them?
> > That was my main point of the discussion.
> 
> List them where it makes sense. As far as I know, @KaiTebay is working on this at the moment, so when that PR's ready, we can go over it and see if any adjustments need to be made.

Well does it make sense to list downloads in the email section (Tutanota, Proton etc.) or the VPN section? Right now there aren't listed downloads in those categories.
