### ISSUE TITLE
Standardize listed pricing info

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1737]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1735

<div type='discussions-op-text'>

<sup>Originally posted by **Redre1l** September  9, 2022</sup>
In the email section, providers have listed prices while other paid/free services in different sections don't have that 
(i.e. Cloud Storage, DNS Resolvers or other sections **not** in the _Providers_ section like Password Managers).

Also if a service offers a free plan alongside paid plans it doesn't make sense to only list the _Free_ label.
(i.e. Proton Mail and Tutanota in the email section)

There is some further info in the text of the card but if you're giving labels under the text of the card, make it consistent.</div>

**Comment by mfmw123** [comment]
I'd do it like this:
- list pricing info everywhere where applicable
- change the format to monthly prices
- include free and premium plans

or all prices can be removed and just redirect the user to the website for pricing info.
