### ISSUE TITLE
Knowledgebase Article on common attacks

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1739]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1720

<div type='discussions-op-text'>

<sup>Originally posted by **matchboxbananasynergy** September  4, 2022</sup>
While writing the knowledgebase article on Passwords, it struck me that while we're educating people on how to have good password hygeine (no password re-use, strong passwords/passphrases etc), we're not really teaching them about common attack vectors such as phishing.

I think it makes sense to have a page that goes over common attacks like that and how people can learn to spot them to hopefully not fall for them.</div>

**Comment by mfwmyfacewhen** [comment]
So other than phishing, I'm not sure what kind of attacks to cover here.

**Comment by jonaharagon** [comment]
credential stuffing and social engineering immediately come to mind, cookie theft is also pretty prevalent among content creators at the moment, that's how LTT was hacked.
