### ISSUE TITLE
Spelling of DNS provider Snopyta

### ISSUE THREAD

**Issue by ghost** [privacyguides/privacyguides.org#174]
## Description
DNS provider _Snoptya_'s name is supposed to be spelled _Snopyta_.
>Inverse the T and the Y
![snoptya](https://user-images.githubusercontent.com/92119119/136445605-cb910ec5-62ce-4a04-bbba-cb8150c86c90.png)

**URL of affected page:**
https://privacyguides.org/providers/dns/
**Reference:**
https://snopyta.org/
https://snopyta.org/service/dns/index.html

**Comment by Mikaela** [comment]
Thanks for noticing, I opened #175 to correct this
