### ISSUE TITLE
Add a knowledgebase article for backups

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1740]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1721

<div type='discussions-op-text'>

<sup>Originally posted by **matchboxbananasynergy** September  4, 2022</sup>
We should have a knowledgebase article that goes over how people should do proper (encrypted) backups, including talking about the [3-2-1 backup method](https://www.globaldatavault.com/blog/3-2-1-backup-rule-back-to-basics/)</div>

**Comment by d4rklynk** [comment]
Yes please, add that topic, it's a wide world

**Comment by d4rklynk** [comment]
> including talking about the [3-2-1 backup method](https://www.globaldatavault.com/blog/3-2-1-backup-rule-back-to-basics/)

I would have use this link https://www.veeam.com/blog/321-backup-rule.html

**Comment by d4rklynk** [comment]
Few things to keep in mind : 
- Cloud is not backup
- RAID is not backup
- A real backup is a backup that works when restoring

**Comment by dngray** [comment]
Maybe there's something from this thread we can use https://github.com/privacyguides/privacyguides.org/discussions/211

> Hello,
> 
> I see there is no online (offsite) backup providers on PrivacyGuides storage section.
> 
> Currently I see 2 good options to have secure encrypted offsite backups:
> 
>     1. having your own NAS (Network Attached Storage) hosted at a friend's house and you backup your encrypted files there (_got the idea from [Linus Tech Tips](https://youtu.be/mpxBmxj5mP0?t=425)_)
> 
>     2. using a service like borgbase https://github.com/borgbase
> 
> 
> > So I was thinking of adding [borgbase](borgbase.com/) and its GUI tool [Vorta](https://github.com/borgbase/vorta) to the Storage section [PR](https://github.com/privacyguides/privacyguides.org/pull/210)

**Comment by dngray** [comment]
When I was going through the discussions that we had open, I found this one https://github.com/privacyguides/privacyguides.org/discussions/739 which is somewhat relevant.
