### ISSUE TITLE
Create RSS feed for "articles" section

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#1742]
https://www.privacyguides.org/articles/ [...] We should still have an RSS feed hosted by ourselves for this section... I think that was overlooked so it might be broken. I'll open an issue to re-create our RSS feed here now so I don't forget. [...]

_Originally posted by @jonaharagon in https://github.com/privacyguides/privacyguides.org/issues/1704#issuecomment-1242388953_

**Comment by mfwmyfacewhen** [comment]
The link 404's.
