### ISSUE TITLE
GrapheneOS "Getting Started" Overview Knowledge Base article

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1751]
The idea here is to create a page that will walk people through GrapheneOS's features in a practical way to help them get up and running the way they want to. As GrapheneOS provides a lot of flexibility with things like Storage Scopes and User profiles, there are a few things to think about and consider before deciding how you want to set up your device.

The overall goal is to provide a useful resource about the OS without duplicating their existing documentation.

Ideas welcome.

Current task list:

- [ ] Talk about Auditor
- [ ] Talk about installation
- [ ] Talk about user profiles, and go through different setups with examples
- [ ] Storage Scopes showcase
- [ ] Sandboxed Google Play setup and configuration
- [ ] Banking app compatibility: https://privsec.dev/apps/banking-applications-compatibility-with-grapheneos/

**Comment by Welteam** [comment]
I believe it's important to cover the following three points (related to each other). I realize it's really an android related more than more so than grapheneOS so it may be a better fit somewhere else on the website :  
+ explain intent/ipc
+ describe the improved isolation and data protection offered by secondary users
+ highlight the shortcomings of work profile

This could then be referenced in your work to introduce higher number of users (now 32) and inter user notifications

**Comment by Welteam** [comment]
That's what I mean, I forgot about that part. The task list looks good to me then

**Comment by dngray** [comment]
A part of this guide, could point out specific privacy [features](https://grapheneos.org/features) GOS has:

I'm thinking we could cover SIM PIN codes, and some GrapheneOS specific features like media scopes, [lte only mode](https://grapheneos.org/features#lte-only-mode) etc. The page is quite long, and I think directing attention to specific areas of it could be helpful.

Another thing we could revisit is Google Phone/Google messages in https://github.com/privacyguides/privacyguides.org/pull/682, especially in light of Signal [Removing SMS support from Signal Android](https://signal.org/blog/sms-removal-android/).

There is often a barrier to get people to install something like Signal, and with modern phones often coming with [Google Messages](https://support.google.com/messages/answer/10262381) it may make more sense to use this on than an SMS/MMS application with no encryption. We wouldn't be adding it as a 'recommendation" to the instant messaging page, but *may* make some reference to the benefits on the Android specific page.

The thought behind the Google Phone/Messaging application is that
- there is spam filtering
- there is E2EE

I really want to nail home on the PG using Google Messages is a **better** alternative to installing some random SMS application "becuz Google" and sending all that data over an unsecure, unencrypted network.

**Comment by mfwmyfacewhen** [comment]
Is this necessary with the GrapheneOS documentation? Seems like they do a good job listing all the features/guides on how to install etc.

**Comment by jonaharagon** [comment]
I'm also not really interested in writing instructional guides on using GrapheneOS. I could maybe see a "feature highlights" blog post that could maybe act as a **review** of various features, but not a how-to and not KB content. That's my 2¢ anyways.
