### ISSUE TITLE
Remove repetitive statements on Frontends recommendations

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1823]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1818

<div type='discussions-op-text'>

<sup>Originally posted by **comastilt4901** September 28, 2022</sup>
Affected URL: https://www.privacyguides.org/frontends/

There are two repetitive statements on four of the frontends we use: Librarian, Nitter, Invidious, and Piped. They all have the same general acknowledgement of the dangers of self-hosting. In fact, it's just a copy-paste.

> When self-hosting, it is important that you have other people using your instance as well in order for you to blend in. You should be careful with where and how you are hosting XYZ, as other peoples' usage will be linked to your hosting.

I think it would make sense to put this inside one of those dropdowns at the very top, probably the danger one (the one with the red lightning bolt). This is how Privacy Guides does it with the "VPNs do not provide anonymity" [dropdown](https://www.privacyguides.org/vpn/). It would look like this:

![image](https://user-images.githubusercontent.com/109399351/192810428-d25c7edd-fcab-49a8-ba6f-5cd0b8fb4c2e.png)

It doesn't have to have that exact wording, but it removes a lot of repetition.

The other repetitive statement is the one on having to read up the privacy policies of each individual instance you use and not querying searches with PII (Personally Identifiable Information). I suggest we put these at the very top as dropdowns just under the danger dropdown since it's also a general statement.

Librarian has one individual statement about itself that isn't repeated, that is: "Librarian instances feature a "privacy nutrition label" to provide an overview of their policy." I think we should make this one of those colored cards. Maybe add another "Tip" card under the existing one Librarian already has?

Edit: Also, if anyone could tell me or point me to the right direction on where I can learn the terminology of these dropdowns/cards or whatever they're called, thanks.

Edit 2: I think I should have put this is Issues, but I don't want to spam. :/</div>

**Comment by comastilt4901** [comment]
Lol I should have chosen a better sentence as an example. The picture makes it seem as if there's an angry mob of people threatening you as soon as you self-host.

**Comment by KaiTebay** [comment]
> Edit: Also, if anyone could tell me or point me to the right direction on where I can learn the terminology of these dropdowns/cards or whatever they're called, thanks.
@matchboxbananasynergy 

They're called [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), from the [Material for MkDocs](https://github.com/squidfunk/mkdocs-material) theme.

**Comment by dngray** [comment]
I do agree, i think the original poster has a good point and this will help us reduce clutter.

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/194998480-0f161fb6-5dfe-4c56-a8f4-6abc7a049374.png)

Also change the last sentence in Piped Tip card. You can now use Piped with or without account. So, It's totally inappropriate or tell to use Offline accounts.
