### ISSUE TITLE
 The privacy policy of NixOS is only the privacy policy of nixos.wiki

### ISSUE THREAD

**Issue by linsui** [privacyguides/privacyguides.org#183]
## Description

**URL of affected page:**
https://privacyguides.org/operating-systems/

The privacy policy of NixOS is only the privacy policy of nixos.wiki. This makes no sense.

**Comment by dngray** [comment]
Yes, this should be removed.

Likely it was there when the whole NixOS website was just a wiki. It does seem now though they've deployed a proper website, and the wiki is just a resource.

**Comment by jonaharagon** [comment]
Does NixOS actually have a privacy policy that covers their entire project, or is this entirely inapplicable here?

**Comment by dngray** [comment]
> Does NixOS actually have a privacy policy that covers their entire project, or is this entirely inapplicable here?

I feel it was hastily added when someone added "privacy policies" for all the things.

**Comment by jonaharagon** [comment]
I'm just wondering whether it should be replaced or removed. I'm looking and can't find a replacement.
