### ISSUE TITLE
Elaborate on some of the issues with F-Droid

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1851]
## Description

**URL of affected page:** https://www.privacyguides.org/android/#verifying-apk-fingerprints

Page is good, however I would like to expand a little on this section:

> However, there are [notable problems](https://wonderfall.dev/fdroid-issues/) with the official F-Droid client, their quality control, and how they build, sign, and deliver packages.

The issue is that people may not click on that link. Now I'm aware there's a *few* issues there, but I would to see links to each heading.

Out of the 6 issues mentioned there, I think there needs to be a little more elaboration on 1-3.

**Comment by jonaharagon** [comment]
Will this be done in #2293 or are you looking for additional changes?

**Comment by dngray** [comment]
I think this one can be closed, the main two things we were interested in was [low target sdk](https://github.com/privacyguides/privacyguides.org/pull/2293#pullrequestreview-1664387790) and lack of unattended updates.
