### ISSUE TITLE
Zypak, and Brave

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1854]
## Description

**URL of affected page:** https://www.privacyguides.org/desktop-browsers/#brave

> We advise against using the Flatpak version of Brave, as it replaces Chromium's sandbox with Flatpak's, which is less effective. Additionally, the package is not maintained by Brave Software, Inc.

My understand is that it replaces Chromium's sandbox with [Zypak](https://github.com/refi64/zypak), as mentioned https://github.com/flatpak/flatpak/issues/3044#issuecomment-565265598.

This text should be corrected.

**Comment by mfwmyfacewhen** [comment]
No update since [April](https://github.com/refi64/zypak/releases), makes me a bit nervous.

**Comment by dngray** [comment]
Don't think we need to mention this, as we have a warning there about the Brave Flatpak.
