### ISSUE TITLE
Keystroke anonymization

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1857]
We could look into this as a research topic https://github.com/vmonaco/kloak

I think it's low priority for most threat models, but may be a point of interest.

**Comment by mfwmyfacewhen** [comment]
>The train kloak/test kloak scenario is more difficult to anonymize than the train normal/test kloak scenario. This is because kloak obfuscates your typing behavior, but does not make your typing behavior similar to other users. This dilemma relates to the problem of user cooperation. It's easy to make your typing behavior look like something that it's not, but what should that be? If it's too unique, then the change does more harm then good, allowing you to be easily identified. Without the cooperation of other users, it's difficult to choose a behavior that's hard to distinguish.

So it can't make users look similar to each other? That makes it not worth recommending imo. You'd have to type first without it, then use it on the same site again to make you look like a different person? Doesn't really seem that useful.

**Comment by mfwmyfacewhen** [comment]
I like the whonix wiki page on this, they recommend [typing in a text editor](https://www.whonix.org/wiki/Keystroke_Deanonymization) and copy/pasting it into the box as well as not using sites with JS enabled.

**Comment by mfwmyfacewhen** [comment]
> I think this is very extreme threat level, but wouldn't it be easier to just copy paste pre written text?

Yeah that's what I'm thinking, probably don't need to mention kloak. This might just be an aside on some other page rather than an entire page in and of itself.

**Comment by dngray** [comment]
I think this one has been decided. There isn't really a whole lot of advice we can give.
