### ISSUE TITLE
Why we don't recommend deterministic password managers

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1859]
## Description

**URL of affected page:** https://github.com/privacyguides/privacyguides.org/pull/323

It came up in this thread, but I think it's important enough to have a section in the passwords guide.

**Comment by jermanuts** [comment]
https://palant.info/categories/password-managers/ might be helpful in the password overview (Introduction to passwords) knowledge base page .

**Comment by kimg45** [comment]
Is this really needed? I don’t think most people have even heard of a deterministic password manager and I think explaining everything that’s not recommended isn’t necessary.

**Comment by dngray** [comment]
They're pretty uncommon, and we don't recommend any on the site. People aren't asking about these so we could just avoid it I think.
