### ISSUE TITLE
Integrated password manager warnings

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1860]
## Description

We should mention perhaps that Google's password management has "opt-in E2EE", and that Microsoft's password sync service does not apply E2EE.

**Comment by mfwmyfacewhen** [comment]
Do you have a source that the Google password manager is opt-in e2ee? [Their documentation](https://support.google.com/chrome/answer/10311524?hl=en#zippy=%2Chow-password-protection-works%2Chow-we-protect-your-data%2Cyoure-in-control) implies it's e2ee by default.
