### ISSUE TITLE
Investigate router platforms

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1864]
## Description

**URL of affected page:** https://discuss.privacyguides.org/t/securing-home-network/319

Many people are looking for replacements to their "home router" as a border device is unsupported by the vendor. Typically consumer grade hardware is only supported for a very short time rather like like cheap mobile phones.

The issue is these devices provide important security controls for local area networks of households. Such use cases have limited budgets that makes enterprise grade hardware unobtainable.

We would have a criteria, and the main thing being that the platform is open enough that it can support new kernels. The [Turris Omnia](https://www.turris.com) based on OpenWRT seems like a fine candidate. Other candidates include [GL.iNet](https://www.gl-inet.com) and [Firewalla](https://firewalla.com), [Protectli](https://protectli.com/) and more advanced options like the [OPNsense offerings](https://shop.opnsense.com/product-categorie/hardware-appliances/).

**Comment by dngray** [comment]
> The German Fritz!box can also be included.
> Another option is Netgear routers with pfsense, or ubiquity hardware.

We would not be including any of these as they're not strictly supported with third party firmware and in a lot of models it is impossible.

**Comment by jonaharagon** [comment]
[MikroTik](https://mikrotik.com/) is probably also worth looking into, I've seen people switch to them after Ubiquiti started withering away. Might not be as consumer-friendly though.

**Comment by dngray** [comment]
> [MikroTik](https://mikrotik.com/) is probably also worth looking into,

[Not at](https://news.ycombinator.com/item?id=24240961) [this time](https://www.bleepingcomputer.com/news/security/hundreds-of-thousands-of-mikrotik-devices-still-vulnerable-to-botnets/).

> I've seen people switch to them after Ubiquiti started withering away.

I'd be surprised about that.

**Comment by maltfield** [comment]
It might also be worthwhile spending 1-4 paragraphs discussing and linking-to some guides on how to setup a "whole house VPN" with your router. Such a setup can pass all traffic for an entire wireless network through a VPN -- especially useful for devices that can't run a VPN or can easily/accidentally have VPN leaks.

I wrote a guide on how to do this with Ubiquiti hardware, but I've seen similar guides for tomato and DD-WRT

 * https://tech.michaelaltfield.net/2017/08/20/howto-guide-whole-house-vpn-with-ubiquiti-cryptostorm-netflix-safe/

**Comment by dngray** [comment]
@maltfield I actually plan to do one of those with https://github.com/privacyguides/privacyguides.org/issues/1863, I only have the OPNsense appliance at this point. I think Jonah has the Firewalla.
