### ISSUE TITLE
VPN Providers Incorrectly Mention F-Droid

### ISSUE THREAD

**Issue by KaiTebay** [privacyguides/privacyguides.org#1874]
## Description

The "Mobile Clients" admonitions for IVPN, Proton VPN, and Mullvad VPN mention their availability on F-Droid:

> The mobile client on Android is also available in [F-Droid](https://f-droid.org/packages/net.mullvad.mullvadvpn), which ensures that it is compiled with [reproducible builds](https://www.f-droid.org/en/2019/05/05/trust-privacy-and-free-software.html).

Since we no longer recommend F-Droid as an Android app source, we should remove these.

**URL of affected page: https://www.privacyguides.org/vpn**

**Comment by flexagoon** [comment]
IVPN F-Droid version has a built-in ad blocker, while the Google Play one doesn't.
