### ISSUE TITLE
Mention FLOC under Chrome anti recommendation

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#19]
- https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea
- https://www.eff.org/deeplinks/2021/04/am-i-floced-launch
- https://amifloced.org/
- https://www.eff.org/deeplinks/2021/04/after-cookies-ad-tech-wants-use-your-email-track-you-everywhere

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> 
>     * https://amifloced.org/

![floced](https://amifloced.org/images/floc-4b.gif)
