### ISSUE TITLE
ProtonMail: Suggest Telemetrie opt-out?

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1932]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1749

<div type='discussions-op-text'>

<sup>Originally posted by **rusty-snake** September 11, 2022</sup>
ProtonMail has two telemetrie switches under Settings > Account > Security and Privacy > Privacy and Data-collection [at the bottom] (free translation):
- collect usage diagnostics data 
- send crash reports

Should we suggest to opt-out from them?

Does anyone know since when they are there? I could swear that they were not there half a year ago and I did not saw an information about adding them.</div>

**Comment by razac-elda** [comment]
I only see crash reports, maybe the diagnostics are not enabled for all jurisdictions.

**Comment by dngray** [comment]
> I only see crash reports, maybe the diagnostics are not enabled for all jurisdictions.

I checked with a client's account, same thing.
