### ISSUE TITLE
Remove the DNSCrypt support for Controld

### ISSUE THREAD

**Issue by marshallishere** [privacyguides/privacyguides.org#1942]
## Description

I went into the Controld website and there's no dnscrypt configuration. I also looked into the [dnscrypt-proxy public resolve list](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md) and there's no dnscrypt server, only doh. I don't think they support it at all.

**URL of affected page:** https://www.privacyguides.org/dns/

**Comment by dngray** [comment]
Looking at their website, seems like they only do DoH/DoT,DoQ
