### ISSUE TITLE
Brave Translate

### ISSUE THREAD

**Issue by idk-r-n** [privacyguides/privacyguides.org#1953]
## Description
It may be worth mentioning the setting to disable Brave translate [https://support.brave.com/hc/en-us/articles/8963107404813](https://support.brave.com/hc/en-us/articles/8963107404813). I don't know when this feature was added. The toggle is under Settings > Languages

**URL of affected page:**
[https://www.privacyguides.org/desktop-browsers/#brave](https://www.privacyguides.org/desktop-browsers/#brave)

**Comment by mfwmyfacewhen** [comment]
Yeah seems like something you would have to go out of your way to use, and even then they do a pretty good job of keeping it private.
