### ISSUE TITLE
IOT Blog article

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1989]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/1716

<div type='discussions-op-text'>

<sup>Originally posted by **mfwmyfacewhen** September  2, 2022</sup>
I think a page explaining how awful IOT is for privacy/security would be good to have. Would like some ideas for what to put in it.</div>

I'm thinking we could do something with this, perhaps in the form of a blog post.

Unfortunately many IoT devices are designed with very limited upstream support. They often depend on specific [BSPs (board support packages)](https://en.wikipedia.org/wiki/Board_support_package) from vendors which only work with particular Linux kernels. That's how you get devices which are forever stuck on an old kernel.

I think we could make some general recommendations here such as:

- Be wary of devices that don't discuss a support cycle or have open source drivers
- Discuss using VLANs to separate unsupported IoT devices
  - Which could be a precursor to https://github.com/privacyguides/privacyguides.org/issues/1863

**Comment by mfwmyfacewhen** [comment]
I'm thinking this could be part of the smart home pr. Maybe even something about how to know if you're buying an IOT device, I know people that are just trying to buy a thermostat or a garage door opener and they end up buying some awful IOT thing on accident.
