### ISSUE TITLE
SOCKS/Censorship comparison on VPNs

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1991]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/638

<div type='discussions-op-text'>

<sup>Originally posted by **ph00lt0** February 21, 2022</sup>
Mullvad allows quite a lot of features to use SOCKS v5.

I think it would be good to add some explanation of this on the website as it can have quite some benefits the the user. They also have an extension in beta for Firefox to allow you to toggle this on and off. 

https://mullvad.net/en/blog/2021/9/30/test-our-new-browser-privacy-tool-mullvad-privacy-companion-beta/

Generally adding the proxy settings can be very beneficial. I also have seen that @nitrohorse once made an extension for this themselves. 

According to mullvad it slows down the amount of captcha's you may experience and also can be good as your ingoing and outgoing IP will be different.

The same goes for the shadowsocks features that mullvad offers and are described here: 
https://mullvad.net/en/help/intro-shadowsocks/
</div>

**Comment by jermanuts** [comment]
https://windscribe.net/knowledge-base/articles/what-protocols-are-available-with-windscribe (Stealth and Wstunnel) but windscribe is not added to the website [yet.](https://github.com/privacyguides/privacyguides.org/pull/1312)

https://deploy-preview-56--privsec-dev.netlify.app/knowledge/commercial-vpn-use-cases/#circumventing-censorship

It's also worth noting that something like Stealth protocol that protonvpn uses won't work in Russia, Iran and china. According to few reports like https://old.reddit.com/r/ProtonVPN/comments/11wbkpu /proton_vpn_completely_inaccessible_in_russia/ At least, not reliably. You will always find someone claiming that it works for them, while that's true perhaps when DPI is overloaded at certain times, so you might connect to a VPN server? Depending on the type DPI of course.

https://github.com/net4people/bbs/issues will have the most accurate tests, also [lol](https://github.com/net4people/bbs/issues/239)

**Comment by PoneyClairDeLune** [comment]
> https://windscribe.net/knowledge-base/articles/what-protocols-are-available-with-windscribe (Stealth and Wstunnel) but windscribe is not added to the website [yet.](https://github.com/privacyguides/privacyguides.org/pull/1312)
> 
> https://deploy-preview-56--privsec-dev.netlify.app/knowledge/commercial-vpn-use-cases/#circumventing-censorship
> 
> It's also worth noting that something like Stealth protocol that protonvpn uses won't work in Russia, Iran and china. According to few reports like https://old.reddit.com/r/ProtonVPN/comments/11wbkpu/proton_vpn_completely_inaccessible_in_russia/ At least, not reliably. You will always find someone claiming that it works for them, while that's true perhaps when DPI is overloaded at certain times, so you might connect to a VPN server? Depending on the type DPI of course.
> 
> https://github.com/net4people/bbs/issues will have the most accurate tests, also [lol](https://github.com/net4people/bbs/issues/239)

https://twitter.com/unHybrideEnExil/status/1580507140220862465

**Comment by jermanuts** [comment]
I have written https://jermanuts.vercel.app/posts/proxies/

Also IVPN added V2Ray support recently. So the only two VPN providers that are recommended by PG that support FEPs are Mullvad and IVPN.

**Comment by dngray** [comment]
Yes, IVPN does support this:

ivpn connect command has argument -v2ray:

```
$ ivpn connect -h
Command usage:
-v2ray TYPE - Use V2Ray obfuscation (this option takes precedence over the '-obfsproxy' option)
Acceptable values: 'quic' (VMESS/QUIC) or 'tcp' (VMESS/TCP)

Example:
$ ivpn connect -v2ray quic -protocol wireguard -city Amsterdam
```

**Comment by dngray** [comment]
Seems that this feature for Windscribe has been released in their clients now https://blog.windscribe.com/introducing-circumvent-censorship/
