### ISSUE TITLE
Recommended software Exifcleaner is no longer maintained

### ISSUE THREAD

**Issue by Anish-M-code** [privacyguides/privacyguides.org#1998]
Reference: https://github.com/szTheory/exifcleaner/issues/218

Exifcleaner is recommended here: https://www.privacyguides.org/data-redaction/

Exifcleaner is no longer maintained since march 2022 , it might be heavily behind security updates and hence bad for privacy.

**Comment by jonaharagon** [comment]
Thanks for the heads up! We record all of our recommendation change discussions on Discourse, hence the closing of this issue :)
