### ISSUE TITLE
Link to projects' defined privacy policies

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#2]
`privacy_policy` links should probably be included in [`recommendation-card.html`](https://github.com/privacyguides/privacyguides.org/blob/main/_includes/recommendation-card.html) as well.

**Comment by dngray** [comment]
Completed in https://github.com/privacyguides/privacyguides.org/commit/7ed3f636a37e24a441980ba5873a1003908baf86
