### ISSUE TITLE
Automatic link checking

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#2003]
## Description

We should automatically check for dead links. I've used a site like https://www.deadlinkchecker.com in the past but that hits the 2000/2000 limit. I was able to get a list of links with:

```
grep -Eorh '(http|https)://[a-zA-Z0-9./?=_-]*' . | sort -u
```

**Comment by jonaharagon** [comment]
We did this at one point but the GitHub Actions VMs are commonly rate limited.

**Comment by mfwmyfacewhen** [comment]
A manual check once in a while should be fine. No need to add more complexity.
