### ISSUE TITLE
Keyoxide PGP

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#2010]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/326

<div type='discussions-op-text'>

<sup>Originally posted by **ignoramous** November 16, 2021</sup>
> Keyoxide allows you to prove "ownership" of accounts on websites, domain names, IM, etc., regardless of your username.

> That last part is important: You could, for example, be `alice` on Lobste.rs, but `@alice24` on Twitter. And if your website is `thatcoder.tld`, how are people supposed to know that all that online property is yours?

> The Keyoxide project is licensed under AGPL-3.0-or-later.

https://docs.keyoxide.org/getting-started/what-is-keyoxide/</div>

**Comment by dngray** [comment]
I'm thinking this could be an interesting addition with https://github.com/privacyguides/privacyguides.org/issues/1686.

I think this does somewhat relate to privacy, particularly when using self hosted services, you'd need some sort of method to tie those credentials together. In the past we used Keybase, however the future of that is unlikely.

Most people opt to simply list credentials on their blog or website, but that doesn't have any cryptographic check.

**Comment by rnaprinciple** [comment]
I believe this is related to privacy, especially when utilizing self-hosted services, as you'd need some way to connect those credentials. We used to utilize Keybase, but that is unlikely to continue. [Roblox Doors](https://robloxdoors.com/)

**Comment by jonaharagon** [comment]
> Most people opt to simply list credentials on their blog or website, but that doesn't have any cryptographic check.

To be honest, I'm not sure what value a cryptographic signature provides in this particular case.

**Comment by dngray** [comment]
Thread moved to https://discuss.privacyguides.net/t/keyoxide-keybase-alternative/9564/9
