### ISSUE TITLE
Add Criteria for Paste Services

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#2015]
## Description

Currently, it seems that Paste Services is the only section (or sub-section, rather) that doesn't have specific criteria associated with it.

It would seem reasonable to expect a paste service to provide client side encryption, for example.

**URL of affected page:**
https://www.privacyguides.org/productivity/#paste-services

**Comment by dngray** [comment]
This is true, and I'm thinking at the moment being open source is really the only thing we can suggest as none of these are audited. I would like to (or have someone) tell me what they think of https://discuss.privacyguides.net/t/paaster-end-to-end-encrypted-pastebin/11757

**Comment by WardPearce** [comment]
Hey creator of Paaster here, password protection is a feature we are planning.

**Comment by WardPearce** [comment]
> > Hey creator of Paaster here, password protection is a feature we are planning.
> > If anyone has any questions or concerns around paaster let me know.
> 
> Hi, cool of you to chime in!
> 
> I hope I'm not putting you in a tough spot, but if you had to give the pros/cons of Paaster compared to something like PrivateBin, what would you say those are?

Sure, obviously these will be somewhat subjective.

**Shared**
- [Secret transportation](https://github.com/WardPearce/paaster#how-are-client-secrets-transported).
- Delete after view.
- Delete after X amount of time.
- Syntax highlighting.
- Deploying via docker.
- CLI Tool. 

**Pros** 
- Modern encryption algorithm (XChaCha20-Poly1305 using libsodium a audited & battle tested lib).
- Paste history.
- PWA support.
- Modern Javascript, written with Typescript using Svelte. PrivateBin can be a bit of a mess.
- Frontend & backend code separation (Paaster's frontend can easily be ran on a separate server then the backend).
- Arguably a more straightforward interface.
- Doesn't expose the format of the paste unlike PrivateBin.
- Discussions in PrivateBin aren't encrypted (not a feature of Paaster, but personally think its better not included then included but insecure.)
- Vercel support.

**Cons**
- Currently no i18n support.
- PrivateBin is more battle tested.
- PrivateBin supports file uploads.
- PrivateBin supports theming.
- PrivateBin has more extensive documentation.
- Less hosted instances then PrivateBin.
- Use of IndexedDB, as mentioned [here](https://github.com/WardPearce/paaster#how-are-client-secrets-stored).
- No additional password protect.


I do think PrivateBin is a great project & Paaster does share a lot of similarities with it. But personally I think Paaster has a radically different design, with more of a focus on simplicity & speed of use.

**Comment by jonaharagon** [comment]
Locking this because I can't keep track of two Paaster discussions at once, but in response to the OP - yes, we need to add criteria to that section 👍
