### ISSUE TITLE
Overhaul Firefox Extension Section

### ISSUE THREAD

**Issue by theuser18** [privacyguides/privacyguides.org#202]
Shouldn't Decentraleyes be replaced by [LocalCDN](https://www.localcdn.org/) and [HTTPS Everywhere should be removed](https://www.eff.org/deeplinks/2021/09/https-actually-everywhere)?

I would also recommend the following extensions:

1. [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) (and Multiaccount Containers)
2. [Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/)

**Comment by rusty-snake** [comment]
> Decentraleyes be replaced by LocalCDN

yes

> HTTPS Everywhere [and ClearUrls] should be removed?

#155 and yes

> Temporary Containers (and Multiaccount Containers)

They are already listed.

> Privacy Redirect

yes

**Comment by pm4rcin** [comment]
@rusty-snake shouldn't clearurls stay here since it can stop redirects unlike AdGuard filters? (I read that on reddit so correct me if I'm wrong)

**Comment by rusty-snake** [comment]
@pm4rcin Yes CU can skip redirection and yes uB can not do this. However I wouldn't use CU if you use only one feature. Just use Skip Redirect and/or Request Control. See also https://github.com/arkenfox/user.js/issues/1263#issuecomment-942495653 and the following.
