### ISSUE TITLE
MermaidJS graph not showing

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#2042]
For some reason the [Mermaid.js graph isn't showing](https://squidfunk.github.io/mkdocs-material/reference/diagrams/) on this page https://www.privacyguides.org/advanced/dns-overview/?h=dns#should-i-use-encrypted-dns

I wonder if it has something to do with the privacy plugin https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin

**Comment by jonaharagon** [comment]
Spent a lot of time troubleshooting and narrowed it down to an issue with `mkdocs-static-i18n` unfortunately, not sure how to fix: https://github.com/ultrabug/mkdocs-static-i18n/issues/196
