### ISSUE TITLE
Missing information about Oblivious DNS over HTTPS (ODoH)

### ISSUE THREAD

**Issue by quackerex** [privacyguides/privacyguides.org#2122]
### Affected page

https://www.privacyguides.org/en/advanced/dns-overview/

### Description

The page is missing information about the ODoH protocol. Can the website be updated to include an explanation of what ODoH is, how it works, and its benefits?

### Sources

- https://blog.cloudflare.com/oblivious-dns/
- https://www.eff.org/deeplinks/2020/12/dns-doh-and-odoh-oh-my-year-review-2020

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
Thanks for the suggestion! This issue tracker is only for tracking website bugs and incorrect information. We track new topic suggestions on our forum at https://discuss.privacyguides.net.
