### ISSUE TITLE
Proton mail tiers/features out of date 

### ISSUE THREAD

**Issue by joeySeal** [privacyguides/privacyguides.org#2156]
### Affected page

https://www.privacyguides.org/en/email/#proton-mail

### Description

I could not find any mention of a free simplelogin account on their site "If you have the Proton Unlimited, Business, or Visionary Plan, you also get [SimpleLogin](https://www.privacyguides.org/en/email/#simplelogin) Premium for free."

Also the tier names have changed, currently they offer free, unlimited for individuals. Mail essentials, business, and enterprise for businesses.

### Sources

https://proton.me/pricing
https://proton.me/business/plans

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
Their plan names haven't changed from what we have on the site... The Visionary plan still exists, I have one myself.

The plans stated definitely include SimpleLogin subscriptions, so there is no error.
