### ISSUE TITLE
Tressorit is not a Hungarian company

### ISSUE THREAD

**Issue by ph00lt0** [privacyguides/privacyguides.org#2157]
### Affected page

https://www.privacyguides.org/en/cloud/#tresorit

### Description

Tressorit is maybe founded in Hungary but it is a Swiss company unlike what is written on the website. This is very relevant due to different laws. I didn't check who wrote this on the website but it's not researched well. 

From the privacy policy:
"Tresorit services are provided by Tresorit AG (company registration no: CH-300.3.017.920-5; address: Franklinstrasse 27, 8050 Zurich)"

### Sources

https://tresorit.com/legal/privacy-policy

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
Tresorit AG is a subsidiary of Tresorit Kft., whose address (in that same document) is listed as:

Tresorit Kft.
Köztelek utca 6.
1092 Budapest, Hungary

I think updating the description to "Swiss-Hungarian" would be the most accurate. They use both "Swiss-Hungarian" and "Swiss" on their website to describe themselves.
