### ISSUE TITLE
Clarification on WKD

### ISSUE THREAD

**Issue by ruhrscholz** [privacyguides/privacyguides.org#2161]
### Affected page

https://www.privacyguides.org/en/email/

### Description

While working on the translations, I noticed there is some (in my opinion) crucial piece of information missing regarding WKD: PrivacyTools advertises it for ProtonMail/Mailbox.org, but fails to mention that this feature only works on the respective default domains of the providers. This has two important consequences:
1. WKD does not (easily) work when using your own domain with any provider
2. The other email providers support E2EE just as well as ProtonMail/Mailbox.org when you use your own domain and configure WKD

Either way, if this WKD-suggestion is purely related to *sending* emails, then this should probably be highlighted as well.

### Sources

1. The WKD [documentation](https://wiki.gnupg.org/WKD) states that the lookup happens via the email's domain part. This can and will resolve to different servers depending on MX and A/AAAA record. The common usage scenario for an own email domain with one of the public providers makes those two records have different values and thus, servers.
2. I tested my own Proton addresses with https://metacode.biz/openpgp/web-key-directory

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
Yes, it's mostly related to *sending* like you said, but we should mention this limitation for custom domains. Setting up WKD on a custom domain is pretty trivial, but it does typically require more setup than the email provider will tell you. 

We should recommend that custom domain users set up https://keys.openpgp.org/about/usage#wkd-as-a-service I think, @privacyguides/team?

**Comment by ruhrscholz** [comment]
Since this is only related to sending email, would all providers that offer the ability to use IMAP/SMTP with Thunderbird (or other clients with WKD support) be considered the same apart from their web client features?

**Comment by jonaharagon** [comment]
Well it is still an advantage that e.g. Proton users get WKD set up for their own mailboxes by default. If you're going to handle WKD entirely yourself then no it doesn't make a difference.
