### ISSUE TITLE
Brave Web3 settings are incorrect

### ISSUE THREAD

**Issue by noClaps** [privacyguides/privacyguides.org#2163]
### Affected page

https://www.privacyguides.org/en/desktop-browsers/#web3

### Description

There is no **None** option for **Default Ethereum wallet** and **Default Solana wallet**. The only options are **Extensions (Brave Wallet fallback)**, **Brave Wallet**, and **Extensions (no fallback)**. There is also a **Crypto Wallets (deprecated)** for Ethereum. This is on Brave v1.51.118, Windows 11.

### Sources

<img width="512" alt="image" src="https://github.com/privacyguides/privacyguides.org/assets/103803129/3bfc160d-9953-431d-bdeb-696fe9864d14">
<img width="511" alt="image" src="https://github.com/privacyguides/privacyguides.org/assets/103803129/6410c2e2-24d3-4ed2-b753-981d6dc778ea">

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by mfwmyfacewhen** [comment]
Might just remove this part then.
