### ISSUE TITLE
Librarian's instances and documentation links is invalid

### ISSUE THREAD

**Issue by zolagonano** [privacyguides/privacyguides.org#2168]
### Affected page

https://www.privacyguides.org/en/frontends/#librarian

### Description

Links provided for librarian aren't valid anymore

### Sources

Documents: https://librarian.codeberg.page/docs/
Instances: https://librarian.codeberg.page/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by mfwmyfacewhen** [comment]
Librarian will be removed in the next release.
