### ISSUE TITLE
Shelter link broken

### ISSUE THREAD

**Issue by ph00lt0** [privacyguides/privacyguides.org#2189]
### Bug description

https://www.privacyguides.org/en/os/android-overview/#recommended-apps
contains a link to shelter however this seems broken.

### Affected pages

https://www.privacyguides.org/en/os/android-overview/#recommended-apps

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by blacklight447** [comment]
Good catch! Im working on a fix here https://github.com/privacyguides/privacyguides.org/pull/2190
