### ISSUE TITLE
Broken link to translation service

### ISSUE THREAD

**Issue by ph00lt0** [privacyguides/privacyguides.org#2197]
### Bug description

Link (icon) at bottom of website is linking to matrix not to the translation thingy.

I found some quite bad sentences in the dutch translation so if you can tell me where to report this?

### Affected pages

https://www.privacyguides.org/en/#we-need-you-heres-how-to-get-involved

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by dngray** [comment]
> I found some quite bad sentences in the dutch translation so if you can tell me where to report this?

best place for that would be on Crowdin ie https://crowdin.com/project/privacyguides/nl
