### ISSUE TITLE
Entire list item on tools.md should be clickable, not just the title

### ISSUE THREAD

**Issue by tedgravlin** [privacyguides/privacyguides.org#2202]
### Bug description

![image](https://github.com/privacyguides/privacyguides.org/assets/123981212/b43e3f57-c3a7-4788-880b-cd800f253251)

Current behavior:
You can only click on the title of a tool to open its page. 

Expected behavior:
You should be able to click anywhere within the border to open the page.

### Affected pages

- tools.md

### Browser

Firefox

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by noClaps** [comment]
https://inclusive-components.design/cards/#thepseudocontenttrick

This might be worth looking at.
