### ISSUE TITLE
Update the Qubes OS "qube" terminology

### ISSUE THREAD

**Issue by nopeitsnothing** [privacyguides/privacyguides.org#2210]
### Affected pages

- [Qubes OS Overview](https://www.privacyguides.org/en/os/qubes-overview/)
- [Desktop/PC section](https://www.privacyguides.org/en/desktop/#qubes-os)

### Description

[This image](https://raw.githubusercontent.com/privacyguides/privacyguides.org/main/docs/assets/img/qubes/qubes-trust-level-architecture.png), and also the language used in several areas, is outdated. It uses the old naming convention of "AppVM" instead of "qube". The Qubes OS maintainers are gradually updating the terms, and most pages include the new language.

### Changes to be made

- "AppVM" -> ["app qube"](https://www.qubes-os.org/doc/glossary/#app-qube)
- "TemplateBasedVM", TemplateVM", "Template VM" -> now just ["template"](https://www.qubes-os.org/doc/glossary/#template) to avoid confusing them for actual qubes
- "DisposableVM", "DispVM" -> ["disposable qube"](https://www.qubes-os.org/doc/glossary/#disposable)
- "DVM Template", "DVM" -> now just ["disposable template"](https://www.qubes-os.org/doc/glossary/#disposable-template)
- "StandaloneVM" -> now just ["standalone"](https://www.qubes-os.org/doc/glossary/#standalone) types of qubes which do not supply their root filesystems to other qubes (i.e., not a full VM)
- "VM" -> "[domain](https://www.qubes-os.org/doc/glossary/#domain)" (synonymous terms)

### Distinctions

* They are never *Qubes*. 
* Sometimes the term [VM](https://www.qubes-os.org/doc/glossary/#vm) is used as a synonym for domU. This is technically inaccurate, as [dom0](https://www.qubes-os.org/doc/glossary/#dom0) is also a VM in Xen. 
- The term “domU” is a common noun and should follow the capitalization rules of common nouns.

### Sources

https://www.qubes-os.org/intro/ - this page still shows them as "AppVM" and "AdminVM". But this is outdated as well. The correct term is colloquially known as *qube* now. Their own documentation is behind what is on their forums as "qube" and "qube-vm".

https://www.qubes-os.org/doc/glossary/ - this page shows the change that isn't globally adopted yet. It should be considered to rename these things to be more in line with the documentation here.

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
> Plans to roll out this change are set to take place with the next release.

I'm tempted to not make any changes until this is actually released. This image is also—as you linked—directly pulled from their documentation, where it hasn't been changed, and I don't think we need to create our own version just for this change. If they update this image in their documentation, we can change it here.

**Comment by nopeitsnothing** [comment]
I hadn't even considered the image when I added it in #1568 so that's kinda my bad. But sure, I'm monitoring the docs for the change as well.

**Comment by nopeitsnothing** [comment]
The documentation is now updated to include the new naming scheme.
