### ISSUE TITLE
IVPN is phasing out port forwarding, update your page accordingly

### ISSUE THREAD

**Issue by slrslr** [privacyguides/privacyguides.org#2216]
### Bug description

https://www.privacyguides.org/en/vpn/?h=vpn#remote-port-forwarding mentions port forwarding next to IVPN, but this will no longer be offered by IVPN per https://www.ivpn.net/blog/gradual-removal-of-port-forwarding
So you should not advertise it, no longer available for new clients and will be disabled for existing ones.

### Affected pages

-

### Browser

Other

### Operating System

Other

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by dngray** [comment]
Yes, the change literally was announced today and a PR already exists to be signed off.

**Comment by blacklight447** [comment]
Yeah, the attitude here is a bit over the top. Apart from that, we do not " advertise" , we give recommendations.
