### ISSUE TITLE
MacOS Sonoma Drops Support for Mail.app Plug-ins

### ISSUE THREAD

**Issue by dorkbuttt** [privacyguides/privacyguides.org#2222]
### Affected page

https://www.privacyguides.org/en/email-clients/#apple-mail-macos

### Description

As MacOS Sonoma 14 is still in beta, I thought it would be prudent to mention it here instead of a separate issue. Apple is dropping support for its legacy plug-ins in Mail.app, disabling GPGTools from being enabled and thus able to decrypt messages. So the entry of it in Email Clients is on a course of being out of date. My first instinct is to retreat to Thunderbird for MacOS, unless word can be ascertained by the developers that they are going to be moving forward and adapting to this change somehow.

### Sources

https://www.macrumors.com/2023/06/14/macos-sonoma-drops-legacy-mail-app-plug-ins/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
I see no reason GPG Tools couldn’t be adapted to use MailKit, seeing as extension-based message encryption and signing is a specifically supported feature of MailKit, so unless you have a source where they say they won’t be developing a version for Sonoma, this doesn’t change our recommendations.

New macOS versions often break GPG Tools, and GPG Tools historically has released timely updates for every new macOS version.
