### ISSUE TITLE
Outdated Information

### ISSUE THREAD

**Issue by ridou-dev** [privacyguides/privacyguides.org#2238]
### Affected page

https://www.privacyguides.org/en/vpn/#ivpn

### Description

"Remote Port Forwarding" is checked for IVPN, but it's no longer available for new customers. And it will no longer be available on September 30, 2023 for former customers who have a pro subscription

### Sources

Here is the source : https://www.ivpn.net/blog/gradual-removal-of-port-forwarding

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by mfwmyfacewhen** [comment]
It's already changed we just haven't pushed the new release yet, good eye though.
