### ISSUE TITLE
Dark image not working (NL/DNS/rethink)

### ISSUE THREAD

**Issue by Kapot** [privacyguides/privacyguides.org#2258]
### Affected page

https://www.privacyguides.org/nl/dns/#versleutelde-dns-proxy

### Description

![rethinkdns](https://github.com/privacyguides/privacyguides.org/assets/6935358/afce49ad-1c01-42ed-870c-62da3ea658b3)

Think theres a fault in line 72 somewhere, but cant find it. Unable to open the rethink dark image on https://www.privacyguides.org/nl/assets/img/android/rethinkdns-dark.svg#only-dark, so the error might be there?

### Sources

No source

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by dngray** [comment]
I've fixed this it, was a missing `[` on Crowdin. The update should occur when the next pull from Crowdin occurs.
