### ISSUE TITLE
AnonAddy is now addy.io

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#2262]
### Affected page

https://www.privacyguides.org/en/email/

### Description

Rebranded

### Sources

https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
A new feature also listed in that announcement post is the ability to disable certain usernames on your account from logging into the addy.io control panel. That being the case, it might make sense for us to recommend having a username that you don't use in your email aliases (only for logging in) and restricting logins to that username only, to prevent would-be attackers from knowing login credentials based on your public aliases.

**Comment by freddy-m** [comment]
Resolved in  #2263
