### ISSUE TITLE
Number of free aliases with AnnonAddy's free plan

### ISSUE THREAD

**Issue by ghost** [privacyguides/privacyguides.org#2264]
### Affected page

https://www.privacyguides.org/en/email/#email-aliasing-services

### Description

There is 10 free shared aliases, not 20.

### Sources

https://addy.io/#pricing

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by freddy-m** [comment]
Resolved in #2263
