### ISSUE TITLE
Tutanota aliases increased

### ISSUE THREAD

**Issue by uhrfru** [privacyguides/privacyguides.org#2284]
### Affected page

https://www.privacyguides.org/en/email/#tutanota

### Description

Tutanota has updated their plans and available functions of those.
Paid accounts now have unlimited custom domain aliases, as well as 15 and 30 normal aliases respectively for the 3€ and 8€ price plans. The PG page states you get 5 aliases.

Also potentially worth adding to the page is that they now also support family accounts/shared mailboxes now. But since it is not mentioned for the other email providers, this seems superfluous unless it is added for all (which I think is worth considering).

### Sources

https://tutanota.com/blog/summer-releases-2023

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by freddy-m** [comment]
Good spot!
