### ISSUE TITLE
 QNAME minimization

### ISSUE THREAD

**Issue by publicarray** [privacyguides/privacyguides.org#2285]
### Affected page

https://www.privacyguides.org/en/advanced/dns-overview/#what-is-qname-minimization

### Description

https://github.com/privacyguides/privacyguides.org/blob/a85690b30620fc59abbfa4b4ffeae1679d2432c2/docs/advanced/dns-overview.md?plain=1#L299C107-L299C137

> Instead of sending the whole domain privacyguides.org, QNAME minimization means the DNS server will ask for all the records that end in .org. Further technical description is defined in [RFC 7816](https://datatracker.ietf.org/doc/html/rfc7816).

The existing text is trying to simplify too much and created an inaccuracy as a result. "DNS server will ask for all the records that end in .org." doesn't make sense, maybe the following works better:

Instead of sending the whole domain to every upstream authoritative server, QNAME minimization means the DNS resolver will only ask for the information it needs to resolve the next query. e.g. It will ask the root for .org and not the fully qualified domain name (FQDN) privacyguides.org. Further technical description is defined in [RFC 7816](https://datatracker.ietf.org/doc/html/rfc7816).

### Sources

Without QNAME minimization the full domain is send to every upstream server:  https://dnscrypt.info/_nuxt/img/DNS.18fe1f1.png

---
https://www.rfc-editor.org/rfc/rfc7816#section-2

>  For example, a resolver receives a request to resolve
   foo.bar.baz.example.  Let's assume that it already knows that
   ns1.nic.example is authoritative for .example and the resolver does
   not know a more specific authoritative name server.  It will send the
   query QTYPE=NS,QNAME=baz.example to ns1.nic.example.

rather than foo.bar.baz.example to ns1.nic.example without QNAME minimisation

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by dngray** [comment]
This one I think we should give an example, because that's likely to mean more to a reader, but yes, I agree.
