### ISSUE TITLE
Broken jump links

### ISSUE THREAD

**Issue by gurdio** [privacyguides/privacyguides.org#2286]
### Bug description

There is an issue with a broken jump link on the page https://www.privacyguides.org/fr/vpn/#fournisseurs-recommandes. Currently, it directs to https://www.privacyguides.org/fr/vpn/#criteria but it should point to https://www.privacyguides.org/fr/vpn/#confiance.

In addition to the above issue, there are also problems with several other links:

 https://www.privacyguides.org/ru/vpn/#_1
 https://www.privacyguides.org/he/vpn/#_1
 https://www.privacyguides.org/es/vpn/#proveedores-recomendados
 https://www.privacyguides.org/it/vpn/#fornitori-consigliati

Furthermore, there are issues with the following links as well:

https://www.privacyguides.org/it/basics/passwords-overview/#usa-password-generate-casualmente
https://www.privacyguides.org/it/basics/passwords-overview/#password

### Affected pages

-

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by dngray** [comment]
These need to be fixed on crowdin

**Comment by dngray** [comment]
These should be fixed.
