### ISSUE TITLE
Fluent Reader Linux Download

### ISSUE THREAD

**Issue by exaCORE42** [privacyguides/privacyguides.org#2313]
### Affected page

https://www.privacyguides.org/en/news-aggregators/

### Description

The Linux download for Fluent Reader isn't mentioned (the download seems to be available on the github page as an Appimage: https://github.com/yang991178/fluent-reader/releases).

### Sources

https://github.com/yang991178/fluent-reader/releases

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by dngray** [comment]
Not quite sure this is needed, we point to the fluent reader webpage which has link to microsoft store, apple store and github on it. I think that's better than specifically directing users to github. Windows users with S mode or Apple users with gatekeeper on strict settings would want to have it in their respective stores.

**Comment by exaCORE42** [comment]
Sorry to add a new comment to this a week late, but that is what is done for some other recommendations on the site including picocrypt (https://www.privacyguides.org/en/encryption/#picocrypt-file).
