### ISSUE TITLE
Ente is now self-hostable 

### ISSUE THREAD

**Issue by TechFanTheo** [privacyguides/privacyguides.org#2421]
### Affected page

https://www.privacyguides.org/en/photo-management/

### Description

I Propose a description change since ente has open-sourced their server side code, therefore ente is now self-hostable. See [PG post](https://discuss.privacyguides.net/t/ente-open-sources-their-server/17159).

New ente description would be :

"ente is an end-to-end encrypted photo backup service which supports automatic backups on iOS and Android. _Their code is fully open-source, both on the client side and on the server side<del>,so it is self-hostable</del>._ It underwent an audit by Cure53 in March 2023 _and by Faillible in April 2023."_

### Sources

https://ente.io/reports/Fallible-Audit-Report-19-04-2023.pdf
https://ente.io/blog/open-sourcing-our-server/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by brog-io** [comment]
They've also changed their Github to be a monorepo structure. So the Github download should be changed to https://github.com/ente-io/ente/releases
