### ISSUE TITLE
Cover Your Tracks & Browser Fingerprinting

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [privacyguides/privacyguides.org#244]
> EFF created a Tool called Cover Your Tracks to test your browser to see how unique it is. (**https://privacyguides.org/browsers/**)

Cover Your Tracks shows uniqueness and entropy values based on their highly biased data set. A lot of users don't understand browser fingerprinting and start tweaking their browser to get better values on this test page, but in reality they worsen their fingerprint significantly. It should be made clear, that 

- Cover Your Tracks has a highly biased and way too small data set and thus the entropy values and uniqueness are pretty off
- It covers only a small portion of fingerprinting methods available nowadays. 
- Measures taken to improve only on a few metrics, can backfire and worsen your fingerprint overall.
- you should not tweak your browser to get better values on this site
- Give them a list of fingerprinting test sites, not only one, so users can realize how complex this topic is and don't start premature optimization.

I will open a few issues with particular corrections, but tbh the whole Browser Fingerprinting section needs a rewrite

**Comment by rusty-snake** [comment]
See also #90

**Comment by PhysicsIsAwesome** [comment]
> See also #90

Thx. Strangely I searched for "fingerprint" in open issues and found nothing :/
