### ISSUE TITLE
Browser Fingerprinting: Influences

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [privacyguides/privacyguides.org#245]
**https://privacyguides.org/browsers/**

Please clear up a few sentences regarding browser fingerprinting, that could be easily missunderstood.

> You need your browser to look as common as everyone else.

This could be missunderstood as: Just use a browser with standard settings and you're fine. But there is more to it and I think this should be made clear:

- Not only your browser (meaning type, version, extensions, settings), but also parts of your 
- hardware, 
- OS,
- and libraries (like fonts, maths, drivers etc) involved. 

This is what makes browser fingerprinting such a difficult problem on desktop computers and by far not that much on top-selling smartphones or tablets. Worst case: Building your own highly uncommon desktop computer, with a 8k Monitor and your super special Arch Linux build, installing fonts libraries and a customized browser in a seldom way.

> Disabling JavaScript, using Linux, or even using the Tor Browser Bundle, will make your browser stick out from the masses.

- Yes it will let your browser stick out from the masses, but that is not the point to make. It is all about state-of-art detectable features and their real world entropy.
- It could be simply missunderstood, like: Don't use Tor browser. 
- And yes, disabling JavaScript will let you stick out, but it will also block a lot of fingerprinting vectors and thus might outweigh the sticking out.
- Agree on the Linux part, though.

**Comment by dngray** [comment]
We're looking at stripping this section shortly and re-writing it.
