### ISSUE TITLE
Recommended Tools link is not working

### ISSUE THREAD

**Issue by Naxterra** [privacyguides/privacyguides.org#2487]
### Bug description

On the [main discussion page](https://discuss.privacyguides.net) "Recommended tools" link is https://www.privacyguides.org/tools// but it should be https://www.privacyguides.org/en/tools/

https://www.privacyguides.org/tools//  this link is throwing 404 error in the browser debug tool.

### Affected pages

https://discuss.privacyguides.net
https://www.privacyguides.org/tools//
https://www.privacyguides.org/en/tools/

### Browser

Firefox, Edge

### Operating System

Windows

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
Where do you see that link on the main discussion page?

**Comment by Naxterra** [comment]
> Where do you see that link on the main discussion page?

![grafik](https://github.com/privacyguides/privacyguides.org/assets/41871948/8e1471c4-eb22-4c2f-bf52-b19e687a3f6f)

**Comment by jonaharagon** [comment]
Ah, forgot about that one, thanks 😅
