### ISSUE TITLE
Website Issue | Invidious and other frontends are linked on the website directly without thought on switching them

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/privacyguides.org#250]
## Problem

Whenever the site links to some frontend for a service, it does that directly and thus we may technically be linking to a lot of different front-ends, and if something bad happens to them, all links need to be updated separately.

## Solution

Decide which front-ends (or services to be front-ended) we want to use, configure them in `_config.yml` and refer to that variable in the rest of the site, so one place rules the other links.

E.g., if we wished to link to IPFS, we could have `ipfsGateway: https://gateway.ipfs.io` in `_config.yml` and all the pages could have `{{site.ipfsGateway}}/ipfs/<content-ID-here>`. Same logic can be applied to Invidious, Nitter or anything.

**Comment by Mikaela** [comment]
> Self-assigning as an issue I care about and may be PRing by myself so it will be visible in /issues, please feel free to send a PR on this regardless should I not have done that at the time.

**Comment by dngray** [comment]
This is a really important issue, and it's part of the reason why I still refrain from linking to gateway frontends.

**Comment by Mikaela** [comment]
Related: https://github.com/privacyguides/privacyguides.org/discussions/341

**Comment by dngray** [comment]
This has been solved in https://github.com/privacyguides/privacyguides.org/pull/392 we link to https://instances.invidious.io

**Comment by Mikaela** [comment]
I don't see `_config.yml` being changed in #392.
