### ISSUE TITLE
Changes in PR #2471 are not reflected on the site

### ISSUE THREAD

**Issue by redoomed1** [privacyguides/privacyguides.org#2515]
### Bug description

#2471 updated internal links to the new Email Aliasing section on several pages of the site.

However, even though the PR was merged, the changes are not reflected on the affected pages. Additionally, the PR also does not show up in the commit history of these pages. The [2024.04.08](https://github.com/privacyguides/privacyguides.org/releases/tag/2024.04.08) release, which mentions a PR (#2480) that was a _continuation_ of #2471, does not mention this PR.

### Affected pages

- https://www.privacyguides.org/en/financial-services/#mysudo-us-paid
- https://www.privacyguides.org/en/basics/account-creation/#email-aliases
- https://www.privacyguides.org/en/os/ios-overview/#icloud_1

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by dngray** [comment]
I think something happened around the time we did https://github.com/privacyguides/privacyguides.org/commit/b5369286617e54535c9af2bcf449eac6ed0c0efd, perhaps I merged and it was force pushed over.

In any case I made sure to reapply it https://github.com/privacyguides/privacyguides.org/commit/09d3669fcfd970b2ba0c2d76e18ee749ff8adcca
