### ISSUE TITLE
Different font size for "Contributors" label on mobile UI

### ISSUE THREAD

**Issue by redoomed1** [privacyguides/privacyguides.org#2533]
### Bug description

This is by no means a showstopper, but a bug nonetheless. The "Contributors" text on the left overview sidebar in the mobile UI of Privacy Guides ([2024.04.14](https://github.com/privacyguides/privacyguides.org/releases/tag/2024.04.14)) is in a slightly smaller font than the font of the other labels.

#### Browser: Vanadium
![contributors-vanadium-font-size](https://github.com/privacyguides/privacyguides.org/assets/161974310/215cb5e2-8ca0-47f7-9277-749b1ae4fbc8)

This does not affect the desktop UI of the site:

#### Brave (desktop)
![contributors-brave-desktop](https://github.com/privacyguides/privacyguides.org/assets/161974310/8c310a29-9e20-4e5d-8e37-cf274a0f62a9)

#### Tor Browser on Safest security level (desktop)
![contributors-tor-desktop-safest](https://github.com/privacyguides/privacyguides.org/assets/161974310/b4781922-817a-4399-8383-5adc2aa417ae)

### Affected pages

- https://www.privacyguides.org/en/about/contributors/

### Browser

Other

### Operating System

Android

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by rollsicecream** [comment]
Can confirm this on Brave Android

**Comment by jonaharagon** [comment]
lmao weird - seems like a bug with https://squidfunk.github.io/mkdocs-material/plugins/typeset/
