### ISSUE TITLE
Contributors table doesn't scale well on mobile devices

### ISSUE THREAD

**Issue by jordan-warne** [privacyguides/privacyguides.org#2541]
### Bug description

When viewing the contributors page on a mobile device the contributors table doesn't scale to the screen width meaning you have to scroll left and right, this isn't very intuitive perhaps it should be adjusted to scale with the size of the screen so you don't have to scroll left and right?

Example:

![image](https://github.com/privacyguides/privacyguides.org/assets/154663344/693e292e-a438-4a30-992d-f451a3f01af0)

375x667 screen size

### Affected pages

- https://www.privacyguides.org/en/about/contributors/

### Browser

Safari

### Operating System

iOS

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
Yes it should, I just didn't want to figure out how to do that lol
