### ISSUE TITLE
Broken LanguageTool logo after 2024.04.16 update

### ISSUE THREAD

**Issue by redoomed1** [privacyguides/privacyguides.org#2549]
### Bug description

On the latest release of the site indicated in the issue title, the logo for LanguageTool is broken on both the Productivity Tools page and `tools.md`.

![languagetool-broken-logo](https://github.com/privacyguides/privacyguides.org/assets/161974310/2a025b51-6a56-414a-8c1c-de6ad5981a22)

![languagetool-tools-logo](https://github.com/privacyguides/privacyguides.org/assets/161974310/dbbeea34-fbef-4f8f-815d-963974abe1b4)

There were, and still are, no issues with the logo when looking at the [GH actions preview](https://github.com/privacyguides/privacyguides.org/pull/2013#issuecomment-2053926314) at every point of the PR. The path to the svg in the code for both of the affected pages looks fine as well.

I did some sleuthing and noticed that the other logos for the productivity tools all had #2054 in common, and the [LanguageTool PR](https://github.com/privacyguides/privacyguides.org/pull/2013) was opened (2023.02.18) before #2054 was merged (2023.02.28). Maybe this is the culprit?

### Affected pages

- https://www.privacyguides.org/en/productivity/#languagetool
- https://www.privacyguides.org/en/tools/#productivity-tools

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
I am not seeing a broken image on my end 👀

**Comment by lamtrinhdev** [comment]
It look likes the network issue. It is fine for me on iPhone with Safari Browser.
![Uploading IMG_6134.png…]()

**Comment by rollsicecream** [comment]
Me too, no problems on my end.

**Comment by redoomed1** [comment]
Turns out it was a network issue as @lamtrinhdev suggested. I switched to a VPN server of a different provider and the logo loaded as expected.
