### ISSUE TITLE
Cannot load infomation in "Multi-Factor Authenticators" popup.

### ISSUE THREAD

**Issue by lamtrinhdev** [privacyguides/privacyguides.org#2551]
### Bug description

When I access "Knowlegde Base" => "Introduction to Passwords" section. It does not show infomation of "multi-factor authentication" popup. At least, it should show 2 first line titiles they are

"Hardware Security Keys
YubiKey
...."

You can refer attached photo for more details.

![IMG_6136](https://github.com/privacyguides/privacyguides.org/assets/49742151/5753a666-5061-4f82-8ce5-bc306d19f6fe)

### Affected pages

-

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by redoomed1** [comment]
Thanks for observing this issue, @lamtrinhdev ! I think the behavior of the popup here bears some similarity to the one I noted in this comment: https://github.com/privacyguides/privacyguides.org/pull/2451#issuecomment-2037930893

> I think that the previews for "whole page links" cover anything until the first permalink on the page, which explains the above behavior.

On the Multi-Factor Authenticators page, there is no text between the title of the page and the first permalink (i.e., the "Hardware Security Keys" heading, which explains the lack of information in the popup on the page you show in this issue.

**Comment by lamtrinhdev** [comment]
Thank you for your comment @redoomed1 . Just raise the ticket to Admin to consider to enhance if needed.

**Comment by jonaharagon** [comment]
Yeah, we can fix this, because I think we should have an introductory paragraph explaining what MFA is, like we do on other pages.

We should also probably start to rewrite some of those introductions with this new hover feature in mind.

**Comment by lamtrinhdev** [comment]
It sounds great, @jonaharagon .

**Comment by redoomed1** [comment]
Behavior was fixed with #2594 

![fixed-instant-preview](https://github.com/privacyguides/privacyguides.org/assets/161974310/5f56d3e9-e64a-458e-87ea-38fa5ead2ac8)

**Comment by lamtrinhdev** [comment]
Thank you, @redoomed1 . It is great.
