### ISSUE TITLE
Remove the outdated information regarding Notesnook's encryption

### ISSUE THREAD

**Issue by MooseExplorer637** [privacyguides/privacyguides.org#2556]
### Affected page

https://www.privacyguides.org/en/notebooks/?h=notesnook#notesnook

### Description

With the release of v3, Notesnook now supports at rest encryption, so your notes are encrypted on the device, even without the private vault feature.

### Sources

https://blog.notesnook.com/introducing-notesnook-v3/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by dngray** [comment]
This one has been completed.
