### ISSUE TITLE
Invidious video embeds are broken

### ISSUE THREAD

**Issue by fincentxyz** [privacyguides/privacyguides.org#2564]
### Bug description

Some (maybe all) Invidious video embeds seem to be broken.

### Affected pages

- https://www.privacyguides.org/en/os/linux-overview/#release-cycle

### Browser

Firefox

### Operating System

Linux

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by kimg45** [comment]
Maybe it would be better to just download the videos and put them in the page instead of linking to invidious
