### ISSUE TITLE
Website still lists Local Monero

### ISSUE THREAD

**Issue by tnonate** [privacyguides/privacyguides.org#2571]
### Affected page

https://www.privacyguides.org/en/advanced/payments/#acquisition

### Description

First paragraph, second sentence:

> P2P marketplaces like [LocalMonero](https://localmonero.co/), a platform which facilitates trades between people, are one option that can be used.

With Local Monero winding down (source below), you should probably change this to another similar exchange of some sort or remove it entirely.

### Sources

https://localmonero.co/blog/announcements/winding-down

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by redoomed1** [comment]
Already fixed in #2565, just not released on the site yet.
