### ISSUE TITLE
ente Auth repo link

### ISSUE THREAD

**Issue by jermanuts** [privacyguides/privacyguides.org#2593]
### Affected page

https://www.privacyguides.org/en/multi-factor-authentication/

### Description

The source code link for ente Auth points to https://github.com/ente-io/auth which might leave visitors confused as most of the description is related to their main product, Ente Photos.

We should update it to https://github.com/ente-io/ente/tree/main/auth

### Sources

...

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
> let's not put people to the source files.

well, it is the "source code" link we're referring to here *I think?*

![2024-05-30 at 22 30 02](https://github.com/privacyguides/privacyguides.org/assets/3637842/5fb8b4ae-6120-4413-84ef-9c40267ed631)

It looks like what happened is that they just deleted the ente-io/auth repo and moved/redirected it to ente-io/ente/auth so... I suppose https://github.com/ente-io/ente/tree/main/auth would be more appropriate.

Actually, we could link to **https://github.com/ente-io/ente/tree/main/auth#readme** it looks like, if we prefer to point people to readable text :)
