### ISSUE TITLE
Split up Productivity Tools page

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#2596]
I feel like we've been treating this like a miscellaneous page. Why don't we just make all of these their own pages?

- Document Collaboration
- Office Suites
- Pastebins
- Language Tools

**Comment by dngray** [comment]
Inclined to agree, i checked out https://github.com/privacyguides/privacyguides.org/pull/2598 and links to make sure nothing is broken and i think we should do this. If a page has too much on it, then people might have trouble finding things.

**Comment by redoomed1** [comment]
I already created the other separate pages in different branches of my fork, just need to create PRs for them.

Also, any tips on WebP optimization for the page covers? I documented what I did for the Pastebins cover [here](https://github.com/privacyguides/privacyguides.org/pull/2598#issuecomment-2143549648), but I'm not sure if it conforms with the rest of the existing covers.
