### ISSUE TITLE
Regarding the last criterion on the MFA tools page

### ISSUE THREAD

**Issue by redoomed1** [privacyguides/privacyguides.org#2608]
### Affected page

https://www.privacyguides.org/en/multi-factor-authentication/#criteria

### Description

Another person on the PG Matrix pointed this out:

> i just read https://www.privacyguides.org/en/multi-factor-authentication/ and it seems like Ente is not fit for the criteria?

     Auth provides end-to-end encrypted cloud backups so that you don't have to worry about losing your tokens.
     We use the same protocols Ente Photos uses to encrypt and preserve your data.

> did this change recently?

> not even optional is allowed, as per criteria

     Must not sync to a third-party cloud sync/backup service.

     Optional E2EE sync support with OS-native tools is acceptable, e.g. encrypted sync via iCloud.

> their service is third party (that's why it needs a login)

### Sources

- https://apps.apple.com/app/id6444121398 (source for the first quote in plain text, which can be found under the "SECURE BACKUPS" heading in the app's description)
- https://github.com/ente-io/ente/tree/main/auth#-architecture

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by rollsicecream** [comment]
The main word here in this criteria is : **third-party**

So, I think in the case of Ente Auth, it's totally okay since they use their own sync solution. This criteria meant to say that 2FA apps shouldn't use 3rd party services like Google Drive, OneDrive and other services.

I could have been wrong though.
