### ISSUE TITLE
Add more space to bottom of side navigation list on desktop

### ISSUE THREAD

**Issue by antgig** [privacyguides/privacyguides.org#2613]
### Bug description

On desktop, there is little room at the bottom of the Knowledge Base and Recommendations pages. On the Knowledge Base page, the last item (Windows and Group Policy Settings) is almost flush with the edge of a desktop screen. Same thing for the Recommendations page and the Device Integrity item.

Perhaps having the bottom of side navigation list higher on the page would fix this issue.

### Affected pages

-Recommendations
-Knowledge Base

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
Can you send a screenshot of what you're referring to here? I'm not sure I'm seeing this on my device.

**Comment by kimg45** [comment]
![Screenshot 2024-07-24 at 2 56 59 PM](https://github.com/user-attachments/assets/95bb9128-7e55-4a5c-9a30-99df84753652)
Seems like there's enough space there. Looks exactly the same on Firefox and Chrome as well.
