### ISSUE TITLE
Missing deploy previews

### ISSUE THREAD

**Issue by redoomed1** [privacyguides/privacyguides.org#2625]
### Bug description

The most recent PR I submitted (#2624) did not generate a GitHub Actions preview.

Additionally, existing preview links for open PRs no longer function (i.e., they return "Site Not Found" error pages).

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by nopeitsnothing** [comment]
Seems like this is a common issue for organizations. My own actions as well as actions from other repos do not seem to be working. I even updated their dependencies (e.g. v4 to v5) thinking that might work. It didn't do a thing. The GitHub seems broken.

**Comment by nopeitsnothing** [comment]
This was and still is an incident involving Github Actions and Workflows: https://www.githubstatus.com/incidents/5yx1d67vq9hg. This is still broken for me and Anonymous Planet, even after updating billing to force a re-check of credentials. I don't know if they think they fixed it or what.

**Comment by redoomed1** [comment]
Update:

Existing preview links for open PRs now work, but new commits don't update the preview (it's stuck on the last commit before whenever GitHub Actions stopped working).

**Comment by jonaharagon** [comment]
All builds are broken because of https://github.com/simple-icons/simple-icons/pull/10019
