### ISSUE TITLE
NextDNS is not in the DNS Table

### ISSUE THREAD

**Issue by arthsmn** [privacyguides/privacyguides.org#2633]
### Affected page

https://www.privacyguides.org/en/dns/#recommended-providers

### Description

NextDNS is not in the DNS table, but it is mentioned below.

### Sources

https://www.privacyguides.org/en/dns/#recommended-providers

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by redoomed1** [comment]
> NextDNS is not in the DNS table, but it is mentioned below.

Yes. As explained in the following links, this arrangement is intentional:

https://github.com/privacyguides/privacyguides.org/pull/2330#discussion_r1526341356

https://discuss.privacyguides.net/t/split-dns-recommendations-into-secure-non-filtering-providers-and-filtering-saas-providers/15026

**Comment by arthsmn** [comment]
Oh, thanks! Sorry!
