### ISSUE TITLE
Google Advanced Protection Program now supports passkeys

### ISSUE THREAD

**Issue by BionicBison05** [privacyguides/privacyguides.org#2638]
### Affected page

https://www.privacyguides.org/en/os/android-overview/#advanced-protection-program

### Description

The current Android overview page states that the Google Advanced Protection Program “is available at no cost to anyone with two or more hardware security keys with FIDO support.” This is no longer true, as users can now enable it with only a passkey. Though arguably less secure than using APP with a physical security key, a benefit of this is that it enforces the use of the passkey rather than allowing a fallback to any less secure verification methods a user may have registered.

### Sources

https://blog.google/technology/safety-security/google-passkeys-advanced-protection-program/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by dngray** [comment]
Merged in https://github.com/privacyguides/privacyguides.org/commit/cbee8396715b6cb019f3b0b9c0e8849a2e0eca03
