### ISSUE TITLE
Brave Wallet now supports an anonymous crypto-currency

### ISSUE THREAD

**Issue by fmarier** [privacyguides/privacyguides.org#2648]
### Affected page

https://www.privacyguides.org/en/desktop-browsers/#brave-rewards-and-wallet

### Description

This part of the sentence is no longer true:

> Brave Wallet operates locally on your computer, but **does not support any private cryptocurrencies**, so we would discourage using this feature as well.

### Sources

https://x.com/brave/status/1756138102395973834
https://support.brave.com/hc/en-us/articles/26390040705165-Zcash-and-Address-Types

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
Thanks for reporting!

We would be looking for support for cryptocurrencies on https://www.privacyguides.org/en/cryptocurrency/

I remember Zcash was specifically excluded from that section... we could look at the cryptocurrency discussions to see why that was the case. I think if we want to consider Zcash a "private cryptocurrency" for _our_ purposes we should have a discussion about it on the forum, so I'm going to close this.

**Comment by jonaharagon** [comment]
Oh, also this would be another reason to not make any changes here even if Zcash was alright:

> At this time, Brave Wallet only supports Transparent addresses.

**Comment by fmarier** [comment]
Just noting that shielded transactions are now supported in Brave Wallet: https://brave.com/blog/shielded-zcash/
