### ISSUE TITLE
Privacy Guides requiring signed commits raises the bar for contributions

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/privacyguides.org#266]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/265

<div type='discussions-op-text'>

<sup>Originally posted by **Mikaela** November  9, 2021</sup>
From https://github.com/privacyguides/privacyguides.org/pull/258#issuecomment-963570912 I understand that we are currently requiring all commits to main to be signed. I think this is a mistake.

I cannot think of any tool that has been called unapproachable and difficult around me as much as gpg. On Windows it requires installing, then there is the magic of generating keys and then I think majority of users neglect backing the key, revocation certificate or at least setting an expiration date as the internet is full of poor advice.

Finally there is configuring git to sign commits and use the key with a couple of `git config`s which graphical applications including VS Code and GitHub For Windows simply ignore.

I have heard git may start supporting signing by SSH keys, but I don't think that is in production today and it wouldn't be of help to contributors who use HTTPS remotes for whatever reason (GitHub for Windows).</div>

**Comment by dngray** [comment]
I suppose from a core-team member perspective, only core team members have the ability to merge, so we can sign contributor's requests, but I'm not entirely certain about how much is gained from that.

**Comment by Mikaela** [comment]
Who are the core team members and how can they force a merge? Do they relate to creation of subteams?

**Comment by dngray** [comment]
> Who are the core team members and how can they force a merge? Do they relate to creation of subteams?

To force a merge you have to actually be an administrator which is @jonaharagon, myself.

There is nothing stopping a team member from signing a contributor's commit and pushing that to the repository though.

**Comment by Mikaela** [comment]
> There is nothing stopping a team member from signing a contributor's commit and pushing that to the repository though, then you shouldn't need to force the merge.

Do you mean `git commit --amend` and `git push <remote> <pr-branch> --force` or `git commit -m "sign" --allow empty && git push <remote> <pr-branch>` ?

Is this additional trouble worth it?
