### ISSUE TITLE
Color assignment class not applying to links

### ISSUE THREAD

**Issue by redoomed1** [privacyguides/privacyguides.org#2706]
### Bug description

#2686 introduced color-coded links that correspond with how common threats are formatted on the [titular page](https://www.privacyguides.org/en/basics/common-threats/) in the Knowledge Base. However, on the live site, the color-coded links do not behave the way that they are expected to, even though _they behave as expected in the deploy preview_ for the linked PR.

**Expected Behavior**: The "Supply Chain Attacks" links on the affected pages should be veridian (`.pg-viridian`).

**Actual Behavior**: These links are the same color as any regular link (yellow in dark mode, blue in light mode).

![color-class](https://github.com/user-attachments/assets/a97ef46c-bd6c-465f-b676-dca5e40415fa)

Reproducible on Mullvad Browser and Vanadium

### Affected pages

- https://www.privacyguides.org/en/desktop/#nixos
- https://www.privacyguides.org/en/basics/common-misconceptions/#open-source-software-is-always-secure-or-proprietary-software-is-more-secure
- https://www.privacyguides.org/en/os/linux-overview/#arch-based-distributions

### Browser

Other

### Operating System

Linux, Android

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
I suspect this is a CDN caching issue. I have to set up new webservers next week anyways, so we'll see if that fixes it.
