### ISSUE TITLE
Matrix keeps asking for phone permissions

### ISSUE THREAD

**Issue by HardenedVariety** [privacyguides/privacyguides.org#2711]
### Bug description

Keep getting notifications that [Amdocs](https://youtube.com/watch?v=1YbpKeWBwa0), the telecommunications company that datamined and spied on americans, needs access to my call logs and SMS?

### Affected pages

-

### Browser

Other

### Operating System

Android

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by dngray** [comment]
The Amdoc think was debunked ages ago https://news.ycombinator.com/item?id=36021353

If you're talking about element, it uses a number of permissions for legitimate purposes.

Also this is the wrong place for such discussions see our forums https://discuss.privacyguides.net
