### ISSUE TITLE
[FORUM] Green code block text in user profile 

### ISSUE THREAD

**Issue by rollsicecream** [privacyguides/privacyguides.org#2748]
### Bug description

When visiting any user profile of the Privacy Guides forum, I see a green code block text for no reason named ``user-profile-secondary``

![image](https://github.com/user-attachments/assets/2b4ec7d6-d19a-4e3e-85c1-511771c2bdcb)

When I click on it, I got this: 

![image](https://github.com/user-attachments/assets/a864273d-3b48-4303-aeed-1bee843aa17a)

There's a little GitHub logo in the left, I clicked it and redirected to a GitHub code search: 

![image](https://github.com/user-attachments/assets/5559cc15-3faa-4860-8102-aa8d16ee581c)

### Affected pages

- All user profiles of the Privacy Guides forum

### Browser

Other

### Operating System

Linux

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by DeadBoySmile** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by rollsicecream** [comment]
> try this https://gofile.io/d/Lji8KD select the desired compiler in the installer

Ah, that's new, a bot in GitHub lol
