### ISSUE TITLE
cloudflare dns has ecs without logging

### ISSUE THREAD

**Issue by D3LTA-AK74** [privacyguides/privacyguides.org#2757]
### Affected page

https://www.privacyguides.org/en/dns/

### Description

cloudflare zero trust has the ability to create a dns for users that has ecs enabled and logging disabled.
![1 - Copy](https://github.com/user-attachments/assets/0bb17f3a-a55b-4737-b81b-553b07622072)

### Sources

one.dash.cloudflare.com

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by friadev** [comment]
This page is specifically referring to their public 1.1.1.1 resolver.
