### ISSUE TITLE
RSS feed stopped working

### ISSUE THREAD

**Issue by tEctutoRIt** [privacyguides/privacyguides.org#2758]
### Bug description

I absolutely loved following the website articles using https://blog.privacyguides.org/feed/, but recently it's not working. It would be so great if there was a button or icon on the website to know/follow the RSS feed. I'm sure lots of other people would love to be able to follow it too! Please add RSS feed and easily visible way to follow it on website.

### Affected pages

-

### Before submitting

- [X] I am reporting something that is broken on the website, not making a suggestion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
I think this should be available at https://www.privacyguides.org/articles/feed_rss_created.xml now, I'll add a redirect to the old URL in a bit.

**Comment by cameronj86** [comment]
Was able to add thanks to finding this thread. 

If possible, I do think that the functionality being available on-site might increase rss users furthers:
![image](https://github.com/user-attachments/assets/3703462f-be29-411f-9072-f548a0f017d6)
