### ISSUE TITLE
Incorrect assumption about DNS on port 53

### ISSUE THREAD

**Issue by ignoramous** [privacyguides/privacyguides.org#2773]
### Affected page

https://www.privacyguides.org/en/advanced/dns-overview

### Description

The website goes:

> Unencrypted DNS always uses port 53 and always uses UDP.

Unencrypted DNS can use any port (but usually does not by convention / standards) and is supported over TCP (by standards).

### Sources

https://datatracker.ietf.org/doc/html/rfc1035#section-4.2

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
Good catch, not sure why we say that when DNS over TCP is quite common.

**Comment by ignoramous** [comment]
> not sure why we say DNS over TCP is quite common

There seems to be an endless supply of incorrect implementations of FOSS DNS clients (for Android specifically) that don't handle *DNS over TCP*. So, it isn't just PG.
