### ISSUE TITLE
DNS Resolvers

### ISSUE THREAD

**Issue by wincmd64** [privacyguides/privacyguides.org#2777]
### Affected page

https://www.privacyguides.org/en/dns/

### Description

The "ad blocking" column is missing.

### Sources

like here https://avoidthehack.com/best-dns-privacy

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by kimg45** [comment]
That's what "Filtering" is.

**Comment by wincmd64** [comment]
This is a lie. Some services block ads, others - don't.

This privacyGUIDEs is for whom? For housewives? Or authors are just lazy?
