### ISSUE TITLE
git.jonaharagon.net being behind cloudflare is not very privacy respecting

### ISSUE THREAD

**Issue by endingisnight** [privacyguides/privacyguides.org#2840]
### Affected page

https://git.jonaharagon.net/privacyguides/privacyguides.org

### Description

It's a literally a MITM attack

### Sources

https://0xacab.org/dCF/deCloudflare

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by jonaharagon** [comment]
Mirrors are supplementary resources nobody is required to use. GitLab does the same.
