### ISSUE TITLE
Add explanation for verified boot

### ISSUE THREAD

**Issue by tommytran732** [privacyguides/privacyguides.org#290]
This issue is a note to make proper explanation on why verified boot is important later on

**Comment by zecamigo** [comment]
Aren't you guys confusing privacy with security?
I mean AFAIK, verified boot will protect against evil maid attacks. This is mostly a security issue, and a bit distant from typical privacy concerns along that spectrum. It has little to do with protecting oneself from surveillance, unless you're targeted. Maybe you should take into consideration privacy needs of different levels and also the fact that the remaining ROM's support a very limited range of devices. (cross commenting from related merge request).

**Comment by dngray** [comment]
We're looking at a criteria for the for the mobile OS.

I think the general consensus is there is too much uncertainty over *random rom* for *random mobile device*.

Providing a criteria and requiring verified boot limits our recommendations to devices we know at least are able to meet a minimum security baseline.

**Comment by PhysicsIsAwesome** [comment]
> Aren't you guys confusing privacy with security?

You cannot really separate the two. For privacy you need to secure stuff you want to keep secret from access through other parties. And by getting hacked you could lose all digital privacy. An example is, that a lot of people root their smartphone to get additional privacy stuff working, that needs deep integration into the system, but aren't aware, how much vulnerable this makes the device. To be able to make good decisions you need to know the pros and cons of the security and privacy aspects.

**Comment by zecamigo** [comment]
>  An example is, that a lot of people root their smartphone to get additional privacy stuff working, that needs deep integration into the system, but aren't aware, how much vulnerable this makes the device.

Spot on. LineageOS stopped shipping SU from v.17. Root access via ADB is very limited and they're continuously hardening the OS security wise. Still don't understand the threat model leading to this decision,.

**Comment by jonaharagon** [comment]
I think this is covered by #371 now, but add a note to that discussion if you feel it isn't.

**Comment by zecamigo** [comment]
What's the advantage of a verified boot again? https://www.theverge.com/2021/12/4/22817758/broken-google-pixel-phone-privacy-leak

**Comment by SkewedZeppelin** [comment]
Verified boot has nothing to do with the user not having a (strong) pin/password
set.
