### ISSUE TITLE
Recommend Age

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#291]
## Description

**URL of affected page:** https://privacyguides.org/software/productivity/#encrypt

https://github.com/FiloSottile/age

**Comment by Loki-L1130** [comment]
This seems like a CLI Tool.

**Comment by dngray** [comment]
It is, but it is:

- modern code
- fairly decent and supported on a lot of platforms.

We don't not mention CLI tools as we do mention `tomb` on that page.

Ideally it would be a nice first project for someone to make a graphical user interface maybe in Qt using that tool.
