### ISSUE TITLE
Aether is no longer open-source

### ISSUE THREAD

**Issue by yhoyhoj** [privacyguides/privacyguides.org#311]
## The last version of Aether (.15) is closed source

**URL of affected page:** https://privacyguides.org/providers/social-news-aggregator/

I wanted to check the source code of Aether and it turns out the [repository](https://github.com/aethereans/aether-app/commits/master) has not been updated with code since May 2020. 
The last version 0.15 has been released in November 2020 and there is no mention of it in the repository.

This means Aether is no longer open source. 
While the last open-source version might still be compatible with the protocol, there is no easy way to get it, besides compiling it.

It is still decentralised, so depending on your criteria of acceptance it might be worth keeping while removing the open-source label.

**Comment by freddy-m** [comment]
Little reason to list it if this is the case.
