### ISSUE TITLE
Website Issue | "Self Hosted Cloud Service" = 404

### ISSUE THREAD

**Issue by RBWare** [privacyguides/privacyguides.org#334]
## Description

Selecting the option for "Self Hosted Cloud Service" is returning a 404.

https://www.privacyguides.org/software/cloud/

**Comment by tommytran732** [comment]
Where do you see that option? I thought I removed it a week ago and merged with cloud storage /shrug

**Comment by tommytran732** [comment]
https://privacyguides.org/cloud/

**Comment by rusty-snake** [comment]
https://www.privacyguides.org/software/ >> Self-Hosted Cloud Server

**Comment by tommytran732** [comment]
Mkay will fix it in my next PR

**Comment by freddy-m** [comment]
Thanks for alerting us @RBWare!

**Comment by tommytran732** [comment]
@freddy-m Actually though, the /software and /provider pages are legacy pages and we are converting to the new formats. Besides, the browser page (which is currently a half converted site) aren't even listed there. Is it okay if I just delete those 2?

We have nothing directly linking to them on PG anyways

**Comment by tommytran732** [comment]
Nevermind about the /providers page, I just realized it's the global surveillance page. I'd still like to remove the software page though as it is a legacy page, does absolutely nothing other than listing things in the navbar, and isn't even linked anywhere in the first place.

**Comment by tommytran732** [comment]
@freddy-m @dngray 

This can be closed, it's fixed in the master branch now.
