### ISSUE TITLE
Website Issue | The contrast of the menus (located at the header) is low

### ISSUE THREAD

**Issue by redudant-overflowing** [privacyguides/privacyguides.org#352]
## Description
When opening the menus from the header, the contrast of the font color and the background color is too low.

## Screenshots
![menu2](https://user-images.githubusercontent.com/93951203/142745618-f4e0e6ba-cd7d-4964-8eb9-03a4ff915e60.png)

**Comment by ElijahPepe** [comment]
The contrast of the two colors is 5.02 which for WCAG compliance would pass the AA level for UI components and any size text. An ideal color would be #d8dddf which would double the contrast.

**Comment by dngray** [comment]
This got fixed in transition to mkdocs https://github.com/privacyguides/privacyguides.org/commit/8ef8e2a263b4e6fd145eb2c171d407de8591e3b3
