### ISSUE TITLE
Website Issue | Implement dark mode alternative images

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#401]
## Description

Implement `-dark` flag so we can have alternative darkmode variants of pictures.

This feature did exist with the old legacy content.

Preventing this:

## Screenshots

![image](https://user-images.githubusercontent.com/48640805/143806327-654e0495-4bde-412b-a9ab-12bfd9f34884.png)

**Comment by jonaharagon** [comment]
Added to recommendation-card in https://github.com/privacyguides/privacyguides.org/commit/becbf3ddcb7eef9ef9dc514c92b9df213d856a65, I'll look at other images Soon™️

**Comment by dngray** [comment]
Well i think this one is done: https://github.com/privacyguides/privacyguides.org/commit/becbf3ddcb7eef9ef9dc514c92b9df213d856a65 https://github.com/privacyguides/privacyguides.org/commit/43c80e7fe2b397a00e6fc2d46b8667bfe8acda51 will continue to fix them as we go.
