### ISSUE TITLE
StartPage's Jurisdiction is wrong

### ISSUE THREAD

**Issue by Loki-L1130** [privacyguides/privacyguides.org#414]
## Description
StartPage is headquarted in the Netherlands but it is shown as US in the site. I think you are mistaken. The PrivacyOne Group which bought majority stake is located in US and StartPage is still in Netherlands and they are the Deciding authority.

This issue was brought up here. Due to this, reddit Post : https://www.reddit.com/r/PrivacyGuides/comments/r5osd2/website_shows_startpage_as_a_usa_company_isnt_it/

**URL of affected page:**
https://privacyguides.org/search-engines/

**Comment by freddy-m** [comment]
See this article from the old PrivacyTools: https://web.archive.org/web/20210419235515/https://blog.privacytools.io/relisting-startpage/

**Comment by ph00lt0** [comment]
I believe @Loki-L1130 is right tho @freddy-m. The Privacy Policy of startpage specifically lists the address in the Netherlands. Also the Dutch DPA is listed as supervisor.

https://www.startpage.com/en/privacy-policy/

**Comment by tommytran732** [comment]
Yeah, the majority stake holder is in the US, but the company itself is in the Netherlands
