### ISSUE TITLE
Should you really be recommending using all lists on uBO?

### ISSUE THREAD

**Issue by youdontneedtoknow22** [privacyguides/privacyguides.org#427]
## Description
So I like the new browser section. One thing I noticed was recommending to enable all lists for ads and privacy, and "annoyance" and "multiple purposes" could just break some things, but it's okay.
I believe we should listen to Gorhill's advice about this. To make it short:
1- enable the regional list (which you completely forgot and I can tell you I can't use websites from my country without being flooded with ads without this list) (unde Regions, Languages)
2- Fanboy's Annoyance (under annoyance)

And what he didn't mention but is important to us is:
3- AdGuard URL Tracking Protection (under privacy)

 This is from his wiki:
https://www.reddit.com/r/uBlockOrigin/wiki/index#wiki_which_filter_lists_should_i_select.3F

When being asked what could happen if someone enabled the Adguard list (next to the on default enabled Easylist) he said:

> Nothing specific happens and this version of Base list is specific to uBO (does not include EasyList, so you need to have EL subscribed) AdGuard is just more popular in some regions and because of this filters will be more optimized for pages visited by users from these regions.
> 
> Only problem with custom settings is you will need to fix your potential issues by yourself or in cooperation with list author(s) - they will not be fixed in uBlock filters

Source: https://www.reddit.com/r/uBlockOrigin/comments/jojw0w/recommended_basic_filter_list/

Of course if you have other sources that recommend enabling all lists, I'd be glad to read them :) I'm here to learn, not to force my opinion.

**Comment by dngray** [comment]
The instructions there clearly say under  “Ads”, “Privacy” and “Malware domains”.

It then goes on to say:

> “Annoyances” and “Multipurpose” lists can also be enabled, but they may break some social media functions.

It doesn't say anything about adding all of the regional lists.

**Comment by youdontneedtoknow22** [comment]
I'm not sure you understand my point.
My point is, we don't have to enable all lists for Ads and privacy (or tell users they can enable all lists from annoyance and multipurpose but it can lead to breakage). The recommended thing (for beginners) to do is the 3 things I mentioned (I just quoted the first 2 from Gorhill and add the third). I mean yeah they can enable all lists. But when it comes to breakage, they will just disable uBO all along to be able to surf the web normally.
And we should mention this about the regional lists, they are helpful (you can only realize this if you live in a country outside the US and see all the ads and popups on other websites which aren't included in the default lists)
