### ISSUE TITLE
🆕 Software Suggestion | 

### ISSUE THREAD

**Issue by GigaMick** [privacyguides/privacyguides.org#430]
Hey I put together this app for sharing private notes as I had become unhappy with my usual tool (PrivNote).

Introducing [burnernote.com](https://burnernote.com)

Ive made this free, ad-free and open source. 

I believe it stands out from the other tools out there because it doesn't carry ads, it's open source and it's pretty drilled down on clean and minimalist design.

I have no intentions to monetise I just wanted to make something people would like to use.

Encryption-wise I employ AES-256-CBC with "Encrypt then MAC".

**Comment by ph00lt0** [comment]
This should be transferred to a discussion, but the website connects to Google Fonts and should therefore not be listed imo.
