### ISSUE TITLE
Should have do not track mentioned in browsers

### ISSUE THREAD

**Issue by Samisafool** [privacyguides/privacyguides.org#449]
## Description

**URL of affected page:**

https://privacyguides.org/browsers/#desktop-only-recommendations

Firefox has no mention of do not track??

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think if they dont mention it then u shouldnt enable it.

I also read somewhere that do not track would make u more identifiable

**Comment by BraINstinct0** [comment]
Yes, most sites do not respect DNT correctly. Those who intend to track will track anyways; reducing a potential fingerprinting option at the cost of having to manually reduce tracking seems reasonable.
1. unlike what panopticlick or the similar show - if you think of the userbase of those tests, seeing DNT enabled by may users can easily be a sampling bias
2. for DNT to be beneficial, one should have to `trust the provider` that they'll not track you if you have DNT sent. 

Note: I am not an active part of the PrivacyGuides community, so the majority might not agree with me. Waiting for other answers might also be beneficial.

**Comment by dngray** [comment]
Basically what @BraINstinct0 said. It's another data point for fingerprinting, and a lot of adtech doesn't respect it anyway.
