### ISSUE TITLE
Include Submenu/Hyperlinks under Browsers Page

### ISSUE THREAD

**Issue by samcross021** [privacyguides/privacyguides.org#48]
## Description
Include a submenu/drop-down/hyperlinks under "Browsers" Page for faster viewing of content of different sections.

## URL
https://www.privacyguides.org/browsers/

## Additional context
It was included in (old)`privacytools.io` website which made mobile and desktop easier to navigate to certain sections.

**Comment by jonaharagon** [comment]
I think this is no longer an issue with the revamped menu and browser page.
