### ISSUE TITLE
Software Suggestion | Privacy Browser | Browsers Page

### ISSUE THREAD

**Issue by samcross021** [privacyguides/privacyguides.org#49]
In the Process of Moving to New Website, I think "_Privacy Browser_" isn't on New Site anyone.
I'm not sure if Privacy Browser still needs Android Webview. If it needs Webview, then It would be good to include Privacy Browser with "_Android Webview_" flair again,.

[https://github.com/privacytools/privacytools.io/issues/1051](url)

**Comment by SkewedZeppelin** [comment]
@sorenstoutner

**Comment by sorenstoutner** [comment]
Yes, Privacy Browser still depends on Android's WebView.

**Comment by jonaharagon** [comment]
For the most part we are trying to shy away from the "worth mentioning" sections of PrivacyTools, either we recommend something or we don't. Are there any benefits to Privacy Browser over our existing Firefox/Bromite/DDG browser recommendations?
