### ISSUE TITLE
Adguard DNS Privacy Policy Link is Broken

### ISSUE THREAD

**Issue by umitseyhan75** [privacyguides/privacyguides.org#502]
## Title says all.

![resim](https://user-images.githubusercontent.com/43583375/147394104-8c5945e7-7149-4939-a452-a07cf323f847.png)

![resim](https://user-images.githubusercontent.com/43583375/147394111-53337baf-854b-4e60-a6f9-f021b054c2c9.png)

**[Encrypted DNS Resolvers](https://privacyguides.org/providers/dns/)**

**Comment by elitejake** [comment]
[The link](https://adguard.com/en/privacy/dns.html) seems to work for me.

**Comment by umitseyhan75** [comment]
It seems to working for me either at this moment. They solved the issue in the time that has passed I believe.
