### ISSUE TITLE
Mailpile is not suitable for end-users

### ISSUE THREAD

**Issue by RandPotato** [privacyguides/privacyguides.org#515]
## Description

From https://github.com/mailpile/Mailpile#installing-mailpile
> Note that Mailpile is still in development and is not suitable for production or end-user use. However, developers and early adopters are encouraged to give it a try and even help us find bugs, fix them and develop new features.

I recommend considering deleting Mailpile or adding a warning to it

**URL of affected page:**
https://privacyguides.org/software/email/

**Comment by jonaharagon** [comment]
This sounds good to me. They haven't released Windows/Mac builds in 3 years and say it shouldn't be used "in part for security reasons" (from https://github.com/mailpile/Mailpile#introduction). 

The project seems to be dead now, which is a bummer. Maybe we should remove it and reconsider when they come back? https://twitter.com/HerraBRE/status/1399077999245463558
