### ISSUE TITLE
Account recycling and digital legacy policy for email

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#531]
## Description

**URL of affected page:** https://privacyguides.org/providers/email/

We should have a heading which describes:

- The policy on account recycling, days/time if an account is inactive, and what happens to it. Whether that be deletion, recycling, or payment required for recovery
- Digital legacy policy, whether this is a feature provided https://github.com/privacyguides/privacyguides.org/discussions/512#discussioncomment-1893530

**Comment by mfwmyfacewhen** [comment]
I think it would be best to just link to their policy rather than duplicating the specific information, but whether or not it is provided at all is definitely something that should be listed.
