### ISSUE TITLE
Mailvelope is not a desktop Email client

### ISSUE THREAD

**Issue by 1hiking** [privacyguides/privacyguides.org#545]
## Description

This tool is not an email client but a browser addon for a web-client

**URL of affected page:**
https://privacyguides.org/software/email/#desktopclients

**Comment by Loki-L1130** [comment]
I agree with you.

**Comment by freddy-m** [comment]
We wanted to add it to the section, but we weren't really sure where to put it. Do you have any suggestions @1hiking? cc @privacyguides/team

**Comment by Loki-L1130** [comment]
How about keeping it under Email Providers ?

**Comment by dngray** [comment]
I think with this one, we want to split that page up in the legacy revamp, essentially allowing for native clients per platform, we could then simply have a web section.

**Comment by dngray** [comment]
I think i'll leave this one under desktop clients. Technically it is, as it only works on desktop browsers.

**Comment by dngray** [comment]
Fixed in https://github.com/privacyguides/privacyguides.org/pull/829, it only works on desktop browsers.
