### ISSUE TITLE
Password managers - outdated link to Last Week Tonight show

### ISSUE THREAD

**Issue by stepech** [privacyguides/privacyguides.org#549]
## Description
When trying to open link provided under `Related Information` to get to Edward Snowden on Passwords, the website appears to be shut down (actually already for 1.5 yrs)

**URL of affected page:**
[https://privacyguides.org/software/passwords/](https://privacyguides.org/software/passwords/)

**Comment by Loki-L1130** [comment]
The Link seems to be fine and it is an Invidious Link.
