### ISSUE TITLE
Removal of the warning for system DNS being ineffective when using VPN

### ISSUE THREAD

**Issue by DeiAsPie** [privacyguides/privacyguides.org#561]
## Removal of the warning for system DNS being ineffective when using VPN

> This is no longer the case the DNS service set as private DNS in Android settings always dominates, no matter what other apps want.

![remove-the-warning](https://user-images.githubusercontent.com/93835541/150640453-23d787f0-426e-4a80-8ea4-31f0f06c6f3a.png)
Remove the Warning

### Code to be changed:
```
<a href="https://developers.google.com/speed/public-dns/docs/using#android_9_pie_or_later" 
class="text-decoration-none badge rounded-pill bg-warning" data-bs-toggle="tooltip" 
title="Android 9's DoT settings have no effect when used concurrently with VPN-based apps which override the DNS.">
<i class="fas fa-exclamation-triangle"></i>
 Warning
</a>

```
### Location of code/URL of affected page:
https://privacyguides.org/providers/dns/

**Comment by xibeifenghenhaohe** [comment]
Perhaps make the title more clear. But yes, encrypted DNS section needs to be updated in accordance to the latest Android version.

**Comment by dngray** [comment]
Resolved in https://github.com/privacyguides/privacyguides.org/pull/767
