### ISSUE TITLE
Removal of UncensoredDNS

### ISSUE THREAD

**Issue by DeiAsPie** [privacyguides/privacyguides.org#572]
## Remove UncensoredDNS
Reason: Doesn't support Qname Minimization.

**URL of affected page:** https://privacyguides.org/providers/dns/

**Comment by tommytran732** [comment]
Right, I will make a PR for it now and hopefully will get merged tonight :)

That said, next time, please open a discussion instead of an issue for this.

**Comment by DeiAsPie** [comment]
OK
