### ISSUE TITLE
Website Issue | HTML tags on meta description

### ISSUE THREAD

**Issue by 1hiking** [privacyguides/privacyguides.org#573]
## Description

I am pretty sure html tags shouldn't be put inside meta description tags. For example on the Android page, there is hyperlink tags.

![image](https://user-images.githubusercontent.com/73438877/150652799-ed8c4c99-32d1-4321-b59d-77b067e37f76.png)

**Comment by DeiAsPie** [comment]
I don't anything wrong here 🤷
