### ISSUE TITLE
FramaDrop Now Defunct

### ISSUE THREAD

**Issue by QL568A6** [privacyguides/privacyguides.org#597]
## Description
The FramaDrop service is no longer at the specified URL and may not be in operation any more.

**URL of affected page: https://privacyguides.org/software/file-sharing/**

**Comment by 34candos** [comment]
Framadrop was indeed discontinued, but the underlying file sharing system (Lufi) still exists. Could another instance of Lufi be recommended as part of PG's file sharing options? What about the Disroot instance? https://upload.disroot.org/
