### ISSUE TITLE
Outdated warnings about CalyxOS's Datura Firewall

### ISSUE THREAD

**Issue by catwithbanana** [privacyguides/privacyguides.org#648]
## Description
The OS page warns that CalyxOS' Datura Firewall may leak. CalyxOS overhauled the implementation of the firewall with their Android 12 update, and as far as I can tell those issues no longer apply. One hasn't been updated in many months, and the other has been marked as solved and closed (after the A12 update).

This warning should be reconsidered. At the very least, the issue that has been solved should no longer be included as a red flag. No additional firewall leaks have been reported on the Git since the A12 update / overhaul. (Issue #889 mentions the firewall but turned out not to be a firewall leak).

**URL of affected page:**
https://privacyguides.org/android/

**Comment by dngray** [comment]
It should be retested.

**Comment by tommytran732** [comment]
Contacted CalyxOS about this. They said they will make a post about the technical details behind it soon but they are currently busy with other stuff. We should wait till then to figure out what they actually changed (yeah we can try to read the code but that would be a lot of work and I'd like to have the high level description of it first).

**Comment by SkewedZeppelin** [comment]
Also Pixel 2 appears to have been dropped as of their February update: https://calyxos.org/news/2022/02/11/android-11-feb-security-update/
