### ISSUE TITLE
Website Issue | The Trachcan Icon In Firefox Focus has White Background in Dark Mode

### ISSUE THREAD

**Issue by mfwmyfacewhen** [privacyguides/privacyguides.org#655]
The trashcan icon in the Firefox Focus section has a distracting white background when the site is in dark mode. Should have a transparent background or separate version for light/dark themes.
![trashcan](https://user-images.githubusercontent.com/94880365/155601288-e2401944-58a6-4657-85ae-1a03cfe94385.png)

**Comment by 0rdinant** [comment]
Will be fixed once #650 is merged.

**Comment by dngray** [comment]
iirc this was always temporary and was done just prior to us having the template logic for dark images.
