### ISSUE TITLE
DivestOS now uses INTERNET permission instead of iptables.

### ISSUE THREAD

**Issue by egecelikci** [privacyguides/privacyguides.org#659]
DivestOS [no longer uses](https://github.com/Divested-Mobile/DivestOS-Build/commit/5e1521700f42a78e10192ece32a5cfc21e8bf58c) leaky iptables approach of LineageOS for network access feature, instead it handles this with INTERNET permission, just like GrapheneOS.

**Related info from project news page:** https://divestos.org/index.php?page=news#2022-03

**These lines are now obsolete**:

https://github.com/privacyguides/privacyguides.org/blob/6862251297c5a56bd78c21ec2d8d52afa9618f9c/_data/operating-systems/android/3_divestos.yml#L11

https://github.com/privacyguides/privacyguides.org/blob/6862251297c5a56bd78c21ec2d8d52afa9618f9c/_data/operating-systems/android/3_divestos.yml#L18

**URL of affected page:** https://www.privacyguides.org/android/

**Comment by tommytran732** [comment]
Will update when there is a new build.

**Comment by SkewedZeppelin** [comment]
All 16.0, 17.1, and 18.1 builds now include this patchset.
