### ISSUE TITLE
Website Issue | About page is missing

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/privacyguides.org#68]
## Description

**URL of affected page:** privacytools.io/about/ redirected to https://www.privacyguides.org/about/ which is a 404 error.

**Comment by blacklight447** [comment]
Thats because we haven't bothered recreating it after the implosion of privacytools. I think readding it would make sense, we could probbaly salvage most of what was on the old page, i wonder what the rest of the team thinks.
Pinging @privacyguides/team

**Comment by dngray** [comment]
Closing as a part of https://github.com/privacyguides/privacyguides.org/pull/898, its just easier to link to GitHub.
