### ISSUE TITLE
🆕 Software Suggestion | MuWire - an anonymous file sharing program over I2P

### ISSUE THREAD

**Issue by zlatinb** [privacyguides/privacyguides.org#684]
Hello, 

I'm re-creating [this issue](https://github.com/privacytools/privacytools.io/issues/2217) which is now archived.  Please let me know if a different template should be used.

# Basic information

Name: MuWire
Category: P2P, File Sharing (not torrent though)
URL: https://muwire.com/ or https://github.com/zlatinb/muwire

# Description

MuWire is a file publishing and networking tool that protects the identity of its users by using I2P technology. Anyone with a desktop computer and an internet connection can create a unique anonymous online persona and publish information of any kind without fear of censorship or persecution.

### Example use case

An example use case is that of Alice, a whistle-blower that wishes to remain anonymous in order to publish sensitive material on an ongoing basis. She creates a MuWire identity (which cannot in any way be linked to her real-world identity) and uses it to distribute information. Alice adds the files containing the sensitive material to her MuWire library and leaves MuWire running.

Bob is a journalist who does not know anything about Alice, but is interested in the type of material she publishes. Furthermore, Bob doesn’t want Alice to know his real-world identity either. He creates a MuWire identity and uses MuWire to search for relevant keywords. Alice’s MuWire node receives those queries and responds with results automatically. Bob then downloads the material from Alice’s MuWire node and verifies that it is genuine and of interest to him. Alice publishes regularly, so Bob subscribes to her publication feed and his MuWire node fetches automatically everything that Alice has made public. MuWire also offers mailbox messaging and chat functionality, so Bob can ask Alice for specific material and even have a real-time chat with her.

The relationship between Alice and Bob is completely anonymous and neither party can learn more about the other without consent.

### Behind the scenes

MuWire uses the I2P network which is known to work even during the strictest internet clampdowns in countries like China and Iran. The technology provides protection against Deep Packet Inspection firewalls and other tools used by state surveillance. From an outside observer the traffic that MuWire/I2P generates is indistinguishable from random static.

# Why I am making the suggestion

I thought it would be a good addition to the PrivacyTools website for the following reasons:

* It enhances the privacy of those wishing to share files
* User interface mimics the old-school file-sharing programs like LimeWire which many are familiar with
* License is GPLv3, even the packaging scripts are available here on GitHub
* Decentralized, self-hostable and documented - there are instructions on the wiki for anyone wishing to create their own MuWire network
* Cross-platform for all desktop/server environments, no mobile support yet
* Encrypted downloads available over the I2P network at the http://muwire.i2p/ site.
* Absolutely no profit motive behind this, I don't even accept donations

# My connection with the software

I am the author

**Comment by zlatinb** [comment]
Ok, will open a discussion

**Comment by ph00lt0** [comment]
https://github.com/privacyguides/privacyguides.org/discussions/687
