### ISSUE TITLE
remove privacy.firstparty.isolate

### ISSUE THREAD

**Issue by tauin** [privacyguides/privacyguides.org#69]
## Description
`privacy.firstparty.isolate` has been made (effectively) redundant with recent firefox updates, and should be removed
**URL of affected page:**
https://www.privacyguides.org/browsers/

**Comment by rusty-snake** [comment]
https://github.com/privacytools/privacytools.io/pull/2081#issuecomment-784441119 and the following

**Comment by dngray** [comment]
> [privacytools/privacytools.io#2081 (comment)](https://github.com/privacytools/privacytools.io/pull/2081#issuecomment-784441119) and the following

What I am looking at doing with that is removing the whole "about:config" section, and just showing what can be achieved through Mozilla's UI.

We'll of course still mention https://github.com/arkenfox/user.js

**Comment by NSABackdoors** [comment]
Any thoughts on how you would expect this to happen?

What does the Strict mode in Firefox leave to be desired? Curious here.

**Comment by PhysicsIsAwesome** [comment]
> What does the Strict mode in Firefox leave to be desired? Curious here.
 A lot of things. privacy.resistFingerprinting is not enabled, just to give an example.

**Comment by PhysicsIsAwesome** [comment]
> `privacy.firstparty.isolate` has been made (effectively) redundant with recent firefox updates, and should be removed

I don't see it being redundant. Do you have a source or sth? [Tor browser](https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/7ed0992f877c447f0605a0e430eedd69aa1fe64d/browser/app/profile/000-tor-browser.js) and [arkenfox](https://github.com/arkenfox/user.js/issues/1051#issuecomment-940903984) still use FPI.

**Comment by rusty-snake** [comment]
If you set ETP=strict, FPI is effectively redundant (for the average user).

**Comment by Thorin-Oakenpants** [comment]
FPI overrides ETP Strict - so you should mention to make sure that is set to false - since you listed it for so long to so many users

**Comment by dngray** [comment]
> FPI overrides ETP Strict - so you should mention to make sure that is set to false - since you listed it for so long to so many users

Would it not be worthwhile to just suggest users create a new profile?

If I'm being totally honest, we don't know what state a user's browser might be in if they've been fiddling with `about:config` settings. I'm not totally confident that flicking that single option will restore things.

Perhaps something general like.

> If you've fiddled with about:config settings in the past, we suggest you create a new browser profile.

**Comment by Thorin-Oakenpants** [comment]
that's up to you .. at arkenfox we can run prefsCleaner or override for a few releases

**Comment by dngray** [comment]
I'm thinking of re-writing the blog article https://privacyguides.org/blog/2019/11/09/firefox-privacy/ so we might mention it there.

**Comment by PinkDev1** [comment]
> removing the whole "about:config" section

How about the contents just be moved into a blog, and then linked on the "Related Information" section? Mozilla frequently removes config options from the GUI and lets them be accesible via about:config only, so removing that section would limit the users a lot.

**Comment by Thorin-Oakenpants** [comment]
> How about the contents just be moved into a blog

that's what arkenfox is for. For most users, turning on HTTPS-Only Mode, ETP Strict and adding uBO is more than enough

**Comment by Loki-L1130** [comment]
@Thorin-Oakenpants, You are right. But I think it could much better like in GUI as https://ffprofile.com which will be easy to be use or how about making a UI like https://privacy.sexy ?

I mean these could be better for the user by finely adjust thing to fix some issues with arkenfox like crashes or incompatiblity with sites.

**Comment by PinkDev1** [comment]
> @Thorin-Oakenpants, You are right. But I think it could much better like in GUI as https://ffprofile.com which will be easy to be use or how about making a UI like https://privacy.sexy ?
> 
> I mean these could be better for the user by finely adjust thing to fix some issues with arkenfox like crashes or incompatiblity with sites.

A bit unrelated but thanks for the links! They seem really handy for mass-deployments

**Comment by Thorin-Oakenpants** [comment]
> But I think it could much better like in GUI

I have thought about adding a github page for arkenfox that loads the user.js and lets you filter prefs: such as by version, by setup tag, etc - but at the end of the day there are only a handful of items that most people need to change
- I count [about 10 items at most](https://github.com/arkenfox/user.js/wiki/1.3-Implementation)
  - FPI will be dropped in a few releases in favor of Total Cookie Protection

IDK how much easier it can get than for someone to read a wiki page, and to open the user.js and search for `[SETUP`

I also find ffprofiler
- contains dubious recommendations
- contains useless prefs
- contains outright dangerous recommendations
- lacking in warning information
- out of date
- weird defaults

I just checked it out again and it's still terrible

**Comment by dngray** [comment]
This will get closed soon when https://github.com/privacyguides/privacyguides.org/pull/383 and https://github.com/privacyguides/privacyguides.org/pull/309 is finished. Should happen this week.
