### ISSUE TITLE
Website Issue | Tor Onion Service Down

### ISSUE THREAD

**Issue by fjx5d** [privacyguides/privacyguides.org#691]
## Description

At one point privacyguides.org [returned the onion-location header](https://archive.today/ohRRD#privacy-guides), advertising the presence of an onion service. Now the onion service appears to be down / non-existent; the header is no longer present in the HTTP response and the address (`xpqizwv63kdv3wxcecdrokx24itbts7y2tedemntqeyc2wbm3lrobbid.onion`) fails to load.

```
Details: 0xF0 — The requested onion service descriptor can't be found on the hashring
and therefore the service is not reachable by the client.
```

**Comment by jonaharagon** [comment]
This is done, and privacyguides.org correctly returns an `Onion-Location` header as well: http://eter4u55b667kuo72ntpm7ut54sa2mxmr22iqgzns4jw7boeox3qgyid.onion/

**Comment by jeromecst** [comment]
The onion site is down again.

**Comment by Solomon1732** [comment]
The onion site is down again
