### ISSUE TITLE
Use SVG animation on the Linux page 

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#712]
## Description

**URL of affected page:** https://privacyguides.org/linux-desktop/

Replace https://privacyguides.org/assets/img/linux-desktop/updates.gif with an animated SVG as mentioned in https://github.com/privacyguides/privacyguides.org/pull/491#issuecomment-1055446948

This animation was only ever going to be borrowed temporarily.

We could do something better with:

- https://inkscape.org/learn/animation/
- https://en.wikipedia.org/wiki/SVG_animation

**Comment by lx-is** [comment]
Ideally you'd want the animation to use CSS animations as opposed to embedding JavaScript in the SVG, right?

**Comment by dngray** [comment]
Correct @lx-is

**Comment by lx-is** [comment]
Okay. I was just curious, I started looking into SVG animations but it all seems a bit over my head 😅

**Comment by dngray** [comment]
Might close this one as we don't need it anymore.
