### ISSUE TITLE
Recent Updates to DivestOS

### ISSUE THREAD

**Issue by SkewedZeppelin** [privacyguides/privacyguides.org#730]
## Description
DivestOS now has many additional hardening features thanks to GrapheneOS, including the hardened memory allocator on 18.1.
https://divestos.org/index.php?page=news#2022-03.3

**URL of affected page:** https://www.privacyguides.org/android/

**Comment by tommytran732** [comment]
Are the builds all ready yet? I updated to the March 14 build and the Bromite webview option mentioned in the update notes doesn't actually work (it only allows the user to use the Mulch webview and that's it).

**Comment by dngray** [comment]
Also happy to take PR from you @SkewedZeppelin, and yes I do note you're the author of DivestOS, but that's okay, we will check/commit accuracy.
