### ISSUE TITLE
Etesync removal (at least tell to user to be wary and check it themselve)

### ISSUE THREAD

**Issue by BirdInFire** [privacyguides/privacyguides.org#731]
## Description
Etesync isn't updated anymore, i tried to ask them but they close the issue as fast as possible and restrict any answer from me, and even listing the number of update they haven't done (with countaine hight to low security issue, only have pushed them to close and tell i mislead user (without any proof of course), 

but the fact that their server app and ios app isn't updated for more than a year remain, so you musn't lead user to their fall with an unsecure services.

**URL of affected page: https://www.privacyguides.org/software/calendar-contacts/**

proof of their intentional lie : 
https://github.com/etesync/server/commit/056d6853a0a9f1c7918e0d7d8a4ae9b8fea393ed

witch correct what i have reported (there is another security issue but not in the django library) and they haven't corrected it.

and their git page you can see nearly all repo aren't updated for month (year in the worst case) : https://github.com/etesync

**Comment by ph00lt0** [comment]
Perhaps you didn't read the reply you have gotten: https://github.com/etesync/server/issues/122#issuecomment-1069743530

**Comment by BirdInFire** [comment]
it's not the fact they do not it imedatly, it the fact they say is not true, update it and block me from report all the security issue i have found out.

**Comment by ph00lt0** [comment]
Sometimes things can be vulnerable but in the way that they are used not have any effect. It's better practice to keep things updated, but from what I am reading the developer gives good arguments.

**Comment by BirdInFire** [comment]
> Sometimes things can be vulnerable but in the way that they are used not have any effect. It's better practice to keep things updated, but from what I am reading the developer gives good arguments.

And for an app who use crypto library who have a shitload of security update every month, a year without update isn't normal, and if they tell that none of their library had update i can safely tell they lie.

**Comment by BirdInFire** [comment]
@ph00lt0 But at least add a warning to check because: not updated = be carful, their strange reaction to my report (update and block, carful x 2.

I do not say they are breached uninstall it imedatly i just say user must be warned that something is strange.

**Comment by BirdInFire** [comment]
> @ph00lt0 There are more responses on [etesync/server#123](https://github.com/etesync/server/issues/123)
> 
> While I do agree the lack of update is concerning, I have reported issues in the past because new versions of python, I also think is valid to report it here, the tone was complete unnecessary, no need to open issues like "Not updated, not secured, nightmare !! update your library !!!!" and " hiding youself behind it's work from decade blabla" in a open- source project Stop using it and report, no need for drama.

its very true and it was my fault for that and i had excused and modified it myself if they wasn't closing and of course blocking me nearly immediately.

**Comment by victor-rds** [comment]
@BirdInFire I do understand both of you in this case, although the block was too fast for my taste, I do understand that in bad day I too would block out of rage.

Good luck mate!
