### ISSUE TITLE
Update all V2 onion links to V3

### ISSUE THREAD

**Issue by unbeatable-101** [privacyguides/privacyguides.org#74]
## Description

Looking at the site, a lot of links are V2, which has been deprecated, they should be updated to V3

**Comment by katzeprior** [comment]
Can you link more that are not in issue #52 
would help the devs i think.

**Comment by unbeatable-101** [comment]
I only found one for DuckDuckGo and Tor

Tor: http://2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion

DuckDuckGo: https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/
