### ISSUE TITLE
Modify font to include Qubes icon

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#743]
## Description

**URL of affected page:** https://privacyguides.org/qubes/

Modify the Qubes OS page to include an icon for the nav menu. We'd  like to use the Q from https://www.qubes-os.org/doc/visual-style-guide/#logos for that.

**Comment by lx-is** [comment]
Does PG have Font Awesome Pro? If so, you can upload custom icons through them.

**Comment by elitejake** [comment]
Yes, this repository does have Font Awesome Pro. 

> If so, you can upload custom icons through them.

That's handy. Why haven't we used it, though?

**Comment by elitejake** [comment]
Fixed in #751. Can be closed now.
