### ISSUE TITLE
Add links to blog feed on the site

### ISSUE THREAD

**Issue by lx-is** [privacyguides/privacyguides.org#769]
Now that #25 is finally closed, a link to the blog's feed should be implemented somewhere on the site as suggested in https://github.com/privacyguides/privacyguides.org/issues/25#issuecomment-1066774714.

**Comment by gracjankn** [comment]
My suggestion is to either include a feed link in the top-right corner (after the "Blog" link in the navbar) or on the Blog page, beside the "Blog" word.

I can make a pull request with this change, if I get some feedback on where others think the link should be.

**Comment by lx-is** [comment]
I don't think it's important enough to put it in the navbar. Somewhere on either the blog page or footer would be best.

If it goes in the footer, something like this could work: 

```diff footer.html
- <p><small>This content was made available by the <a href="https://github.com/orgs/privacyguides/people">Privacy Guides team</a> and <a href="https://github.com/privacyguides/privacyguides.org/graphs/contributors?from=2019-05-11&type=c&to={{ site.build.date }}">contributors</a>. <a href="https://github.com/privacyguides/privacyguides">Get involved</a>! | <a href="https://github.com/privacyguides/privacyguides.org/issues">Open an Issue</a> | <a href="/privacy-policy/">Privacy Policy</a> | <a href="/terms-and-notices/">Website Terms &amp; Notices</a></small></p>
+ <p><small>This content was made available by the <a href="https://github.com/orgs/privacyguides/people">Privacy Guides team</a> and <a href="https://github.com/privacyguides/privacyguides.org/graphs/contributors?from=2019-05-11&type=c&to={{ site.build.date }}">contributors</a>. <a href="https://github.com/privacyguides/privacyguides">Get involved</a>! | <a href="https://github.com/privacyguides/privacyguides.org/issues">Open an Issue</a> | <a href="/privacy-policy/">Privacy Policy</a> | <a href="/terms-and-notices/">Website Terms &amp; Notices</a> | <a href="/feed.json">JSON Feed</a> · <a href="/feed.xml">RSS Feed</a></small></p>
```

![](https://user-images.githubusercontent.com/100533118/160193820-146af7f2-c01d-4b72-b69c-80e82e571145.png)


Alternatively, if it goes on the blog page itself, you could use Font Awesome in a similar way to how the link icon is used on some headers.

![](https://user-images.githubusercontent.com/100533118/160194913-a3d22eda-47e4-466b-baf1-3bfa52d81ca5.png)
