### ISSUE TITLE
Fix handling of 404 errors

### ISSUE THREAD

**Issue by lx-is** [privacyguides/privacyguides.org#774]
Visiting a page that doesn't exist results in a generic Apache "Not Found" error rather than https://privacyguides.org/404/

**Comment by lx-is** [comment]
???

**Comment by elitejake** [comment]
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

The `ErrorDocument` is pointing to a file that doesn't exist. Pinging @jonaharagon

**Comment by jonaharagon** [comment]
Fixed
