### ISSUE TITLE
Website Issue | Table of Contents

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#802]
Some pages are starting to get quite lengthy, so we should look into a Table of Contents plugin for jekyll.

Should be fairly possible, as all the headings are anchored links.

**Comment by elitejake** [comment]
Since we are using kramdown, we can add TOC by using `{:toc}` according to [this](https://stackoverflow.com/a/36658757/15394638).

**Comment by dngray** [comment]
We're thinking long term, of doing something better than that.

Personally I really like these examples, such as the [Vault](https://learn.hashicorp.com/tutorials/vault/getting-started-install), which uses [NextJS](https://nextjs.org/docs). [Qubes OS](https://www.qubes-os.org/doc/how-to-edit-the-documentation/) is also pretty good.

We could also use mkdocs https://squidfunk.github.io/mkdocs-material/getting-started/ which https://www.chezmoi.io uses.

Looks a little nicer than https://readthedocs.io used by the Linux kernel https://www.kernel.org/doc/html/latest/index.html

**Comment by dngray** [comment]
@jonaharagon if we do use mkdocs, which I think is a good idea, we can ditch the jekyll blog and maybe use Gatsby.

I really like how the [matrix blog](https://matrix.org/blog/posts) is. Especially with the way post/dates are in folders rather than the filename of the blog article, for example:

https://raw.githubusercontent.com/matrix-org/matrix.org/master/gatsby/content/blog/2022/03/2022-03-22-synapse-1.55.mdx

**Comment by elitejake** [comment]
I have experience with mkdocs-material. There is a tiny problem, we'll have to [self-host Roboto fonts](https://github.com/squidfunk/mkdocs-material/issues/739#issuecomment-1036027153) or use their [privacy](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=privacy#built-in-privacy-plugin) plugin. By default, mkdocs-material uses the [Google Fonts CDN](https://fonts.google.com/), which is not privacy friendly. See the [issue](https://github.com/squidfunk/mkdocs-material/issues/739) behind it.

**Comment by elitejake** [comment]
[Furo](https://github.com/pradyunsg/furo) is similar to mkdocs-material and has a toc on the right. But the problem is that the docs should be written in [reStructured Text](https://en.wikipedia.org/wiki/ReStructuredText), which is [way harder](https://learnxinyminutes.com/docs/rst) than markdown.

It is used by [urllib3](https://urllib3.readthedocs.io/en/stable/), [black](https://black.readthedocs.io/en/stable/) and other Python projects.

**Comment by dngray** [comment]
> I have experience with mkdocs-material. There is a tiny problem, we'll have to [self-host Roboto fonts](https://github.com/squidfunk/mkdocs-material/issues/739#issuecomment-1036027153) or use their [privacy](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=privacy#built-in-privacy-plugin) plugin. By default, mkdocs-material uses the [Google Fonts CDN](https://fonts.google.com/), which is not privacy friendly. See the [issue](https://github.com/squidfunk/mkdocs-material/issues/739) behind it.

We'd probably self-host, that.

> [Furo](https://github.com/pradyunsg/furo) is similar to mkdocs-material and has a toc on the right. The con is that the docs should be written in [reStructured Text](https://en.wikipedia.org/wiki/ReStructuredText), which is [way harder](https://learnxinyminutes.com/docs/rst) than markdown.
> 
> It is used by [urllib3](https://urllib3.readthedocs.io/en/stable/), [black](https://black.readthedocs.io/en/stable/) and other Python projects.

Interestingly, that's mentioned here https://squidfunk.github.io/mkdocs-material/alternatives/#sphinx

**Comment by elitejake** [comment]
Yeah, mkdocs-material has more features than Furo. If we're are going to pay for their [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) program, I'd say it'll be worth it.

**Comment by dngray** [comment]
> If we're are going to pay for their [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) program, I'd say it'll be worth it.

We would, I'm sure we can afford to send a few dollars that way, it would mean we have a healthy environment to work in which is continuously improved.

Even without the insiders program you can still self build https://squidfunk.github.io/mkdocs-material/insiders/?h=#compatibility

**Comment by elitejake** [comment]
Will this result in changing of PG logo and color palette?

**Comment by dngray** [comment]
> Will this result in changing of PG logo and color palette?

would need to speak to @jonaharagon about that, but I would like to take care of https://github.com/privacyguides/privacyguides.org/issues/525 at the same time.

**Comment by elitejake** [comment]
A pro of using Jerkyll over mkdocs is that we can split a page into sections which are separate files. If there are two PRs on different sections on the same page, we can merge them without conflict. 
Is there a direct way to do this in mkdocs? We could probably do this with a plugin though.

**Comment by dngray** [comment]
Done as a part of https://github.com/privacyguides/privacyguides.org/pull/829
