### ISSUE TITLE
Website Issue | can't reach the privacyguides.org

### ISSUE THREAD

**Issue by BUZZ-clr** [privacyguides/privacyguides.org#803]
## Description 
I can't reach https://privacyguides.org  ! 
I used to use this site all the time, I can acces it. 
But, i don't know whats happend. I can not acces to this site at all. No matter what i do to slove this problem, issiuse is still countines for me. I tried many ways to slove this and acces it again, Unfortunately I can't do anything anymore 😕
Nothing works. 

In my country are no have to ' privacy stricts ' i think gov does not blocked it. Or, blocked ? I don't know idk how can i check there is no info or warning shared. 

When i try to acces to privacyguides'  i always got "Connection Reset" or sometimes " connection time out "   error. But, i contacted our ISP and they say there is no limitations or they did not do anything. Evrything is stable. Why is this happening then ?  Please help me to acces to this site again. I really love to using and getting useful infos about privacy. Thank you very much <3 

## Screenshots

Fire Fox 

![Screenshot_20220327-175817_Firefox.jpg](https://user-images.githubusercontent.com/67105085/160285174-779c9ff8-f307-450d-a3ee-f6a894bf7503.jpg)

Brave 

![Screenshot_20220327-180018_Brave.jpg](https://user-images.githubusercontent.com/67105085/160285179-e47bb260-d517-48b2-bd3e-4501068c4240.jpg)

**Comment by dngray** [comment]
Please contact me via https://polarbear.army the details here.
