### ISSUE TITLE
Kryptor is no longer in beta

### ISSUE THREAD

**Issue by samuel-lucas6** [privacyguides/privacyguides.org#83]
## Description
As of [v3.0.3](https://github.com/samuel-lucas6/Kryptor/releases/tag/v3.0.3), Kryptor is no longer in beta.

**URL of affected page:**
https://privacyguides.org/software/productivity/#encrypt

**Comment by NSABackdoors** [comment]
Mentioned in #52

**Comment by samuel-lucas6** [comment]
> 
> 
> Mentioned earlier and added pull request to #52

Sorry! Didn't see that. Many thanks.
