### ISSUE TITLE
Website Issue | Re-add RSS

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#833]
Now that we're not using Jekyll, we probably need to re-add [RSS Autodiscovery](https://www.rssboard.org/rss-autodiscovery)

Maybe we can evaluate https://github.com/Guts/mkdocs-rss-plugin

**Comment by dngray** [comment]
Might be better to use https://github.com/maedadev/mkdocs-atom-plugin

**Comment by garret** [comment]
Ok I can see it was not me who has noticed the disappearance of the rss reader. Will subscribe to see updates to this as this was the only way for me keeping updated with the website.

**Comment by dngray** [comment]
Yeah it happened when we moved from using Jekyll over to mkdocs-material, it's definitely on our to do list to re-add.

I wouldn't mind adding atom/jsonfeed if we can too.

**Comment by lx-is** [comment]
> Ok I can see it was not me who has noticed the disappearance of the rss reader. Will subscribe to see updates to this as this was the only way for me keeping updated with the website.

Obviously not an ideal solution, but in the meantime you can subscribe to the recent commits log: https://github.com/privacyguides/privacyguides.org/commits.atom

<br>

<br>

I'm planning on taking a shot at re-adding the RSS feed sometime this week. But, from the bit of reconnaissance I've done on the issue it doesn't seem as easy as #25, so I'm not sure if I'll be successful in doing so lol

**Comment by dngray** [comment]
This has been fixed as we're now using wordpress for that.
