### ISSUE TITLE
Website Issue | Right side "overflow"

### ISSUE THREAD

**Issue by 1hiking** [privacyguides/privacyguides.org#837]
## Description

On mobile devices, the left side will overflow, it seems to be caused by the buttons on the bottom.

Hopefully not an upstream issue so that it can be fixed :B

## Screenshots

![image](https://user-images.githubusercontent.com/73438877/161344858-09431b90-eaed-47ed-af12-30efc8514ac8.png)

**Comment by dngray** [comment]
Hmm, I tried this on my phone and couldn't reproduce, could you provide steps to reproduce?

**Comment by jonaharagon** [comment]
Fixed in #843
