### ISSUE TITLE
Create Security Advanced section, mention Age, Minisign, Signify

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#845]
Following on from https://github.com/privacyguides/privacyguides.org/pull/293#issuecomment-1086547448

I think it might be worthwhile to have a "Security Advanced" section as well as the "Security Basics". I do want to write an article for the Basics section that incorporates what is https://github.com/privacyguides/privacyguides.org/discussions/468

Likewise now that Infosec Handbook seems permanently offline, we could write an article which demonstrates [Minisign](https://web.archive.org/web/20210813101914/https://infosec-handbook.eu/tutorials/tool-minisign/), and [Signify](https://web.archive.org/web/20210814181026/https://infosec-handbook.eu/tutorials/tool-signify/) and their use with [Age](https://github.com/FiloSottile/age/).

I think advanced guides are actually good, as well, because even IT fluent people, including developers often need guidance.

**Comment by samuel-lucas6** [comment]
That's a good idea. Shame their site has gone down; not sure what happened there as they were talking about rewriting old articles or something not that long ago.

**Comment by realguyman** [comment]
I believe all CLI applications should only be presented in the “Advanced Security” section.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Would this also include something like 'only use ethernet cables at home instead of wifi?'

**Comment by dngray** [comment]
I'm not sure we will bother with this, seeing as other projects like grapheneos now use ssh-keygen for verifying signatures. For ease of use we recommend Kryptor which takes care of the encryption/authentication.
