### ISSUE TITLE
Website Issue | Remove mathjax code and use privacy plugin?

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#848]
Will remove external mathjax resource, can use some local code for now.

Looking at https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin also.

**Comment by realguyman** [comment]
Do we need to include MathJax from a CDN, or are we strictly removing it?

**Comment by dngray** [comment]
> Do we need to include MathJax from a CDN, or are we strictly removing it?

Removing it, i prefer not have external links, it was added in early prototype, as we use some on the Android page.
