### ISSUE TITLE
Add a disclaimer to the old Firefox privacy blog post, or better yet remove it altogether 

### ISSUE THREAD

**Issue by RandPotato** [privacyguides/privacyguides.org#868]
## Description
Title says it all

**URL of affected page:**
https://privacyguides.org/blog/2019/11/09/firefox-privacy/

**Comment by EdwardLangdon** [comment]
I think that it will acts as an Archive

**Comment by dngray** [comment]
Normally what I've seen in situations like this an admonishment is added to the top directing to the most current article.
