### ISSUE TITLE
Website Issue | Use prefers-color-scheme

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#869]
https://github.com/privacyguides/privacyguides.org/discussions/851

https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference

**Comment by lx-is** [comment]
It seems to use the media query when the page is loaded for the first time, but does not automatically change after that initial load. You can test this by changing your system color scheme and loading the page in a private browsing window.

I believe that is the intended MkDocs Material behavior though. At least I think so from reading: https://github.com/squidfunk/mkdocs-material/issues/2727 & https://github.com/squidfunk/mkdocs-material/issues/3123 & https://github.com/squidfunk/mkdocs-material/issues/3244. I am tired, so it is a possibility I just read through those wrong.

https://github.com/jannismain/mkdocs-system-preference-theme-toggle aims to add the auto switching functionality.

**Comment by dngray** [comment]
I just checked this, and you're right.
