### ISSUE TITLE
Incorrect label for KeePassDX's F-Droid package link

### ISSUE THREAD

**Issue by realguyman** [privacyguides/privacyguides.org#879]
## Description

KeePassDX incorrectly labels a link pointing to the F-Droid package as an iOS App on their store: https://github.com/privacyguides/privacyguides.org/blob/0a7f85ceeb87d18369322a149f9739715a133c1f/docs/passwords.md?plain=1#L53

**URL of affected page:** https://privacyguides.org/passwords/#keepassdx

**Comment by dngray** [comment]
Ah, must have have happened when i copy pasted the as a template, will fix.
