### ISSUE TITLE
Website Issue | New layout is hard to navigate

### ISSUE THREAD

**Issue by MrGoatsy** [privacyguides/privacyguides.org#881]
The new layout is hard to navigate, the site looks to cluttered now and the big yellow header hurts my eyes.

It would be great if it could be a darker colour yellow and the old menu at the top could come back with the drop downs.

**Comment by flexagoon** [comment]
The website is fine on desktop (although the previous version was better), but on mobile it's just awful

**Comment by realguyman** [comment]
Please make a clear case on how it is hard to navigate, and optionally how we could improve it.

“It's just awful” or “it's hard to navigate” doesn't help us.

**Comment by MrGoatsy** [comment]
The old website had clear categories as top for the drop down menu. I would like to have those brought back.

The old layout had this:
https://i.imgur.com/N2yC6XN.png

The new layout has this:
https://i.imgur.com/Z2mUrJ7.png

While the search function is great, it now requires more clicks to find the features which were previously in the drop down menu.

**Comment by realguyman** [comment]
PrivacyGuides is no longer simply recommending tools. We have separate categories to distinguish tool recommendations and other content such as a complete section on explaining 2FA.

Maybe we can choose better wording for these categories.

**Comment by ph00lt0** [comment]
I must say I also quite dislike the new navigation. The sidebar navigation is way to long buy having all recommendations in the same place. Would be better to split it up per category like we actually had before. So rather then having recommendations in the main menu have Operating Systems, Browsers, Providers, and Software located there. 

That would return the overview in the website and also lets you more quickly navigate to the right page.

**Comment by dngray** [comment]
We now have single page layout in https://privacyguides.org/tools/

**Comment by ph00lt0** [comment]
@dngray yeah it's not great in my opinion. It's a lot harder to find things.

**Comment by realguyman** [comment]
At this point, it only takes two clicks to get to any recommended tool category from the landing page.

> The sidebar navigation is way to long

I don't think it is. Seems pretty subjective. And it's really quite a short scroll to get through the entire sidebar. Besides, if you don't like the sidebar, then you can scroll the https://www.privacyguides.org/tools/ page.

> I must say I also quite dislike the new navigation.

Subjective. I like it.

> So rather then having recommendations in the main menu have Operating Systems, Browsers, Providers, and Software located there.

If by “main menu” you mean the top navigation bar, then no, I disagree. Having to click on “recommendations” link doesn't prevent you from accessing the content. *The wording could probably use a re-evaluation, though.*

**Comment by MrGoatsy** [comment]
Any update regarding this?

**Comment by realguyman** [comment]
@MrGoatsy Is there any _actual issues_ with the current design? As I already stated, the amount of clicks it takes to get to content is 3. I'm not seeing what needs to be "fixed", or updated here.

**Comment by MrGoatsy** [comment]
It used to be 2 clicks and there is no reason it should be more than the absolute minimum.

Navigating a website should be as easy as possible for the end user.
