### ISSUE TITLE
Lemmy

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#9]
TODO:

- [x] Merge https://github.com/privacytools/privacytools.io/pull/2154 into `main`
- [ ] ~~Host Privacy Guides Lemmy instance https://github.com/privacytools/privacytools.io/issues/2140#issuecomment-761577424~~
     - Probably a good idea, better than hosting another forum for this project.

**Comment by LongJohn-Silver** [comment]
Why don't you simply create a community? I feel like this project is too new for a whole instance.
