### ISSUE TITLE
Mullvad Port Forwarding Restrictions

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#92]
## Description

Received this message on Reddit.

**URL of affected page:** https://privacyguides.org/providers/vpn/

> Under Port Forwarding for Mullvad it says:
>
> > Remote port forwarding is allowed on Mullvad, see Port forwarding with Mullvad VPN.
>
> But I think it should be mentioned that port forwarding is only allowed if you make one-time payments, if you have a subscription setup it's not allowed.
>
> > Port forwarding is not allowed for accounts that have an active automatic recurring subscription (via PayPal or credit card). It is therefore not possible to add ports to such accounts. If you have an automatic subscription then you can log in to your account, click on "Manage subscription" and cancel it. Your current time will remain on the account and you can make manual one-time payments from then on.
>
> https://mullvad.net/en/help/port-forwarding-and-mullvad/
>
> Might be a minor thing but had an issue with this so why I'm sending this.

**Comment by NSABackdoors** [comment]
That seems like something odd to add. Have you received any reasoning as to why this is the case?

**Comment by Dyrimon** [comment]
> That seems like something odd to add. Have you received any reasoning as to why this is the case?

I assume this is to evade the copyright trolls asking Mullvad to connect the static port to that specific user as IPs and ports are public. If customer uses anonymous one-time payment system that has no trace to them, Mullvad can tell them we don't know which user is using that port as we don't keep tracks of onetime payment

They explained this in their blog post: https://mullvad.net/en/blog/2021/3/22/minor-change-our-terms-service/

**Comment by NSABackdoors** [comment]
> I assume this is to evade the copyright trolls asking Mullvad to connect the static port to that specific user as IPs and ports are public. If customer uses anonymous one-time payment system that has no trace to them, Mullvad can tell them we don't know which user is using that port as we don't keep tracks of onetime payment

This makes sense. Thanks for the explanation.
