### ISSUE TITLE
Separate browser extensions

### ISSUE THREAD

**Issue by elitejake** [privacyguides/privacyguides.org#940]
## Description

Since the **Browsers** section has just one link (to [Web Browsers](https://www.privacyguides.org/browsers/)), I propose we separate browser extensions to another page. It looks like this and feels empty:

![browsers](https://user-images.githubusercontent.com/74049394/162254098-cfb3d5ce-b14b-40a9-8840-390352bc4d32.png)

**Alternative:** Directly link browser extensions in nav to https://www.privacyguides.org/browsers/#additional-resources

**Comment by dngray** [comment]
We could just link to https://www.privacyguides.org/browsers/#ublock-origin now, as all headings are links.

I don't think we need a separate page, there's only things, and only two of them are extensions.
