### ISSUE TITLE
Website Issue | 2 broken links in Privacy Policy

### ISSUE THREAD

**Issue by taivlam** [privacyguides/privacyguides.org#942]
## Description

There are 2 broken links in the [section](https://www.privacyguides.org/about/privacy-policy/#how-can-i-find-out-about-changes-to-this-document) titled "How can I find out about
changes to this document?" in the Privacy Policy.  (The exact URL used
is the same for both, but each respective link is used with a different
purpose.)

I didn't want to make a pull request because I didn't know if there are
better solutions.

1)  First, the link for any new changes is no longer valid and is using:
    ```
    https://www.privacyguides.org/about/privacy-policy.md
    ```

(The `.md` suffix is the invalid part, leading to a 404 Not Found page.)

Instead, to pragmatically fix this, this should be pointed to at least the
GitHub [commit history](https://github.com/privacyguides/privacyguides.org/commits/main/docs/about/privacy-policy.md).  Alternatively, the corresponding [source](https://github.com/taivlam/privacyguides.org/blob/main/docs/about/privacy-policy.md) on
GitHub can be linked in the final sentence:

> "A full revision history of this page can be found on GitHub."

However, I am unsure about this method being appropriate if the absolute
path to the Privacy Policy changes.

2)  The link for contact information intends to point to another page
with this info.

However, the only contact info currently is in the [section](https://www.privacyguides.org/about/privacy-policy/#how-can-i-contact-the-privacy-guides-team-about-privacy=) right above,
titled "How can I contact the Privacy Guides team about privacy?"

**Comment by realguyman** [comment]
I'm not sure if Jonah intended for the URL to point to `privacy-policy` instead of `privacy-policy.md`. But either way I'll submit a PR that links to GitHub commits until we can find a better solution.

He might've ported over our already written privacy policy from the old site. I'm not sure. I'll get the links functioning, at least.
