### ISSUE TITLE
Building a threat model

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#947]
I haven't decided whether this should be a part of the threat modeling page, but I'm thinking maybe not.

I'm thinking we should include https://github.com/privacyguides/privacyguides.org/discussions/468 under a "building a threat" page.

I wouldn't mind covering jurisdiction at the same time such as what is mentioned in https://github.com/privacyguides/privacyguides.org/pull/937

The TLDR of that is, consider where *you* are, consider the privacy policy of the service you intend to use and the laws of the country where that service resides.

Rather than a "good list of countries" or "bad list" which changes regularly.

**Comment by Sirwhofromwhere** [comment]
In my opinion 'building a threat' should be part of the threat modelling page. As the Knowledge Base expands with further sections, it will be important to consolidate as much as possible in to directly relevant categories. That is unless you are able to implement a sub-category feature where clicking on the main category in the list presents a drop down, and then hyperlinking & referencing at the bottom of the page to it for further learning on that subject.

Approaching topics with overlap with a first priority of finding ways to incorporate them under the same category, whether that requires re-writing of the original page to capture all the information efficiently or simply expanding the page to a greater number of words, is the best long term strategy as it will always be easier to simply create another section. The cost of which is an unapproachable category list that discourages a snack approach to reading.

**Comment by dngray** [comment]
So in this issue I'm thinking we should address:

  - https://github.com/privacyguides/privacyguides.org/discussions/468

This leads into:

- https://github.com/privacytools/privacytools.io/issues/1437#issuecomment-546845665
  - https://github.com/privacyguides/privacyguides.org/pull/937
    - Email
    - VPN (Also looking at adding Windscribe in this PR as discussion 
      https://github.com/privacyguides/privacyguides.org/discussions/372#discussioncomment-1691195
- https://github.com/privacyguides/privacyguides.org/issues/1020 (this one we can start minimally, and people can expand via PR), it needs to mostly be a stub for translators.

Few reasons for this:

- Eyes is not the only agreement, geographical location of the user is relevant to determine immediate threats in threat model
- Privacy is obtained through using strong E2EE, and not spraying data about yourself all over the internet, which is the reason for: https://github.com/privacyguides/privacyguides.org/discussions/949

Might possibly look at something that addresses https://github.com/privacyguides/privacyguides.org/discussions/888, I'm not quite sure what that would look like.
