### ISSUE TITLE
Website Issue | Sidebar non-scrollable without Javascript

### ISSUE THREAD

**Issue by subnut** [privacyguides/privacyguides.org#978]
**EDIT:** The scrollbar is lacking only when Javascript is disabled. (See discussion below.)

## Description
On smaller screens, the sidebar's full length isn't completely visible, nor is it obvious that the sidebar has been rendered incomplete (due to the lack of a scrollbar). 
![20220411_22h07m05s_grim](https://user-images.githubusercontent.com/56714626/162788167-0f28f9cb-936e-48b7-a6d2-6088174cc80f.png)

Look at the above screenshot. At first glance, who can tell that the sidebar contains more entries? I certainly wasn't able to, until I had scrolled to the _very end_ of the page.

And even after I'd realized that the sidebar is incomplete, there's no way to scroll it!

I'm no web designer, but isn't the sidebar intended to give a **complete** overview of the current page, and have clickable items to jump to the headers? 😆 

## Suggestions

- Maybe collapse the list to the main headers (eg. Browsers, Operating Systems, **Service** providers, ...) and expand the sub-entries of the main header when it is clicked/tapped on?
  - Could the `<details>` and `<summary>` HTML tags be used?
  - I wonder how [libera.chat](https://libera.chat/) is doing those drop-downs on their top bar (About, Contribute, etc..) without using JavaScript
- Or, find a way to include the scrollbar without destroying the beautiful UI

**Comment by jonaharagon** [comment]
@subnut can you share what OS and browser you are using?

On Chrome on Windows a scrollbar appears to be permanently displayed. The sidebar can be scrolled independently of the page. ✅

On Firefox on macOS a scrollbar appears on page load and then disappears (which I believe is standard behavior for scrollable elements). The sidebar can be scrolled independently of the page. ✅

On Safari on macOS no scrollbar appears, and it doesn't seem like the sidebar can be scrolled independently at all, so you can't see the other elements until scrolling to the bottom of the page. This seems like something that could be fixed. ❌

**Comment by lx-is** [comment]
I think this has something to do with content blockers, not one's screen size. I can tell you don't have scripts enabled for the site because you're lacking a search bar, so try enabling scripts and checking if the sidebar scrollbar appears and is functional.

A quick test on Brave: with the "maxed out" shield options, the sidebar doesn't work as intended, however turning off the shield restores the functionality.

> On Safari on macOS no scrollbar appears, and it doesn't seem like the sidebar can be scrolled independently at all, so you can't see the other elements until scrolling to the bottom of the page. This seems like something that could be fixed.

Safari has the independent scroll bar for me.

**Comment by subnut** [comment]
Ah, it _is_ related to having scripts disabled.  
Enabling scripts fixes the issue.

But why does a scroll bar depend on JavaScript? :thinking:   
Searching requires JS is understandable, but why scrolling?

---

I'm on Firefox 99 on Linux

**Comment by jonaharagon** [comment]
> Safari has the independent scroll bar for me.

Oh, I forgot I had JS disabled in Safari. This is the issue then, I'll see if this has to be the case.

**Comment by jonaharagon** [comment]
@subnut how do you feel about the left and right sidebars on this page with JS disabled? https://deploy-preview-981--privacyguides.netlify.app/android/

**Comment by subnut** [comment]
@jonaharagon 
> @subnut how do you feel about the left and right sidebars on this page with JS disabled? https://deploy-preview-981--privacyguides.netlify.app/android/

It's reasonable, IMO. https://docs.voidlinux.org also does the same.

I approve. :+1:
