### ISSUE TITLE
Website Issue | SSLLabs Ranking can be improved from B to A for privacyguides.org

### ISSUE THREAD

**Issue by AnonyPla** [privacyguides/privacyguides.org#98]
## Description

SSLLabs Ranking can be improved (Currently B). 

https://www.ssllabs.com/ssltest/analyze.html?d=privacyguides.org

There are several issues to correct. Please refer to the report.

## Screenshots

![image](https://user-images.githubusercontent.com/86740652/133888545-93775919-327e-470c-8137-c84c683c94b8.png)

![image](https://user-images.githubusercontent.com/86740652/133888565-9119e419-0894-4db1-ad79-c1263515dc84.png)

**Comment by jamugha** [comment]
The cipher suite could be improved, and enabling HSTS preloaded would also be a great idea.
But the No SNI certificate issue is not a concern especially if right now TLS 1.2 and 1.3 are the only protocols supported, since 99.999999% of clients supporting these also support Server Name Indication.

**Comment by dngray** [comment]
I don't believe this report to be correct anymore. That said the server could support forward secrecy.


![2516109768](https://user-images.githubusercontent.com/48640805/141278584-56f3fc94-0d93-40a6-bb02-933b7b8df128.png)

**Comment by jamugha** [comment]
it's a cipher suite order issue definitely, use this to get an appropriate settting
https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1k&guideline=5.6

**Comment by dngray** [comment]
Going to close this issue as it seems it is fixed.

![2193903546](https://user-images.githubusercontent.com/48640805/161374898-b11a9969-fd14-4de9-8d7e-07bf124b521e.png)
