### ISSUE TITLE
Multi-Factor Authentication description

### ISSUE THREAD

**Issue by razac-elda** [privacyguides/privacyguides.org#999]
The page describes MFA as a 2FA configuration with password+code because it's the most common type, but there's no biometric one.

I think you should expand the explanation of MFA(something you know, have, are) or link the wikipedia article, then continue with the 2FA implementation with password+code.

For example:

> Multi-factor authentication (MFA, or 2FA) is a security mechanism that requires additional steps beyond entering your username (or email) and password. **Add here the "something you x" part** .The most common method are time limited codes you might receive from an SMS or app.

The following paragraph should be edited to reflect what was written earlier.

**[URL of affected page](https://www.privacyguides.org/security/multi-factor-authentication/)**

**Comment by dngray** [comment]
That's a good point, because biometric is used with Windows Hello and all that that. It also tightly integrates with TPM, something else i want to write about.

**Comment by razac-elda** [comment]
But Windows Hello and other similar device unlock methods usually are not MFA, this could be a separate post.

**Comment by jonaharagon** [comment]
> they will still need a device you own **_like_** your phone (something you have) in order to generate the code needed to log in to your account.

This is just an example, we do already cover plenty of non-code-based authentication methods (push notifications, U2F).

We should probably replace mentions of "U2F" on this page with "WebAuthn" which covers the most common biometric MFA method for online applications though.

**Comment by razac-elda** [comment]
My point is more related to the explanation of what MFA is theoretically. The article mentions the concept of "something you know/have" but not "something you are".

And U2F is not related to "something you are" unless we are talking about the Yubikey Bio series, so it would be password+key+fingerprint.

**Comment by jonaharagon** [comment]
> And U2F is not related to "something you are" unless...

No, but WebAuthn can utilize Windows Hello on Windows, or Touch ID on macOS/iOS which was the point I was making.

**Comment by dngray** [comment]
> We should probably replace mentions of "U2F" on this page with "WebAuthn" which covers the most common biometric MFA method for online applications though.

I wouldn't be opposed to that, or just calling it [FIDO2](https://en.wikipedia.org/wiki/FIDO2_Project).

![2116122983](https://user-images.githubusercontent.com/48640805/163410437-3c91023c-e45c-4baf-91d5-c7903d89b9b3.png)

**Comment by dngray** [comment]
> We should probably replace mentions of "U2F" on this page with "WebAuthn" which covers the most common biometric MFA method for online applications though.

I wouldn't be opposed to that, or just calling it [FIDO2](https://en.wikipedia.org/wiki/FIDO2_Project). I believe you can use FIDO2 without WebAuthn, ie like with [SSH](https://developers.yubico.com/SSH/).

**Comment by dngray** [comment]
> My point is more related to the explanation of what MFA is theoretically. The article mentions the concept of "something you know/have" but not "something you are".

I'm pretty sure "something you are" is "something you have". Your fingers and eyes are something you have. The reason this comes up is because biometrics are a turned into a cryptographic fingerprint, validated on a TPM. A password is just "something you know".

I think it might be possible to use biometrics to get the TPM to give a valid response to a server with FIDO2.  FIDO2 supports not just dongles, but "platform authentication" as a MFA and that includes things like a TPM or a Secure Enclave.

**Comment by razac-elda** [comment]
I have always read them as different factors, from online resources to textbooks.

Everything in the end will be translated into cryptography but the difference is the original source.

**Comment by dngray** [comment]
I think it's more the point that Windows Hello can be configured to require MFA, additional devices etc https://www.microsoft.com/en-us/microsoft-365/blog/2018/04/17/windows-hello-fido2-security-keys/

https://www.petervanderwoude.nl/post/configuring-windows-hello-for-business-multi-factor-unlock/
